//
// Copyright (c) 2011 NVIDIA Corporation. 
// All rights reserved. 
// 
// Redistribution and use in source and binary forms, with or without 
// modification, are permitted provided that the following conditions are met: 
// 
// Redistributions of source code must retain the above copyright notice, 
// this list of conditions and the following disclaimer. 
// 
// Redistributions in binary form must reproduce the above copyright notice, 
// this list of conditions and the following disclaimer in the documentation 
// and/or other materials provided with the distribution. 
// 
// Neither the name of the NVIDIA Corporation nor the names of its contributors 
// may be used to endorse or promote products derived from this software 
// without specific prior written permission. 
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
// POSSIBILITY OF SUCH DAMAGE. 
//

//
// DO NOT EDIT - generated by simspec!
//

#ifndef ___ARI2S_H_INC_
#define ___ARI2S_H_INC_
#define CIF_FIFO_DEPTH  16
#define CIF2_FIFO_DEPTH 32
#define CIF_FIFO_WIDTH  32
#define CIF_REPLICATE_MAX_CHANNELS      2
#define APB_REG_ADDR_U  7
#define APB_REG_ADDR_L  2
#define APB_CLIENT_ADDR_U       11
#define APB_CLIENT_ADDR_L       8
#define AUDIO_CNFGLNK_WIDTH     8
#define AUDIO_CNFGLNK_PACKET_0_VECTOR_LENGTH    6
#define AUDIO_CNFGLNK_PACKET_0_CYCLES_BITS      3
#define AUDIO_CNFGLNK_PACKET_0_CYCLES   6
#define AUDIO_CNFGLNK_PACKET_0_CYCLES_MINUS1    5
#define AUDIO_CNFGLNK_PACKET_0_PAUSE_CYCLE      1
#define AUDIO_CNFGLNK_PACKET_0_SIZE_MINUS1      47
#define AUDIO_CNFGLNK_PACKET_0_DATA_U   47
#define AUDIO_CNFGLNK_PACKET_0_DATA_L   16
#define AUDIO_CNFGLNK_PACKET_0_RW       15
#define AUDIO_CNFGLNK_PACKET_0_P        14
#define AUDIO_CNFGLNK_PACKET_0_REG_ADDR_U       13
#define AUDIO_CNFGLNK_PACKET_0_REG_ADDR_L       8
#define AUDIO_CNFGLNK_PACKET_0_CLIENT_ADDR_U    7
#define AUDIO_CNFGLNK_PACKET_0_CLIENT_ADDR_L    4
#define AUDIO_CNFGLNK_PACKET_H  1
#define NV_APBIF_CONFIG_LINK_RXFIFO_DEPTH       1
#define NV_APBIF_CONFIG_LINK_RXFIFO_WIDTH       32
#define NV_APBIF_CONFIG_LINK_TXFIFO_DEPTH       1
#define NV_APBIF_CONFIG_LINK_TXFIFO_WIDTH       39
#define NV_APBIF_CONFIG_LINK_TXFIFO_WIDTH_MINUS1        38
#define NV_APBIF_CONFIG_LINK_TXFIFO_RW  38
#define NV_APBIF_CONFIG_LINK_TXFIFO_RDDR_U      37
#define NV_APBIF_CONFIG_LINK_TXFIFO_RDDR_L      32

// Packet AUDIO_CNFGLNK_PACKET_0
#define AUDIO_CNFGLNK_PACKET_0_SIZE 48

#define AUDIO_CNFGLNK_PACKET_0_DATA_SHIFT                       _MK_SHIFT_CONST(16)
#define AUDIO_CNFGLNK_PACKET_0_DATA_FIELD                       _MK_FIELD_CONST(0xffffffff, AUDIO_CNFGLNK_PACKET_0_DATA_SHIFT)
#define AUDIO_CNFGLNK_PACKET_0_DATA_RANGE                       _MK_SHIFT_CONST(47):_MK_SHIFT_CONST(16)
#define AUDIO_CNFGLNK_PACKET_0_DATA_ROW                 0

#define AUDIO_CNFGLNK_PACKET_0_PAUSE_SHIFT                      _MK_SHIFT_CONST(15)
#define AUDIO_CNFGLNK_PACKET_0_PAUSE_FIELD                      _MK_FIELD_CONST(0x1, AUDIO_CNFGLNK_PACKET_0_PAUSE_SHIFT)
#define AUDIO_CNFGLNK_PACKET_0_PAUSE_RANGE                      _MK_SHIFT_CONST(15):_MK_SHIFT_CONST(15)
#define AUDIO_CNFGLNK_PACKET_0_PAUSE_ROW                        0
#define AUDIO_CNFGLNK_PACKET_0_PAUSE_UNSET                      _MK_ENUM_CONST(0)
#define AUDIO_CNFGLNK_PACKET_0_PAUSE_SET                        _MK_ENUM_CONST(1)

#define AUDIO_CNFGLNK_PACKET_0_RW_SHIFT                 _MK_SHIFT_CONST(14)
#define AUDIO_CNFGLNK_PACKET_0_RW_FIELD                 _MK_FIELD_CONST(0x1, AUDIO_CNFGLNK_PACKET_0_RW_SHIFT)
#define AUDIO_CNFGLNK_PACKET_0_RW_RANGE                 _MK_SHIFT_CONST(14):_MK_SHIFT_CONST(14)
#define AUDIO_CNFGLNK_PACKET_0_RW_ROW                   0
#define AUDIO_CNFGLNK_PACKET_0_RW_WRITE                 _MK_ENUM_CONST(0)
#define AUDIO_CNFGLNK_PACKET_0_RW_READ                  _MK_ENUM_CONST(1)

#define AUDIO_CNFGLNK_PACKET_0_REG_ADDR_SHIFT                   _MK_SHIFT_CONST(8)
#define AUDIO_CNFGLNK_PACKET_0_REG_ADDR_FIELD                   _MK_FIELD_CONST(0x3f, AUDIO_CNFGLNK_PACKET_0_REG_ADDR_SHIFT)
#define AUDIO_CNFGLNK_PACKET_0_REG_ADDR_RANGE                   _MK_SHIFT_CONST(13):_MK_SHIFT_CONST(8)
#define AUDIO_CNFGLNK_PACKET_0_REG_ADDR_ROW                     0

#define AUDIO_CNFGLNK_PACKET_0_CLIENT_ADDR_SHIFT                        _MK_SHIFT_CONST(4)
#define AUDIO_CNFGLNK_PACKET_0_CLIENT_ADDR_FIELD                        _MK_FIELD_CONST(0xf, AUDIO_CNFGLNK_PACKET_0_CLIENT_ADDR_SHIFT)
#define AUDIO_CNFGLNK_PACKET_0_CLIENT_ADDR_RANGE                        _MK_SHIFT_CONST(7):_MK_SHIFT_CONST(4)
#define AUDIO_CNFGLNK_PACKET_0_CLIENT_ADDR_ROW                  0

#define AUDIO_CNFGLNK_PACKET_0_H_SHIFT                  _MK_SHIFT_CONST(0)
#define AUDIO_CNFGLNK_PACKET_0_H_FIELD                  _MK_FIELD_CONST(0xf, AUDIO_CNFGLNK_PACKET_0_H_SHIFT)
#define AUDIO_CNFGLNK_PACKET_0_H_RANGE                  _MK_SHIFT_CONST(3):_MK_SHIFT_CONST(0)
#define AUDIO_CNFGLNK_PACKET_0_H_ROW                    0


// Register I2S_CTRL_0  
#define I2S_CTRL_0                      _MK_ADDR_CONST(0x0)
#define I2S_CTRL_0_SECURE                       0x0
#define I2S_CTRL_0_WORD_COUNT                   0x1
#define I2S_CTRL_0_RESET_VAL                    _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_RESET_MASK                   _MK_MASK_CONST(0xff007737)
#define I2S_CTRL_0_SW_DEFAULT_VAL                       _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_SW_DEFAULT_MASK                      _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_READ_MASK                    _MK_MASK_CONST(0xff007737)
#define I2S_CTRL_0_WRITE_MASK                   _MK_MASK_CONST(0xff007737)
#define I2S_CTRL_0_XFER_EN_TX_SHIFT                     _MK_SHIFT_CONST(31)
#define I2S_CTRL_0_XFER_EN_TX_FIELD                     _MK_FIELD_CONST(0x1, I2S_CTRL_0_XFER_EN_TX_SHIFT)
#define I2S_CTRL_0_XFER_EN_TX_RANGE                     31:31
#define I2S_CTRL_0_XFER_EN_TX_WOFFSET                   0x0
#define I2S_CTRL_0_XFER_EN_TX_DEFAULT                   _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_XFER_EN_TX_DEFAULT_MASK                      _MK_MASK_CONST(0x1)
#define I2S_CTRL_0_XFER_EN_TX_SW_DEFAULT                        _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_XFER_EN_TX_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_XFER_EN_TX_DISABLE                   _MK_ENUM_CONST(0)
#define I2S_CTRL_0_XFER_EN_TX_ENABLE                    _MK_ENUM_CONST(1)

#define I2S_CTRL_0_XFER_EN_RX_SHIFT                     _MK_SHIFT_CONST(30)
#define I2S_CTRL_0_XFER_EN_RX_FIELD                     _MK_FIELD_CONST(0x1, I2S_CTRL_0_XFER_EN_RX_SHIFT)
#define I2S_CTRL_0_XFER_EN_RX_RANGE                     30:30
#define I2S_CTRL_0_XFER_EN_RX_WOFFSET                   0x0
#define I2S_CTRL_0_XFER_EN_RX_DEFAULT                   _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_XFER_EN_RX_DEFAULT_MASK                      _MK_MASK_CONST(0x1)
#define I2S_CTRL_0_XFER_EN_RX_SW_DEFAULT                        _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_XFER_EN_RX_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_XFER_EN_RX_DISABLE                   _MK_ENUM_CONST(0)
#define I2S_CTRL_0_XFER_EN_RX_ENABLE                    _MK_ENUM_CONST(1)

#define I2S_CTRL_0_CG_EN_SHIFT                  _MK_SHIFT_CONST(29)
#define I2S_CTRL_0_CG_EN_FIELD                  _MK_FIELD_CONST(0x1, I2S_CTRL_0_CG_EN_SHIFT)
#define I2S_CTRL_0_CG_EN_RANGE                  29:29
#define I2S_CTRL_0_CG_EN_WOFFSET                        0x0
#define I2S_CTRL_0_CG_EN_DEFAULT                        _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_CG_EN_DEFAULT_MASK                   _MK_MASK_CONST(0x1)
#define I2S_CTRL_0_CG_EN_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_CG_EN_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_CG_EN_DISABLE                        _MK_ENUM_CONST(0)
#define I2S_CTRL_0_CG_EN_ENABLE                 _MK_ENUM_CONST(1)

#define I2S_CTRL_0_SOFT_RESET_SHIFT                     _MK_SHIFT_CONST(28)
#define I2S_CTRL_0_SOFT_RESET_FIELD                     _MK_FIELD_CONST(0x1, I2S_CTRL_0_SOFT_RESET_SHIFT)
#define I2S_CTRL_0_SOFT_RESET_RANGE                     28:28
#define I2S_CTRL_0_SOFT_RESET_WOFFSET                   0x0
#define I2S_CTRL_0_SOFT_RESET_DEFAULT                   _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_SOFT_RESET_DEFAULT_MASK                      _MK_MASK_CONST(0x1)
#define I2S_CTRL_0_SOFT_RESET_SW_DEFAULT                        _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_SOFT_RESET_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_SOFT_RESET_DISABLE                   _MK_ENUM_CONST(0)
#define I2S_CTRL_0_SOFT_RESET_ENABLE                    _MK_ENUM_CONST(1)

#define I2S_CTRL_0_TX_FLOWCTL_EN_SHIFT                  _MK_SHIFT_CONST(27)
#define I2S_CTRL_0_TX_FLOWCTL_EN_FIELD                  _MK_FIELD_CONST(0x1, I2S_CTRL_0_TX_FLOWCTL_EN_SHIFT)
#define I2S_CTRL_0_TX_FLOWCTL_EN_RANGE                  27:27
#define I2S_CTRL_0_TX_FLOWCTL_EN_WOFFSET                        0x0
#define I2S_CTRL_0_TX_FLOWCTL_EN_DEFAULT                        _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_TX_FLOWCTL_EN_DEFAULT_MASK                   _MK_MASK_CONST(0x1)
#define I2S_CTRL_0_TX_FLOWCTL_EN_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_TX_FLOWCTL_EN_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_TX_FLOWCTL_EN_DISABLE                        _MK_ENUM_CONST(0)
#define I2S_CTRL_0_TX_FLOWCTL_EN_ENABLE                 _MK_ENUM_CONST(1)

#define I2S_CTRL_0_OBS_SEL_SHIFT                        _MK_SHIFT_CONST(24)
#define I2S_CTRL_0_OBS_SEL_FIELD                        _MK_FIELD_CONST(0x7, I2S_CTRL_0_OBS_SEL_SHIFT)
#define I2S_CTRL_0_OBS_SEL_RANGE                        26:24
#define I2S_CTRL_0_OBS_SEL_WOFFSET                      0x0
#define I2S_CTRL_0_OBS_SEL_DEFAULT                      _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_OBS_SEL_DEFAULT_MASK                 _MK_MASK_CONST(0x7)
#define I2S_CTRL_0_OBS_SEL_SW_DEFAULT                   _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_OBS_SEL_SW_DEFAULT_MASK                      _MK_MASK_CONST(0x0)

#define I2S_CTRL_0_FRAME_FORMAT_SHIFT                   _MK_SHIFT_CONST(12)
#define I2S_CTRL_0_FRAME_FORMAT_FIELD                   _MK_FIELD_CONST(0x7, I2S_CTRL_0_FRAME_FORMAT_SHIFT)
#define I2S_CTRL_0_FRAME_FORMAT_RANGE                   14:12
#define I2S_CTRL_0_FRAME_FORMAT_WOFFSET                 0x0
#define I2S_CTRL_0_FRAME_FORMAT_DEFAULT                 _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_FRAME_FORMAT_DEFAULT_MASK                    _MK_MASK_CONST(0x7)
#define I2S_CTRL_0_FRAME_FORMAT_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_FRAME_FORMAT_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_FRAME_FORMAT_LRCK_MODE                       _MK_ENUM_CONST(0)
#define I2S_CTRL_0_FRAME_FORMAT_FSYNC_MODE                      _MK_ENUM_CONST(1)

#define I2S_CTRL_0_MASTER_SHIFT                 _MK_SHIFT_CONST(10)
#define I2S_CTRL_0_MASTER_FIELD                 _MK_FIELD_CONST(0x1, I2S_CTRL_0_MASTER_SHIFT)
#define I2S_CTRL_0_MASTER_RANGE                 10:10
#define I2S_CTRL_0_MASTER_WOFFSET                       0x0
#define I2S_CTRL_0_MASTER_DEFAULT                       _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_MASTER_DEFAULT_MASK                  _MK_MASK_CONST(0x1)
#define I2S_CTRL_0_MASTER_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_MASTER_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_MASTER_DISABLE                       _MK_ENUM_CONST(0)
#define I2S_CTRL_0_MASTER_ENABLE                        _MK_ENUM_CONST(1)

#define I2S_CTRL_0_LRCK_POLARITY_SHIFT                  _MK_SHIFT_CONST(9)
#define I2S_CTRL_0_LRCK_POLARITY_FIELD                  _MK_FIELD_CONST(0x1, I2S_CTRL_0_LRCK_POLARITY_SHIFT)
#define I2S_CTRL_0_LRCK_POLARITY_RANGE                  9:9
#define I2S_CTRL_0_LRCK_POLARITY_WOFFSET                        0x0
#define I2S_CTRL_0_LRCK_POLARITY_DEFAULT                        _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_LRCK_POLARITY_DEFAULT_MASK                   _MK_MASK_CONST(0x1)
#define I2S_CTRL_0_LRCK_POLARITY_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_LRCK_POLARITY_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_LRCK_POLARITY_LOW                    _MK_ENUM_CONST(0)
#define I2S_CTRL_0_LRCK_POLARITY_HIGH                   _MK_ENUM_CONST(1)

#define I2S_CTRL_0_LPBK_SHIFT                   _MK_SHIFT_CONST(8)
#define I2S_CTRL_0_LPBK_FIELD                   _MK_FIELD_CONST(0x1, I2S_CTRL_0_LPBK_SHIFT)
#define I2S_CTRL_0_LPBK_RANGE                   8:8
#define I2S_CTRL_0_LPBK_WOFFSET                 0x0
#define I2S_CTRL_0_LPBK_DEFAULT                 _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_LPBK_DEFAULT_MASK                    _MK_MASK_CONST(0x1)
#define I2S_CTRL_0_LPBK_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_LPBK_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_LPBK_DISABLE                 _MK_ENUM_CONST(0)
#define I2S_CTRL_0_LPBK_ENABLE                  _MK_ENUM_CONST(1)

#define I2S_CTRL_0_BIT_CODE_SHIFT                       _MK_SHIFT_CONST(4)
#define I2S_CTRL_0_BIT_CODE_FIELD                       _MK_FIELD_CONST(0x3, I2S_CTRL_0_BIT_CODE_SHIFT)
#define I2S_CTRL_0_BIT_CODE_RANGE                       5:4
#define I2S_CTRL_0_BIT_CODE_WOFFSET                     0x0
#define I2S_CTRL_0_BIT_CODE_DEFAULT                     _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_BIT_CODE_DEFAULT_MASK                        _MK_MASK_CONST(0x3)
#define I2S_CTRL_0_BIT_CODE_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_BIT_CODE_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_BIT_CODE_LINEAR                      _MK_ENUM_CONST(0)
#define I2S_CTRL_0_BIT_CODE_uLAW                        _MK_ENUM_CONST(1)
#define I2S_CTRL_0_BIT_CODE_ALAW                        _MK_ENUM_CONST(2)
#define I2S_CTRL_0_BIT_CODE_RSVD                        _MK_ENUM_CONST(3)

#define I2S_CTRL_0_BIT_SIZE_SHIFT                       _MK_SHIFT_CONST(0)
#define I2S_CTRL_0_BIT_SIZE_FIELD                       _MK_FIELD_CONST(0x7, I2S_CTRL_0_BIT_SIZE_SHIFT)
#define I2S_CTRL_0_BIT_SIZE_RANGE                       2:0
#define I2S_CTRL_0_BIT_SIZE_WOFFSET                     0x0
#define I2S_CTRL_0_BIT_SIZE_DEFAULT                     _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_BIT_SIZE_DEFAULT_MASK                        _MK_MASK_CONST(0x7)
#define I2S_CTRL_0_BIT_SIZE_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_BIT_SIZE_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)
#define I2S_CTRL_0_BIT_SIZE_BIT_SIZE_RSVD                       _MK_ENUM_CONST(0)
#define I2S_CTRL_0_BIT_SIZE_BIT_SIZE_8                  _MK_ENUM_CONST(1)
#define I2S_CTRL_0_BIT_SIZE_BIT_SIZE_12                 _MK_ENUM_CONST(2)
#define I2S_CTRL_0_BIT_SIZE_BIT_SIZE_16                 _MK_ENUM_CONST(3)
#define I2S_CTRL_0_BIT_SIZE_BIT_SIZE_20                 _MK_ENUM_CONST(4)
#define I2S_CTRL_0_BIT_SIZE_BIT_SIZE_24                 _MK_ENUM_CONST(5)
#define I2S_CTRL_0_BIT_SIZE_BIT_SIZE_28                 _MK_ENUM_CONST(6)
#define I2S_CTRL_0_BIT_SIZE_BIT_SIZE_32                 _MK_ENUM_CONST(7)


// Register I2S_TIMING_0  
#define I2S_TIMING_0                    _MK_ADDR_CONST(0x4)
#define I2S_TIMING_0_SECURE                     0x0
#define I2S_TIMING_0_WORD_COUNT                         0x1
#define I2S_TIMING_0_RESET_VAL                  _MK_MASK_CONST(0x1f)
#define I2S_TIMING_0_RESET_MASK                         _MK_MASK_CONST(0x17ff)
#define I2S_TIMING_0_SW_DEFAULT_VAL                     _MK_MASK_CONST(0x0)
#define I2S_TIMING_0_SW_DEFAULT_MASK                    _MK_MASK_CONST(0x0)
#define I2S_TIMING_0_READ_MASK                  _MK_MASK_CONST(0x17ff)
#define I2S_TIMING_0_WRITE_MASK                         _MK_MASK_CONST(0x17ff)
#define I2S_TIMING_0_NON_SYM_EN_SHIFT                   _MK_SHIFT_CONST(12)
#define I2S_TIMING_0_NON_SYM_EN_FIELD                   _MK_FIELD_CONST(0x1, I2S_TIMING_0_NON_SYM_EN_SHIFT)
#define I2S_TIMING_0_NON_SYM_EN_RANGE                   12:12
#define I2S_TIMING_0_NON_SYM_EN_WOFFSET                 0x0
#define I2S_TIMING_0_NON_SYM_EN_DEFAULT                 _MK_MASK_CONST(0x0)
#define I2S_TIMING_0_NON_SYM_EN_DEFAULT_MASK                    _MK_MASK_CONST(0x1)
#define I2S_TIMING_0_NON_SYM_EN_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define I2S_TIMING_0_NON_SYM_EN_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)
#define I2S_TIMING_0_NON_SYM_EN_DISABLE                 _MK_ENUM_CONST(0)
#define I2S_TIMING_0_NON_SYM_EN_ENABLE                  _MK_ENUM_CONST(1)

#define I2S_TIMING_0_CHANNEL_BIT_CNT_SHIFT                      _MK_SHIFT_CONST(0)
#define I2S_TIMING_0_CHANNEL_BIT_CNT_FIELD                      _MK_FIELD_CONST(0x7ff, I2S_TIMING_0_CHANNEL_BIT_CNT_SHIFT)
#define I2S_TIMING_0_CHANNEL_BIT_CNT_RANGE                      10:0
#define I2S_TIMING_0_CHANNEL_BIT_CNT_WOFFSET                    0x0
#define I2S_TIMING_0_CHANNEL_BIT_CNT_DEFAULT                    _MK_MASK_CONST(0x1f)
#define I2S_TIMING_0_CHANNEL_BIT_CNT_DEFAULT_MASK                       _MK_MASK_CONST(0x7ff)
#define I2S_TIMING_0_CHANNEL_BIT_CNT_SW_DEFAULT                 _MK_MASK_CONST(0x0)
#define I2S_TIMING_0_CHANNEL_BIT_CNT_SW_DEFAULT_MASK                    _MK_MASK_CONST(0x0)


// Register I2S_OFFSET_0  
#define I2S_OFFSET_0                    _MK_ADDR_CONST(0x8)
#define I2S_OFFSET_0_SECURE                     0x0
#define I2S_OFFSET_0_WORD_COUNT                         0x1
#define I2S_OFFSET_0_RESET_VAL                  _MK_MASK_CONST(0x0)
#define I2S_OFFSET_0_RESET_MASK                         _MK_MASK_CONST(0x7ff07ff)
#define I2S_OFFSET_0_SW_DEFAULT_VAL                     _MK_MASK_CONST(0x0)
#define I2S_OFFSET_0_SW_DEFAULT_MASK                    _MK_MASK_CONST(0x0)
#define I2S_OFFSET_0_READ_MASK                  _MK_MASK_CONST(0x7ff07ff)
#define I2S_OFFSET_0_WRITE_MASK                         _MK_MASK_CONST(0x7ff07ff)
#define I2S_OFFSET_0_RX_DATA_OFFSET_SHIFT                       _MK_SHIFT_CONST(16)
#define I2S_OFFSET_0_RX_DATA_OFFSET_FIELD                       _MK_FIELD_CONST(0x7ff, I2S_OFFSET_0_RX_DATA_OFFSET_SHIFT)
#define I2S_OFFSET_0_RX_DATA_OFFSET_RANGE                       26:16
#define I2S_OFFSET_0_RX_DATA_OFFSET_WOFFSET                     0x0
#define I2S_OFFSET_0_RX_DATA_OFFSET_DEFAULT                     _MK_MASK_CONST(0x0)
#define I2S_OFFSET_0_RX_DATA_OFFSET_DEFAULT_MASK                        _MK_MASK_CONST(0x7ff)
#define I2S_OFFSET_0_RX_DATA_OFFSET_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define I2S_OFFSET_0_RX_DATA_OFFSET_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)

#define I2S_OFFSET_0_TX_DATA_OFFSET_SHIFT                       _MK_SHIFT_CONST(0)
#define I2S_OFFSET_0_TX_DATA_OFFSET_FIELD                       _MK_FIELD_CONST(0x7ff, I2S_OFFSET_0_TX_DATA_OFFSET_SHIFT)
#define I2S_OFFSET_0_TX_DATA_OFFSET_RANGE                       10:0
#define I2S_OFFSET_0_TX_DATA_OFFSET_WOFFSET                     0x0
#define I2S_OFFSET_0_TX_DATA_OFFSET_DEFAULT                     _MK_MASK_CONST(0x0)
#define I2S_OFFSET_0_TX_DATA_OFFSET_DEFAULT_MASK                        _MK_MASK_CONST(0x7ff)
#define I2S_OFFSET_0_TX_DATA_OFFSET_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define I2S_OFFSET_0_TX_DATA_OFFSET_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)


// Register I2S_CH_CTRL_0  
#define I2S_CH_CTRL_0                   _MK_ADDR_CONST(0xc)
#define I2S_CH_CTRL_0_SECURE                    0x0
#define I2S_CH_CTRL_0_WORD_COUNT                        0x1
#define I2S_CH_CTRL_0_RESET_VAL                         _MK_MASK_CONST(0x0)
#define I2S_CH_CTRL_0_RESET_MASK                        _MK_MASK_CONST(0xff003777)
#define I2S_CH_CTRL_0_SW_DEFAULT_VAL                    _MK_MASK_CONST(0x0)
#define I2S_CH_CTRL_0_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define I2S_CH_CTRL_0_READ_MASK                         _MK_MASK_CONST(0xff003777)
#define I2S_CH_CTRL_0_WRITE_MASK                        _MK_MASK_CONST(0xff003777)
#define I2S_CH_CTRL_0_FSYNC_WIDTH_SHIFT                 _MK_SHIFT_CONST(24)
#define I2S_CH_CTRL_0_FSYNC_WIDTH_FIELD                 _MK_FIELD_CONST(0xff, I2S_CH_CTRL_0_FSYNC_WIDTH_SHIFT)
#define I2S_CH_CTRL_0_FSYNC_WIDTH_RANGE                 31:24
#define I2S_CH_CTRL_0_FSYNC_WIDTH_WOFFSET                       0x0
#define I2S_CH_CTRL_0_FSYNC_WIDTH_DEFAULT                       _MK_MASK_CONST(0x0)
#define I2S_CH_CTRL_0_FSYNC_WIDTH_DEFAULT_MASK                  _MK_MASK_CONST(0xff)
#define I2S_CH_CTRL_0_FSYNC_WIDTH_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define I2S_CH_CTRL_0_FSYNC_WIDTH_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)

#define I2S_CH_CTRL_0_HIGHZ_CTRL_SHIFT                  _MK_SHIFT_CONST(12)
#define I2S_CH_CTRL_0_HIGHZ_CTRL_FIELD                  _MK_FIELD_CONST(0x3, I2S_CH_CTRL_0_HIGHZ_CTRL_SHIFT)
#define I2S_CH_CTRL_0_HIGHZ_CTRL_RANGE                  13:12
#define I2S_CH_CTRL_0_HIGHZ_CTRL_WOFFSET                        0x0
#define I2S_CH_CTRL_0_HIGHZ_CTRL_DEFAULT                        _MK_MASK_CONST(0x0)
#define I2S_CH_CTRL_0_HIGHZ_CTRL_DEFAULT_MASK                   _MK_MASK_CONST(0x3)
#define I2S_CH_CTRL_0_HIGHZ_CTRL_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define I2S_CH_CTRL_0_HIGHZ_CTRL_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define I2S_CH_CTRL_0_HIGHZ_CTRL_NOHIGHZ                        _MK_ENUM_CONST(0)
#define I2S_CH_CTRL_0_HIGHZ_CTRL_HIGHZ                  _MK_ENUM_CONST(1)
#define I2S_CH_CTRL_0_HIGHZ_CTRL_HIGHZ_ON_HALF_BIT_CLK                  _MK_ENUM_CONST(2)

#define I2S_CH_CTRL_0_RX_BIT_ORDER_SHIFT                        _MK_SHIFT_CONST(10)
#define I2S_CH_CTRL_0_RX_BIT_ORDER_FIELD                        _MK_FIELD_CONST(0x1, I2S_CH_CTRL_0_RX_BIT_ORDER_SHIFT)
#define I2S_CH_CTRL_0_RX_BIT_ORDER_RANGE                        10:10
#define I2S_CH_CTRL_0_RX_BIT_ORDER_WOFFSET                      0x0
#define I2S_CH_CTRL_0_RX_BIT_ORDER_DEFAULT                      _MK_MASK_CONST(0x0)
#define I2S_CH_CTRL_0_RX_BIT_ORDER_DEFAULT_MASK                 _MK_MASK_CONST(0x1)
#define I2S_CH_CTRL_0_RX_BIT_ORDER_SW_DEFAULT                   _MK_MASK_CONST(0x0)
#define I2S_CH_CTRL_0_RX_BIT_ORDER_SW_DEFAULT_MASK                      _MK_MASK_CONST(0x0)
#define I2S_CH_CTRL_0_RX_BIT_ORDER_MSB_FIRST                    _MK_ENUM_CONST(0)
#define I2S_CH_CTRL_0_RX_BIT_ORDER_LSB_FIRST                    _MK_ENUM_CONST(1)

#define I2S_CH_CTRL_0_TX_BIT_ORDER_SHIFT                        _MK_SHIFT_CONST(9)
#define I2S_CH_CTRL_0_TX_BIT_ORDER_FIELD                        _MK_FIELD_CONST(0x1, I2S_CH_CTRL_0_TX_BIT_ORDER_SHIFT)
#define I2S_CH_CTRL_0_TX_BIT_ORDER_RANGE                        9:9
#define I2S_CH_CTRL_0_TX_BIT_ORDER_WOFFSET                      0x0
#define I2S_CH_CTRL_0_TX_BIT_ORDER_DEFAULT                      _MK_MASK_CONST(0x0)
#define I2S_CH_CTRL_0_TX_BIT_ORDER_DEFAULT_MASK                 _MK_MASK_CONST(0x1)
#define I2S_CH_CTRL_0_TX_BIT_ORDER_SW_DEFAULT                   _MK_MASK_CONST(0x0)
#define I2S_CH_CTRL_0_TX_BIT_ORDER_SW_DEFAULT_MASK                      _MK_MASK_CONST(0x0)
#define I2S_CH_CTRL_0_TX_BIT_ORDER_MSB_FIRST                    _MK_ENUM_CONST(0)
#define I2S_CH_CTRL_0_TX_BIT_ORDER_LSB_FIRST                    _MK_ENUM_CONST(1)

#define I2S_CH_CTRL_0_EDGE_CTRL_SHIFT                   _MK_SHIFT_CONST(8)
#define I2S_CH_CTRL_0_EDGE_CTRL_FIELD                   _MK_FIELD_CONST(0x1, I2S_CH_CTRL_0_EDGE_CTRL_SHIFT)
#define I2S_CH_CTRL_0_EDGE_CTRL_RANGE                   8:8
#define I2S_CH_CTRL_0_EDGE_CTRL_WOFFSET                 0x0
#define I2S_CH_CTRL_0_EDGE_CTRL_DEFAULT                 _MK_MASK_CONST(0x0)
#define I2S_CH_CTRL_0_EDGE_CTRL_DEFAULT_MASK                    _MK_MASK_CONST(0x1)
#define I2S_CH_CTRL_0_EDGE_CTRL_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define I2S_CH_CTRL_0_EDGE_CTRL_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)
#define I2S_CH_CTRL_0_EDGE_CTRL_POS_EDGE                        _MK_ENUM_CONST(0)
#define I2S_CH_CTRL_0_EDGE_CTRL_NEG_EDGE                        _MK_ENUM_CONST(1)

#define I2S_CH_CTRL_0_RX_MASK_BITS_SHIFT                        _MK_SHIFT_CONST(4)
#define I2S_CH_CTRL_0_RX_MASK_BITS_FIELD                        _MK_FIELD_CONST(0x7, I2S_CH_CTRL_0_RX_MASK_BITS_SHIFT)
#define I2S_CH_CTRL_0_RX_MASK_BITS_RANGE                        6:4
#define I2S_CH_CTRL_0_RX_MASK_BITS_WOFFSET                      0x0
#define I2S_CH_CTRL_0_RX_MASK_BITS_DEFAULT                      _MK_MASK_CONST(0x0)
#define I2S_CH_CTRL_0_RX_MASK_BITS_DEFAULT_MASK                 _MK_MASK_CONST(0x7)
#define I2S_CH_CTRL_0_RX_MASK_BITS_SW_DEFAULT                   _MK_MASK_CONST(0x0)
#define I2S_CH_CTRL_0_RX_MASK_BITS_SW_DEFAULT_MASK                      _MK_MASK_CONST(0x0)
#define I2S_CH_CTRL_0_RX_MASK_BITS_ZERO                 _MK_ENUM_CONST(0)
#define I2S_CH_CTRL_0_RX_MASK_BITS_ONE                  _MK_ENUM_CONST(1)
#define I2S_CH_CTRL_0_RX_MASK_BITS_TWO                  _MK_ENUM_CONST(2)
#define I2S_CH_CTRL_0_RX_MASK_BITS_THREE                        _MK_ENUM_CONST(3)
#define I2S_CH_CTRL_0_RX_MASK_BITS_FOUR                 _MK_ENUM_CONST(4)
#define I2S_CH_CTRL_0_RX_MASK_BITS_FIVE                 _MK_ENUM_CONST(5)
#define I2S_CH_CTRL_0_RX_MASK_BITS_SIX                  _MK_ENUM_CONST(6)
#define I2S_CH_CTRL_0_RX_MASK_BITS_SEVEN                        _MK_ENUM_CONST(7)

#define I2S_CH_CTRL_0_TX_MASK_BITS_SHIFT                        _MK_SHIFT_CONST(0)
#define I2S_CH_CTRL_0_TX_MASK_BITS_FIELD                        _MK_FIELD_CONST(0x7, I2S_CH_CTRL_0_TX_MASK_BITS_SHIFT)
#define I2S_CH_CTRL_0_TX_MASK_BITS_RANGE                        2:0
#define I2S_CH_CTRL_0_TX_MASK_BITS_WOFFSET                      0x0
#define I2S_CH_CTRL_0_TX_MASK_BITS_DEFAULT                      _MK_MASK_CONST(0x0)
#define I2S_CH_CTRL_0_TX_MASK_BITS_DEFAULT_MASK                 _MK_MASK_CONST(0x7)
#define I2S_CH_CTRL_0_TX_MASK_BITS_SW_DEFAULT                   _MK_MASK_CONST(0x0)
#define I2S_CH_CTRL_0_TX_MASK_BITS_SW_DEFAULT_MASK                      _MK_MASK_CONST(0x0)
#define I2S_CH_CTRL_0_TX_MASK_BITS_ZERO                 _MK_ENUM_CONST(0)
#define I2S_CH_CTRL_0_TX_MASK_BITS_ONE                  _MK_ENUM_CONST(1)
#define I2S_CH_CTRL_0_TX_MASK_BITS_TWO                  _MK_ENUM_CONST(2)
#define I2S_CH_CTRL_0_TX_MASK_BITS_THREE                        _MK_ENUM_CONST(3)
#define I2S_CH_CTRL_0_TX_MASK_BITS_FOUR                 _MK_ENUM_CONST(4)
#define I2S_CH_CTRL_0_TX_MASK_BITS_FIVE                 _MK_ENUM_CONST(5)
#define I2S_CH_CTRL_0_TX_MASK_BITS_SIX                  _MK_ENUM_CONST(6)
#define I2S_CH_CTRL_0_TX_MASK_BITS_SEVEN                        _MK_ENUM_CONST(7)


// Register I2S_SLOT_CTRL_0  
#define I2S_SLOT_CTRL_0                 _MK_ADDR_CONST(0x10)
#define I2S_SLOT_CTRL_0_SECURE                  0x0
#define I2S_SLOT_CTRL_0_WORD_COUNT                      0x1
#define I2S_SLOT_CTRL_0_RESET_VAL                       _MK_MASK_CONST(0x0)
#define I2S_SLOT_CTRL_0_RESET_MASK                      _MK_MASK_CONST(0x7ffff)
#define I2S_SLOT_CTRL_0_SW_DEFAULT_VAL                  _MK_MASK_CONST(0x0)
#define I2S_SLOT_CTRL_0_SW_DEFAULT_MASK                         _MK_MASK_CONST(0x0)
#define I2S_SLOT_CTRL_0_READ_MASK                       _MK_MASK_CONST(0x7ffff)
#define I2S_SLOT_CTRL_0_WRITE_MASK                      _MK_MASK_CONST(0x7ffff)
#define I2S_SLOT_CTRL_0_TOTAL_SLOTS_SHIFT                       _MK_SHIFT_CONST(16)
#define I2S_SLOT_CTRL_0_TOTAL_SLOTS_FIELD                       _MK_FIELD_CONST(0x7, I2S_SLOT_CTRL_0_TOTAL_SLOTS_SHIFT)
#define I2S_SLOT_CTRL_0_TOTAL_SLOTS_RANGE                       18:16
#define I2S_SLOT_CTRL_0_TOTAL_SLOTS_WOFFSET                     0x0
#define I2S_SLOT_CTRL_0_TOTAL_SLOTS_DEFAULT                     _MK_MASK_CONST(0x0)
#define I2S_SLOT_CTRL_0_TOTAL_SLOTS_DEFAULT_MASK                        _MK_MASK_CONST(0x7)
#define I2S_SLOT_CTRL_0_TOTAL_SLOTS_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define I2S_SLOT_CTRL_0_TOTAL_SLOTS_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)

#define I2S_SLOT_CTRL_0_RX_SLOT_ENABLES_SHIFT                   _MK_SHIFT_CONST(8)
#define I2S_SLOT_CTRL_0_RX_SLOT_ENABLES_FIELD                   _MK_FIELD_CONST(0xff, I2S_SLOT_CTRL_0_RX_SLOT_ENABLES_SHIFT)
#define I2S_SLOT_CTRL_0_RX_SLOT_ENABLES_RANGE                   15:8
#define I2S_SLOT_CTRL_0_RX_SLOT_ENABLES_WOFFSET                 0x0
#define I2S_SLOT_CTRL_0_RX_SLOT_ENABLES_DEFAULT                 _MK_MASK_CONST(0x0)
#define I2S_SLOT_CTRL_0_RX_SLOT_ENABLES_DEFAULT_MASK                    _MK_MASK_CONST(0xff)
#define I2S_SLOT_CTRL_0_RX_SLOT_ENABLES_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define I2S_SLOT_CTRL_0_RX_SLOT_ENABLES_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)

#define I2S_SLOT_CTRL_0_TX_SLOT_ENABLES_SHIFT                   _MK_SHIFT_CONST(0)
#define I2S_SLOT_CTRL_0_TX_SLOT_ENABLES_FIELD                   _MK_FIELD_CONST(0xff, I2S_SLOT_CTRL_0_TX_SLOT_ENABLES_SHIFT)
#define I2S_SLOT_CTRL_0_TX_SLOT_ENABLES_RANGE                   7:0
#define I2S_SLOT_CTRL_0_TX_SLOT_ENABLES_WOFFSET                 0x0
#define I2S_SLOT_CTRL_0_TX_SLOT_ENABLES_DEFAULT                 _MK_MASK_CONST(0x0)
#define I2S_SLOT_CTRL_0_TX_SLOT_ENABLES_DEFAULT_MASK                    _MK_MASK_CONST(0xff)
#define I2S_SLOT_CTRL_0_TX_SLOT_ENABLES_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define I2S_SLOT_CTRL_0_TX_SLOT_ENABLES_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)


// Register I2S_AUDIOCIF_I2STX_CTRL_0  
#define I2S_AUDIOCIF_I2STX_CTRL_0                       _MK_ADDR_CONST(0x14)
#define I2S_AUDIOCIF_I2STX_CTRL_0_SECURE                        0x0
#define I2S_AUDIOCIF_I2STX_CTRL_0_WORD_COUNT                    0x1
#define I2S_AUDIOCIF_I2STX_CTRL_0_RESET_VAL                     _MK_MASK_CONST(0x1104)
#define I2S_AUDIOCIF_I2STX_CTRL_0_RESET_MASK                    _MK_MASK_CONST(0xf70777ff)
#define I2S_AUDIOCIF_I2STX_CTRL_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_READ_MASK                     _MK_MASK_CONST(0xf70777ff)
#define I2S_AUDIOCIF_I2STX_CTRL_0_WRITE_MASK                    _MK_MASK_CONST(0xf70777fb)
#define I2S_AUDIOCIF_I2STX_CTRL_0_MONO_CONV_SHIFT                       _MK_SHIFT_CONST(0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_MONO_CONV_FIELD                       _MK_FIELD_CONST(0x1, I2S_AUDIOCIF_I2STX_CTRL_0_MONO_CONV_SHIFT)
#define I2S_AUDIOCIF_I2STX_CTRL_0_MONO_CONV_RANGE                       0:0
#define I2S_AUDIOCIF_I2STX_CTRL_0_MONO_CONV_WOFFSET                     0x0
#define I2S_AUDIOCIF_I2STX_CTRL_0_MONO_CONV_DEFAULT                     _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_MONO_CONV_DEFAULT_MASK                        _MK_MASK_CONST(0x1)
#define I2S_AUDIOCIF_I2STX_CTRL_0_MONO_CONV_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_MONO_CONV_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_MONO_CONV_ZERO                        _MK_ENUM_CONST(0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_MONO_CONV_COPY                        _MK_ENUM_CONST(1)

#define I2S_AUDIOCIF_I2STX_CTRL_0_TRUNCATE_SHIFT                        _MK_SHIFT_CONST(1)
#define I2S_AUDIOCIF_I2STX_CTRL_0_TRUNCATE_FIELD                        _MK_FIELD_CONST(0x1, I2S_AUDIOCIF_I2STX_CTRL_0_TRUNCATE_SHIFT)
#define I2S_AUDIOCIF_I2STX_CTRL_0_TRUNCATE_RANGE                        1:1
#define I2S_AUDIOCIF_I2STX_CTRL_0_TRUNCATE_WOFFSET                      0x0
#define I2S_AUDIOCIF_I2STX_CTRL_0_TRUNCATE_DEFAULT                      _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_TRUNCATE_DEFAULT_MASK                 _MK_MASK_CONST(0x1)
#define I2S_AUDIOCIF_I2STX_CTRL_0_TRUNCATE_SW_DEFAULT                   _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_TRUNCATE_SW_DEFAULT_MASK                      _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_TRUNCATE_ROUND                        _MK_ENUM_CONST(0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_TRUNCATE_CHOP                 _MK_ENUM_CONST(1)

#define I2S_AUDIOCIF_I2STX_CTRL_0_DIRECTION_SHIFT                       _MK_SHIFT_CONST(2)
#define I2S_AUDIOCIF_I2STX_CTRL_0_DIRECTION_FIELD                       _MK_FIELD_CONST(0x1, I2S_AUDIOCIF_I2STX_CTRL_0_DIRECTION_SHIFT)
#define I2S_AUDIOCIF_I2STX_CTRL_0_DIRECTION_RANGE                       2:2
#define I2S_AUDIOCIF_I2STX_CTRL_0_DIRECTION_WOFFSET                     0x0
#define I2S_AUDIOCIF_I2STX_CTRL_0_DIRECTION_DEFAULT                     _MK_MASK_CONST(0x1)
#define I2S_AUDIOCIF_I2STX_CTRL_0_DIRECTION_DEFAULT_MASK                        _MK_MASK_CONST(0x1)
#define I2S_AUDIOCIF_I2STX_CTRL_0_DIRECTION_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_DIRECTION_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_DIRECTION_INIT_ENUM                   RXCIF
#define I2S_AUDIOCIF_I2STX_CTRL_0_DIRECTION_TXCIF                       _MK_ENUM_CONST(0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_DIRECTION_RXCIF                       _MK_ENUM_CONST(1)

#define I2S_AUDIOCIF_I2STX_CTRL_0_REPLICATE_SHIFT                       _MK_SHIFT_CONST(3)
#define I2S_AUDIOCIF_I2STX_CTRL_0_REPLICATE_FIELD                       _MK_FIELD_CONST(0x1, I2S_AUDIOCIF_I2STX_CTRL_0_REPLICATE_SHIFT)
#define I2S_AUDIOCIF_I2STX_CTRL_0_REPLICATE_RANGE                       3:3
#define I2S_AUDIOCIF_I2STX_CTRL_0_REPLICATE_WOFFSET                     0x0
#define I2S_AUDIOCIF_I2STX_CTRL_0_REPLICATE_DEFAULT                     _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_REPLICATE_DEFAULT_MASK                        _MK_MASK_CONST(0x1)
#define I2S_AUDIOCIF_I2STX_CTRL_0_REPLICATE_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_REPLICATE_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_REPLICATE_DISABLE                     _MK_ENUM_CONST(0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_REPLICATE_ENABLE                      _MK_ENUM_CONST(1)

#define I2S_AUDIOCIF_I2STX_CTRL_0_STEREO_CONV_SHIFT                     _MK_SHIFT_CONST(4)
#define I2S_AUDIOCIF_I2STX_CTRL_0_STEREO_CONV_FIELD                     _MK_FIELD_CONST(0x3, I2S_AUDIOCIF_I2STX_CTRL_0_STEREO_CONV_SHIFT)
#define I2S_AUDIOCIF_I2STX_CTRL_0_STEREO_CONV_RANGE                     5:4
#define I2S_AUDIOCIF_I2STX_CTRL_0_STEREO_CONV_WOFFSET                   0x0
#define I2S_AUDIOCIF_I2STX_CTRL_0_STEREO_CONV_DEFAULT                   _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_STEREO_CONV_DEFAULT_MASK                      _MK_MASK_CONST(0x3)
#define I2S_AUDIOCIF_I2STX_CTRL_0_STEREO_CONV_SW_DEFAULT                        _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_STEREO_CONV_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_STEREO_CONV_CH0                       _MK_ENUM_CONST(0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_STEREO_CONV_CH1                       _MK_ENUM_CONST(1)
#define I2S_AUDIOCIF_I2STX_CTRL_0_STEREO_CONV_AVG                       _MK_ENUM_CONST(2)
#define I2S_AUDIOCIF_I2STX_CTRL_0_STEREO_CONV_RSVD                      _MK_ENUM_CONST(3)

#define I2S_AUDIOCIF_I2STX_CTRL_0_EXPAND_SHIFT                  _MK_SHIFT_CONST(6)
#define I2S_AUDIOCIF_I2STX_CTRL_0_EXPAND_FIELD                  _MK_FIELD_CONST(0x3, I2S_AUDIOCIF_I2STX_CTRL_0_EXPAND_SHIFT)
#define I2S_AUDIOCIF_I2STX_CTRL_0_EXPAND_RANGE                  7:6
#define I2S_AUDIOCIF_I2STX_CTRL_0_EXPAND_WOFFSET                        0x0
#define I2S_AUDIOCIF_I2STX_CTRL_0_EXPAND_DEFAULT                        _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_EXPAND_DEFAULT_MASK                   _MK_MASK_CONST(0x3)
#define I2S_AUDIOCIF_I2STX_CTRL_0_EXPAND_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_EXPAND_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_EXPAND_ZERO                   _MK_ENUM_CONST(0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_EXPAND_ONE                    _MK_ENUM_CONST(1)
#define I2S_AUDIOCIF_I2STX_CTRL_0_EXPAND_LFSR                   _MK_ENUM_CONST(2)
#define I2S_AUDIOCIF_I2STX_CTRL_0_EXPAND_RSVD                   _MK_ENUM_CONST(3)

#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_BITS_SHIFT                     _MK_SHIFT_CONST(8)
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_BITS_FIELD                     _MK_FIELD_CONST(0x7, I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_BITS_SHIFT)
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_BITS_RANGE                     10:8
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_BITS_WOFFSET                   0x0
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_BITS_DEFAULT                   _MK_MASK_CONST(0x1)
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_BITS_DEFAULT_MASK                      _MK_MASK_CONST(0x7)
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_BITS_SW_DEFAULT                        _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_BITS_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_BITS_BIT4                      _MK_ENUM_CONST(0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_BITS_BIT8                      _MK_ENUM_CONST(1)
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_BITS_BIT12                     _MK_ENUM_CONST(2)
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_BITS_BIT16                     _MK_ENUM_CONST(3)
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_BITS_BIT20                     _MK_ENUM_CONST(4)
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_BITS_BIT24                     _MK_ENUM_CONST(5)
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_BITS_BIT28                     _MK_ENUM_CONST(6)
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_BITS_BIT32                     _MK_ENUM_CONST(7)

#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_BITS_SHIFT                      _MK_SHIFT_CONST(12)
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_BITS_FIELD                      _MK_FIELD_CONST(0x7, I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_BITS_SHIFT)
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_BITS_RANGE                      14:12
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_BITS_WOFFSET                    0x0
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_BITS_DEFAULT                    _MK_MASK_CONST(0x1)
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_BITS_DEFAULT_MASK                       _MK_MASK_CONST(0x7)
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_BITS_SW_DEFAULT                 _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_BITS_SW_DEFAULT_MASK                    _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_BITS_BIT4                       _MK_ENUM_CONST(0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_BITS_BIT8                       _MK_ENUM_CONST(1)
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_BITS_BIT12                      _MK_ENUM_CONST(2)
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_BITS_BIT16                      _MK_ENUM_CONST(3)
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_BITS_BIT20                      _MK_ENUM_CONST(4)
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_BITS_BIT24                      _MK_ENUM_CONST(5)
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_BITS_BIT28                      _MK_ENUM_CONST(6)
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_BITS_BIT32                      _MK_ENUM_CONST(7)

#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_CHANNELS_SHIFT                 _MK_SHIFT_CONST(16)
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_CHANNELS_FIELD                 _MK_FIELD_CONST(0x7, I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_CHANNELS_SHIFT)
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_CHANNELS_RANGE                 18:16
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_CHANNELS_WOFFSET                       0x0
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_CHANNELS_DEFAULT                       _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_CHANNELS_DEFAULT_MASK                  _MK_MASK_CONST(0x7)
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_CHANNELS_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_CHANNELS_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_CHANNELS_CH1                   _MK_ENUM_CONST(0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_CHANNELS_CH2                   _MK_ENUM_CONST(1)
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_CHANNELS_CH3                   _MK_ENUM_CONST(2)
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_CHANNELS_CH4                   _MK_ENUM_CONST(3)
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_CHANNELS_CH5                   _MK_ENUM_CONST(4)
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_CHANNELS_CH6                   _MK_ENUM_CONST(5)
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_CHANNELS_CH7                   _MK_ENUM_CONST(6)
#define I2S_AUDIOCIF_I2STX_CTRL_0_CLIENT_CHANNELS_CH8                   _MK_ENUM_CONST(7)

#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_CHANNELS_SHIFT                  _MK_SHIFT_CONST(24)
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_CHANNELS_FIELD                  _MK_FIELD_CONST(0x7, I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_CHANNELS_SHIFT)
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_CHANNELS_RANGE                  26:24
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_CHANNELS_WOFFSET                        0x0
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_CHANNELS_DEFAULT                        _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_CHANNELS_DEFAULT_MASK                   _MK_MASK_CONST(0x7)
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_CHANNELS_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_CHANNELS_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_CHANNELS_CH1                    _MK_ENUM_CONST(0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_CHANNELS_CH2                    _MK_ENUM_CONST(1)
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_CHANNELS_CH3                    _MK_ENUM_CONST(2)
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_CHANNELS_CH4                    _MK_ENUM_CONST(3)
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_CHANNELS_CH5                    _MK_ENUM_CONST(4)
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_CHANNELS_CH6                    _MK_ENUM_CONST(5)
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_CHANNELS_CH7                    _MK_ENUM_CONST(6)
#define I2S_AUDIOCIF_I2STX_CTRL_0_AUDIO_CHANNELS_CH8                    _MK_ENUM_CONST(7)

#define I2S_AUDIOCIF_I2STX_CTRL_0_FIFO_THRESHOLD_SHIFT                  _MK_SHIFT_CONST(28)
#define I2S_AUDIOCIF_I2STX_CTRL_0_FIFO_THRESHOLD_FIELD                  _MK_FIELD_CONST(0xf, I2S_AUDIOCIF_I2STX_CTRL_0_FIFO_THRESHOLD_SHIFT)
#define I2S_AUDIOCIF_I2STX_CTRL_0_FIFO_THRESHOLD_RANGE                  31:28
#define I2S_AUDIOCIF_I2STX_CTRL_0_FIFO_THRESHOLD_WOFFSET                        0x0
#define I2S_AUDIOCIF_I2STX_CTRL_0_FIFO_THRESHOLD_DEFAULT                        _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_FIFO_THRESHOLD_DEFAULT_MASK                   _MK_MASK_CONST(0xf)
#define I2S_AUDIOCIF_I2STX_CTRL_0_FIFO_THRESHOLD_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2STX_CTRL_0_FIFO_THRESHOLD_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)


// Register I2S_AUDIOCIF_I2SRX_CTRL_0  
#define I2S_AUDIOCIF_I2SRX_CTRL_0                       _MK_ADDR_CONST(0x18)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_SECURE                        0x0
#define I2S_AUDIOCIF_I2SRX_CTRL_0_WORD_COUNT                    0x1
#define I2S_AUDIOCIF_I2SRX_CTRL_0_RESET_VAL                     _MK_MASK_CONST(0x1100)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_RESET_MASK                    _MK_MASK_CONST(0xf70777ff)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_READ_MASK                     _MK_MASK_CONST(0xf70777ff)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_WRITE_MASK                    _MK_MASK_CONST(0xf70777fb)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_MONO_CONV_SHIFT                       _MK_SHIFT_CONST(0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_MONO_CONV_FIELD                       _MK_FIELD_CONST(0x1, I2S_AUDIOCIF_I2SRX_CTRL_0_MONO_CONV_SHIFT)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_MONO_CONV_RANGE                       0:0
#define I2S_AUDIOCIF_I2SRX_CTRL_0_MONO_CONV_WOFFSET                     0x0
#define I2S_AUDIOCIF_I2SRX_CTRL_0_MONO_CONV_DEFAULT                     _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_MONO_CONV_DEFAULT_MASK                        _MK_MASK_CONST(0x1)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_MONO_CONV_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_MONO_CONV_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_MONO_CONV_ZERO                        _MK_ENUM_CONST(0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_MONO_CONV_COPY                        _MK_ENUM_CONST(1)

#define I2S_AUDIOCIF_I2SRX_CTRL_0_TRUNCATE_SHIFT                        _MK_SHIFT_CONST(1)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_TRUNCATE_FIELD                        _MK_FIELD_CONST(0x1, I2S_AUDIOCIF_I2SRX_CTRL_0_TRUNCATE_SHIFT)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_TRUNCATE_RANGE                        1:1
#define I2S_AUDIOCIF_I2SRX_CTRL_0_TRUNCATE_WOFFSET                      0x0
#define I2S_AUDIOCIF_I2SRX_CTRL_0_TRUNCATE_DEFAULT                      _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_TRUNCATE_DEFAULT_MASK                 _MK_MASK_CONST(0x1)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_TRUNCATE_SW_DEFAULT                   _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_TRUNCATE_SW_DEFAULT_MASK                      _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_TRUNCATE_ROUND                        _MK_ENUM_CONST(0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_TRUNCATE_CHOP                 _MK_ENUM_CONST(1)

#define I2S_AUDIOCIF_I2SRX_CTRL_0_DIRECTION_SHIFT                       _MK_SHIFT_CONST(2)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_DIRECTION_FIELD                       _MK_FIELD_CONST(0x1, I2S_AUDIOCIF_I2SRX_CTRL_0_DIRECTION_SHIFT)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_DIRECTION_RANGE                       2:2
#define I2S_AUDIOCIF_I2SRX_CTRL_0_DIRECTION_WOFFSET                     0x0
#define I2S_AUDIOCIF_I2SRX_CTRL_0_DIRECTION_DEFAULT                     _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_DIRECTION_DEFAULT_MASK                        _MK_MASK_CONST(0x1)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_DIRECTION_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_DIRECTION_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_DIRECTION_INIT_ENUM                   TXCIF
#define I2S_AUDIOCIF_I2SRX_CTRL_0_DIRECTION_TXCIF                       _MK_ENUM_CONST(0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_DIRECTION_RXCIF                       _MK_ENUM_CONST(1)

#define I2S_AUDIOCIF_I2SRX_CTRL_0_REPLICATE_SHIFT                       _MK_SHIFT_CONST(3)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_REPLICATE_FIELD                       _MK_FIELD_CONST(0x1, I2S_AUDIOCIF_I2SRX_CTRL_0_REPLICATE_SHIFT)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_REPLICATE_RANGE                       3:3
#define I2S_AUDIOCIF_I2SRX_CTRL_0_REPLICATE_WOFFSET                     0x0
#define I2S_AUDIOCIF_I2SRX_CTRL_0_REPLICATE_DEFAULT                     _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_REPLICATE_DEFAULT_MASK                        _MK_MASK_CONST(0x1)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_REPLICATE_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_REPLICATE_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_REPLICATE_DISABLE                     _MK_ENUM_CONST(0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_REPLICATE_ENABLE                      _MK_ENUM_CONST(1)

#define I2S_AUDIOCIF_I2SRX_CTRL_0_STEREO_CONV_SHIFT                     _MK_SHIFT_CONST(4)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_STEREO_CONV_FIELD                     _MK_FIELD_CONST(0x3, I2S_AUDIOCIF_I2SRX_CTRL_0_STEREO_CONV_SHIFT)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_STEREO_CONV_RANGE                     5:4
#define I2S_AUDIOCIF_I2SRX_CTRL_0_STEREO_CONV_WOFFSET                   0x0
#define I2S_AUDIOCIF_I2SRX_CTRL_0_STEREO_CONV_DEFAULT                   _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_STEREO_CONV_DEFAULT_MASK                      _MK_MASK_CONST(0x3)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_STEREO_CONV_SW_DEFAULT                        _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_STEREO_CONV_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_STEREO_CONV_CH0                       _MK_ENUM_CONST(0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_STEREO_CONV_CH1                       _MK_ENUM_CONST(1)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_STEREO_CONV_AVG                       _MK_ENUM_CONST(2)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_STEREO_CONV_RSVD                      _MK_ENUM_CONST(3)

#define I2S_AUDIOCIF_I2SRX_CTRL_0_EXPAND_SHIFT                  _MK_SHIFT_CONST(6)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_EXPAND_FIELD                  _MK_FIELD_CONST(0x3, I2S_AUDIOCIF_I2SRX_CTRL_0_EXPAND_SHIFT)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_EXPAND_RANGE                  7:6
#define I2S_AUDIOCIF_I2SRX_CTRL_0_EXPAND_WOFFSET                        0x0
#define I2S_AUDIOCIF_I2SRX_CTRL_0_EXPAND_DEFAULT                        _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_EXPAND_DEFAULT_MASK                   _MK_MASK_CONST(0x3)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_EXPAND_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_EXPAND_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_EXPAND_ZERO                   _MK_ENUM_CONST(0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_EXPAND_ONE                    _MK_ENUM_CONST(1)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_EXPAND_LFSR                   _MK_ENUM_CONST(2)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_EXPAND_RSVD                   _MK_ENUM_CONST(3)

#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_BITS_SHIFT                     _MK_SHIFT_CONST(8)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_BITS_FIELD                     _MK_FIELD_CONST(0x7, I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_BITS_SHIFT)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_BITS_RANGE                     10:8
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_BITS_WOFFSET                   0x0
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_BITS_DEFAULT                   _MK_MASK_CONST(0x1)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_BITS_DEFAULT_MASK                      _MK_MASK_CONST(0x7)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_BITS_SW_DEFAULT                        _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_BITS_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_BITS_BIT4                      _MK_ENUM_CONST(0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_BITS_BIT8                      _MK_ENUM_CONST(1)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_BITS_BIT12                     _MK_ENUM_CONST(2)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_BITS_BIT16                     _MK_ENUM_CONST(3)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_BITS_BIT20                     _MK_ENUM_CONST(4)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_BITS_BIT24                     _MK_ENUM_CONST(5)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_BITS_BIT28                     _MK_ENUM_CONST(6)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_BITS_BIT32                     _MK_ENUM_CONST(7)

#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_BITS_SHIFT                      _MK_SHIFT_CONST(12)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_BITS_FIELD                      _MK_FIELD_CONST(0x7, I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_BITS_SHIFT)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_BITS_RANGE                      14:12
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_BITS_WOFFSET                    0x0
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_BITS_DEFAULT                    _MK_MASK_CONST(0x1)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_BITS_DEFAULT_MASK                       _MK_MASK_CONST(0x7)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_BITS_SW_DEFAULT                 _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_BITS_SW_DEFAULT_MASK                    _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_BITS_BIT4                       _MK_ENUM_CONST(0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_BITS_BIT8                       _MK_ENUM_CONST(1)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_BITS_BIT12                      _MK_ENUM_CONST(2)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_BITS_BIT16                      _MK_ENUM_CONST(3)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_BITS_BIT20                      _MK_ENUM_CONST(4)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_BITS_BIT24                      _MK_ENUM_CONST(5)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_BITS_BIT28                      _MK_ENUM_CONST(6)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_BITS_BIT32                      _MK_ENUM_CONST(7)

#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_CHANNELS_SHIFT                 _MK_SHIFT_CONST(16)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_CHANNELS_FIELD                 _MK_FIELD_CONST(0x7, I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_CHANNELS_SHIFT)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_CHANNELS_RANGE                 18:16
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_CHANNELS_WOFFSET                       0x0
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_CHANNELS_DEFAULT                       _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_CHANNELS_DEFAULT_MASK                  _MK_MASK_CONST(0x7)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_CHANNELS_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_CHANNELS_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_CHANNELS_CH1                   _MK_ENUM_CONST(0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_CHANNELS_CH2                   _MK_ENUM_CONST(1)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_CHANNELS_CH3                   _MK_ENUM_CONST(2)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_CHANNELS_CH4                   _MK_ENUM_CONST(3)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_CHANNELS_CH5                   _MK_ENUM_CONST(4)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_CHANNELS_CH6                   _MK_ENUM_CONST(5)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_CHANNELS_CH7                   _MK_ENUM_CONST(6)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_CLIENT_CHANNELS_CH8                   _MK_ENUM_CONST(7)

#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_CHANNELS_SHIFT                  _MK_SHIFT_CONST(24)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_CHANNELS_FIELD                  _MK_FIELD_CONST(0x7, I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_CHANNELS_SHIFT)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_CHANNELS_RANGE                  26:24
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_CHANNELS_WOFFSET                        0x0
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_CHANNELS_DEFAULT                        _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_CHANNELS_DEFAULT_MASK                   _MK_MASK_CONST(0x7)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_CHANNELS_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_CHANNELS_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_CHANNELS_CH1                    _MK_ENUM_CONST(0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_CHANNELS_CH2                    _MK_ENUM_CONST(1)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_CHANNELS_CH3                    _MK_ENUM_CONST(2)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_CHANNELS_CH4                    _MK_ENUM_CONST(3)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_CHANNELS_CH5                    _MK_ENUM_CONST(4)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_CHANNELS_CH6                    _MK_ENUM_CONST(5)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_CHANNELS_CH7                    _MK_ENUM_CONST(6)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_AUDIO_CHANNELS_CH8                    _MK_ENUM_CONST(7)

#define I2S_AUDIOCIF_I2SRX_CTRL_0_FIFO_THRESHOLD_SHIFT                  _MK_SHIFT_CONST(28)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_FIFO_THRESHOLD_FIELD                  _MK_FIELD_CONST(0xf, I2S_AUDIOCIF_I2SRX_CTRL_0_FIFO_THRESHOLD_SHIFT)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_FIFO_THRESHOLD_RANGE                  31:28
#define I2S_AUDIOCIF_I2SRX_CTRL_0_FIFO_THRESHOLD_WOFFSET                        0x0
#define I2S_AUDIOCIF_I2SRX_CTRL_0_FIFO_THRESHOLD_DEFAULT                        _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_FIFO_THRESHOLD_DEFAULT_MASK                   _MK_MASK_CONST(0xf)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_FIFO_THRESHOLD_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define I2S_AUDIOCIF_I2SRX_CTRL_0_FIFO_THRESHOLD_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)


// Register I2S_FLOWCTL_0  
#define I2S_FLOWCTL_0                   _MK_ADDR_CONST(0x1c)
#define I2S_FLOWCTL_0_SECURE                    0x0
#define I2S_FLOWCTL_0_WORD_COUNT                        0x1
#define I2S_FLOWCTL_0_RESET_VAL                         _MK_MASK_CONST(0x80000000)
#define I2S_FLOWCTL_0_RESET_MASK                        _MK_MASK_CONST(0x80000000)
#define I2S_FLOWCTL_0_SW_DEFAULT_VAL                    _MK_MASK_CONST(0x0)
#define I2S_FLOWCTL_0_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define I2S_FLOWCTL_0_READ_MASK                         _MK_MASK_CONST(0x0)
#define I2S_FLOWCTL_0_WRITE_MASK                        _MK_MASK_CONST(0x0)
#define I2S_FLOWCTL_0_FILTER_SHIFT                      _MK_SHIFT_CONST(31)
#define I2S_FLOWCTL_0_FILTER_FIELD                      _MK_FIELD_CONST(0x1, I2S_FLOWCTL_0_FILTER_SHIFT)
#define I2S_FLOWCTL_0_FILTER_RANGE                      31:31
#define I2S_FLOWCTL_0_FILTER_WOFFSET                    0x0
#define I2S_FLOWCTL_0_FILTER_DEFAULT                    _MK_MASK_CONST(0x1)
#define I2S_FLOWCTL_0_FILTER_DEFAULT_MASK                       _MK_MASK_CONST(0x1)
#define I2S_FLOWCTL_0_FILTER_SW_DEFAULT                 _MK_MASK_CONST(0x0)
#define I2S_FLOWCTL_0_FILTER_SW_DEFAULT_MASK                    _MK_MASK_CONST(0x0)
#define I2S_FLOWCTL_0_FILTER_INIT_ENUM                  QUAD
#define I2S_FLOWCTL_0_FILTER_LINEAR                     _MK_ENUM_CONST(0)
#define I2S_FLOWCTL_0_FILTER_QUAD                       _MK_ENUM_CONST(1)


// Register I2S_TX_STEP_0  
#define I2S_TX_STEP_0                   _MK_ADDR_CONST(0x20)
#define I2S_TX_STEP_0_SECURE                    0x0
#define I2S_TX_STEP_0_WORD_COUNT                        0x1
#define I2S_TX_STEP_0_RESET_VAL                         _MK_MASK_CONST(0x8000)
#define I2S_TX_STEP_0_RESET_MASK                        _MK_MASK_CONST(0xffff)
#define I2S_TX_STEP_0_SW_DEFAULT_VAL                    _MK_MASK_CONST(0x0)
#define I2S_TX_STEP_0_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define I2S_TX_STEP_0_READ_MASK                         _MK_MASK_CONST(0xffff)
#define I2S_TX_STEP_0_WRITE_MASK                        _MK_MASK_CONST(0xffff)
#define I2S_TX_STEP_0_STEP_SIZE_SHIFT                   _MK_SHIFT_CONST(0)
#define I2S_TX_STEP_0_STEP_SIZE_FIELD                   _MK_FIELD_CONST(0xffff, I2S_TX_STEP_0_STEP_SIZE_SHIFT)
#define I2S_TX_STEP_0_STEP_SIZE_RANGE                   15:0
#define I2S_TX_STEP_0_STEP_SIZE_WOFFSET                 0x0
#define I2S_TX_STEP_0_STEP_SIZE_DEFAULT                 _MK_MASK_CONST(0x8000)
#define I2S_TX_STEP_0_STEP_SIZE_DEFAULT_MASK                    _MK_MASK_CONST(0xffff)
#define I2S_TX_STEP_0_STEP_SIZE_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define I2S_TX_STEP_0_STEP_SIZE_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)


// Register I2S_FLOW_STATUS_0  
#define I2S_FLOW_STATUS_0                       _MK_ADDR_CONST(0x24)
#define I2S_FLOW_STATUS_0_SECURE                        0x0
#define I2S_FLOW_STATUS_0_WORD_COUNT                    0x1
#define I2S_FLOW_STATUS_0_RESET_VAL                     _MK_MASK_CONST(0x0)
#define I2S_FLOW_STATUS_0_RESET_MASK                    _MK_MASK_CONST(0xc0000013)
#define I2S_FLOW_STATUS_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define I2S_FLOW_STATUS_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define I2S_FLOW_STATUS_0_READ_MASK                     _MK_MASK_CONST(0xc000001f)
#define I2S_FLOW_STATUS_0_WRITE_MASK                    _MK_MASK_CONST(0xc000001f)
#define I2S_FLOW_STATUS_0_MONITOR_EN_SHIFT                      _MK_SHIFT_CONST(0)
#define I2S_FLOW_STATUS_0_MONITOR_EN_FIELD                      _MK_FIELD_CONST(0x1, I2S_FLOW_STATUS_0_MONITOR_EN_SHIFT)
#define I2S_FLOW_STATUS_0_MONITOR_EN_RANGE                      0:0
#define I2S_FLOW_STATUS_0_MONITOR_EN_WOFFSET                    0x0
#define I2S_FLOW_STATUS_0_MONITOR_EN_DEFAULT                    _MK_MASK_CONST(0x0)
#define I2S_FLOW_STATUS_0_MONITOR_EN_DEFAULT_MASK                       _MK_MASK_CONST(0x1)
#define I2S_FLOW_STATUS_0_MONITOR_EN_SW_DEFAULT                 _MK_MASK_CONST(0x0)
#define I2S_FLOW_STATUS_0_MONITOR_EN_SW_DEFAULT_MASK                    _MK_MASK_CONST(0x0)
#define I2S_FLOW_STATUS_0_MONITOR_EN_INIT_ENUM                  DISABLE
#define I2S_FLOW_STATUS_0_MONITOR_EN_DISABLE                    _MK_ENUM_CONST(0)
#define I2S_FLOW_STATUS_0_MONITOR_EN_ENABLE                     _MK_ENUM_CONST(1)

#define I2S_FLOW_STATUS_0_COUNTER_EN_SHIFT                      _MK_SHIFT_CONST(1)
#define I2S_FLOW_STATUS_0_COUNTER_EN_FIELD                      _MK_FIELD_CONST(0x1, I2S_FLOW_STATUS_0_COUNTER_EN_SHIFT)
#define I2S_FLOW_STATUS_0_COUNTER_EN_RANGE                      1:1
#define I2S_FLOW_STATUS_0_COUNTER_EN_WOFFSET                    0x0
#define I2S_FLOW_STATUS_0_COUNTER_EN_DEFAULT                    _MK_MASK_CONST(0x0)
#define I2S_FLOW_STATUS_0_COUNTER_EN_DEFAULT_MASK                       _MK_MASK_CONST(0x1)
#define I2S_FLOW_STATUS_0_COUNTER_EN_SW_DEFAULT                 _MK_MASK_CONST(0x0)
#define I2S_FLOW_STATUS_0_COUNTER_EN_SW_DEFAULT_MASK                    _MK_MASK_CONST(0x0)
#define I2S_FLOW_STATUS_0_COUNTER_EN_INIT_ENUM                  DISABLE
#define I2S_FLOW_STATUS_0_COUNTER_EN_DISABLE                    _MK_ENUM_CONST(0)
#define I2S_FLOW_STATUS_0_COUNTER_EN_ENABLE                     _MK_ENUM_CONST(1)

#define I2S_FLOW_STATUS_0_MONITOR_CLR_SHIFT                     _MK_SHIFT_CONST(2)
#define I2S_FLOW_STATUS_0_MONITOR_CLR_FIELD                     _MK_FIELD_CONST(0x1, I2S_FLOW_STATUS_0_MONITOR_CLR_SHIFT)
#define I2S_FLOW_STATUS_0_MONITOR_CLR_RANGE                     2:2
#define I2S_FLOW_STATUS_0_MONITOR_CLR_WOFFSET                   0x0
#define I2S_FLOW_STATUS_0_MONITOR_CLR_DEFAULT                   _MK_MASK_CONST(0x0)
#define I2S_FLOW_STATUS_0_MONITOR_CLR_DEFAULT_MASK                      _MK_MASK_CONST(0x0)
#define I2S_FLOW_STATUS_0_MONITOR_CLR_SW_DEFAULT                        _MK_MASK_CONST(0x0)
#define I2S_FLOW_STATUS_0_MONITOR_CLR_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)

#define I2S_FLOW_STATUS_0_COUNTER_CLR_SHIFT                     _MK_SHIFT_CONST(3)
#define I2S_FLOW_STATUS_0_COUNTER_CLR_FIELD                     _MK_FIELD_CONST(0x1, I2S_FLOW_STATUS_0_COUNTER_CLR_SHIFT)
#define I2S_FLOW_STATUS_0_COUNTER_CLR_RANGE                     3:3
#define I2S_FLOW_STATUS_0_COUNTER_CLR_WOFFSET                   0x0
#define I2S_FLOW_STATUS_0_COUNTER_CLR_DEFAULT                   _MK_MASK_CONST(0x0)
#define I2S_FLOW_STATUS_0_COUNTER_CLR_DEFAULT_MASK                      _MK_MASK_CONST(0x0)
#define I2S_FLOW_STATUS_0_COUNTER_CLR_SW_DEFAULT                        _MK_MASK_CONST(0x0)
#define I2S_FLOW_STATUS_0_COUNTER_CLR_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)

#define I2S_FLOW_STATUS_0_MONITOR_INT_EN_SHIFT                  _MK_SHIFT_CONST(4)
#define I2S_FLOW_STATUS_0_MONITOR_INT_EN_FIELD                  _MK_FIELD_CONST(0x1, I2S_FLOW_STATUS_0_MONITOR_INT_EN_SHIFT)
#define I2S_FLOW_STATUS_0_MONITOR_INT_EN_RANGE                  4:4
#define I2S_FLOW_STATUS_0_MONITOR_INT_EN_WOFFSET                        0x0
#define I2S_FLOW_STATUS_0_MONITOR_INT_EN_DEFAULT                        _MK_MASK_CONST(0x0)
#define I2S_FLOW_STATUS_0_MONITOR_INT_EN_DEFAULT_MASK                   _MK_MASK_CONST(0x1)
#define I2S_FLOW_STATUS_0_MONITOR_INT_EN_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define I2S_FLOW_STATUS_0_MONITOR_INT_EN_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define I2S_FLOW_STATUS_0_MONITOR_INT_EN_INIT_ENUM                      DISABLE
#define I2S_FLOW_STATUS_0_MONITOR_INT_EN_DISABLE                        _MK_ENUM_CONST(0)
#define I2S_FLOW_STATUS_0_MONITOR_INT_EN_ENABLE                 _MK_ENUM_CONST(1)

#define I2S_FLOW_STATUS_0_FLOW_OVERFLOW_SHIFT                   _MK_SHIFT_CONST(30)
#define I2S_FLOW_STATUS_0_FLOW_OVERFLOW_FIELD                   _MK_FIELD_CONST(0x1, I2S_FLOW_STATUS_0_FLOW_OVERFLOW_SHIFT)
#define I2S_FLOW_STATUS_0_FLOW_OVERFLOW_RANGE                   30:30
#define I2S_FLOW_STATUS_0_FLOW_OVERFLOW_WOFFSET                 0x0
#define I2S_FLOW_STATUS_0_FLOW_OVERFLOW_DEFAULT                 _MK_MASK_CONST(0x0)
#define I2S_FLOW_STATUS_0_FLOW_OVERFLOW_DEFAULT_MASK                    _MK_MASK_CONST(0x1)
#define I2S_FLOW_STATUS_0_FLOW_OVERFLOW_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define I2S_FLOW_STATUS_0_FLOW_OVERFLOW_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)
#define I2S_FLOW_STATUS_0_FLOW_OVERFLOW_INIT_ENUM                       NORMAL
#define I2S_FLOW_STATUS_0_FLOW_OVERFLOW_NORMAL                  _MK_ENUM_CONST(0)
#define I2S_FLOW_STATUS_0_FLOW_OVERFLOW_OVER                    _MK_ENUM_CONST(1)

#define I2S_FLOW_STATUS_0_FLOW_UNDERFLOW_SHIFT                  _MK_SHIFT_CONST(31)
#define I2S_FLOW_STATUS_0_FLOW_UNDERFLOW_FIELD                  _MK_FIELD_CONST(0x1, I2S_FLOW_STATUS_0_FLOW_UNDERFLOW_SHIFT)
#define I2S_FLOW_STATUS_0_FLOW_UNDERFLOW_RANGE                  31:31
#define I2S_FLOW_STATUS_0_FLOW_UNDERFLOW_WOFFSET                        0x0
#define I2S_FLOW_STATUS_0_FLOW_UNDERFLOW_DEFAULT                        _MK_MASK_CONST(0x0)
#define I2S_FLOW_STATUS_0_FLOW_UNDERFLOW_DEFAULT_MASK                   _MK_MASK_CONST(0x1)
#define I2S_FLOW_STATUS_0_FLOW_UNDERFLOW_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define I2S_FLOW_STATUS_0_FLOW_UNDERFLOW_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define I2S_FLOW_STATUS_0_FLOW_UNDERFLOW_INIT_ENUM                      NORMAL
#define I2S_FLOW_STATUS_0_FLOW_UNDERFLOW_NORMAL                 _MK_ENUM_CONST(0)
#define I2S_FLOW_STATUS_0_FLOW_UNDERFLOW_UNDER                  _MK_ENUM_CONST(1)


// Register I2S_FLOW_TOTAL_0  
#define I2S_FLOW_TOTAL_0                        _MK_ADDR_CONST(0x28)
#define I2S_FLOW_TOTAL_0_SECURE                         0x0
#define I2S_FLOW_TOTAL_0_WORD_COUNT                     0x1
#define I2S_FLOW_TOTAL_0_RESET_VAL                      _MK_MASK_CONST(0x0)
#define I2S_FLOW_TOTAL_0_RESET_MASK                     _MK_MASK_CONST(0xffffffff)
#define I2S_FLOW_TOTAL_0_SW_DEFAULT_VAL                         _MK_MASK_CONST(0x0)
#define I2S_FLOW_TOTAL_0_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define I2S_FLOW_TOTAL_0_READ_MASK                      _MK_MASK_CONST(0xffffffff)
#define I2S_FLOW_TOTAL_0_WRITE_MASK                     _MK_MASK_CONST(0x0)
#define I2S_FLOW_TOTAL_0_COUNTER_SHIFT                  _MK_SHIFT_CONST(0)
#define I2S_FLOW_TOTAL_0_COUNTER_FIELD                  _MK_FIELD_CONST(0xffffffff, I2S_FLOW_TOTAL_0_COUNTER_SHIFT)
#define I2S_FLOW_TOTAL_0_COUNTER_RANGE                  31:0
#define I2S_FLOW_TOTAL_0_COUNTER_WOFFSET                        0x0
#define I2S_FLOW_TOTAL_0_COUNTER_DEFAULT                        _MK_MASK_CONST(0x0)
#define I2S_FLOW_TOTAL_0_COUNTER_DEFAULT_MASK                   _MK_MASK_CONST(0xffffffff)
#define I2S_FLOW_TOTAL_0_COUNTER_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define I2S_FLOW_TOTAL_0_COUNTER_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)


// Register I2S_FLOW_OVER_0  
#define I2S_FLOW_OVER_0                 _MK_ADDR_CONST(0x2c)
#define I2S_FLOW_OVER_0_SECURE                  0x0
#define I2S_FLOW_OVER_0_WORD_COUNT                      0x1
#define I2S_FLOW_OVER_0_RESET_VAL                       _MK_MASK_CONST(0x0)
#define I2S_FLOW_OVER_0_RESET_MASK                      _MK_MASK_CONST(0xffffffff)
#define I2S_FLOW_OVER_0_SW_DEFAULT_VAL                  _MK_MASK_CONST(0x0)
#define I2S_FLOW_OVER_0_SW_DEFAULT_MASK                         _MK_MASK_CONST(0x0)
#define I2S_FLOW_OVER_0_READ_MASK                       _MK_MASK_CONST(0xffffffff)
#define I2S_FLOW_OVER_0_WRITE_MASK                      _MK_MASK_CONST(0x0)
#define I2S_FLOW_OVER_0_COUNTER_SHIFT                   _MK_SHIFT_CONST(0)
#define I2S_FLOW_OVER_0_COUNTER_FIELD                   _MK_FIELD_CONST(0xffffffff, I2S_FLOW_OVER_0_COUNTER_SHIFT)
#define I2S_FLOW_OVER_0_COUNTER_RANGE                   31:0
#define I2S_FLOW_OVER_0_COUNTER_WOFFSET                 0x0
#define I2S_FLOW_OVER_0_COUNTER_DEFAULT                 _MK_MASK_CONST(0x0)
#define I2S_FLOW_OVER_0_COUNTER_DEFAULT_MASK                    _MK_MASK_CONST(0xffffffff)
#define I2S_FLOW_OVER_0_COUNTER_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define I2S_FLOW_OVER_0_COUNTER_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)


// Register I2S_FLOW_UNDER_0  
#define I2S_FLOW_UNDER_0                        _MK_ADDR_CONST(0x30)
#define I2S_FLOW_UNDER_0_SECURE                         0x0
#define I2S_FLOW_UNDER_0_WORD_COUNT                     0x1
#define I2S_FLOW_UNDER_0_RESET_VAL                      _MK_MASK_CONST(0x0)
#define I2S_FLOW_UNDER_0_RESET_MASK                     _MK_MASK_CONST(0xffffffff)
#define I2S_FLOW_UNDER_0_SW_DEFAULT_VAL                         _MK_MASK_CONST(0x0)
#define I2S_FLOW_UNDER_0_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define I2S_FLOW_UNDER_0_READ_MASK                      _MK_MASK_CONST(0xffffffff)
#define I2S_FLOW_UNDER_0_WRITE_MASK                     _MK_MASK_CONST(0x0)
#define I2S_FLOW_UNDER_0_COUNTER_SHIFT                  _MK_SHIFT_CONST(0)
#define I2S_FLOW_UNDER_0_COUNTER_FIELD                  _MK_FIELD_CONST(0xffffffff, I2S_FLOW_UNDER_0_COUNTER_SHIFT)
#define I2S_FLOW_UNDER_0_COUNTER_RANGE                  31:0
#define I2S_FLOW_UNDER_0_COUNTER_WOFFSET                        0x0
#define I2S_FLOW_UNDER_0_COUNTER_DEFAULT                        _MK_MASK_CONST(0x0)
#define I2S_FLOW_UNDER_0_COUNTER_DEFAULT_MASK                   _MK_MASK_CONST(0xffffffff)
#define I2S_FLOW_UNDER_0_COUNTER_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define I2S_FLOW_UNDER_0_COUNTER_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)


// Register I2S_LCOEF_1_4_0_0  
#define I2S_LCOEF_1_4_0_0                       _MK_ADDR_CONST(0x34)
#define I2S_LCOEF_1_4_0_0_SECURE                        0x0
#define I2S_LCOEF_1_4_0_0_WORD_COUNT                    0x1
#define I2S_LCOEF_1_4_0_0_RESET_VAL                     _MK_MASK_CONST(0x2e)
#define I2S_LCOEF_1_4_0_0_RESET_MASK                    _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_1_4_0_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define I2S_LCOEF_1_4_0_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define I2S_LCOEF_1_4_0_0_READ_MASK                     _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_1_4_0_0_WRITE_MASK                    _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_1_4_0_0_COEF_SHIFT                    _MK_SHIFT_CONST(0)
#define I2S_LCOEF_1_4_0_0_COEF_FIELD                    _MK_FIELD_CONST(0xffff, I2S_LCOEF_1_4_0_0_COEF_SHIFT)
#define I2S_LCOEF_1_4_0_0_COEF_RANGE                    15:0
#define I2S_LCOEF_1_4_0_0_COEF_WOFFSET                  0x0
#define I2S_LCOEF_1_4_0_0_COEF_DEFAULT                  _MK_MASK_CONST(0x2e)
#define I2S_LCOEF_1_4_0_0_COEF_DEFAULT_MASK                     _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_1_4_0_0_COEF_SW_DEFAULT                       _MK_MASK_CONST(0x0)
#define I2S_LCOEF_1_4_0_0_COEF_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)


// Register I2S_LCOEF_1_4_1_0  
#define I2S_LCOEF_1_4_1_0                       _MK_ADDR_CONST(0x38)
#define I2S_LCOEF_1_4_1_0_SECURE                        0x0
#define I2S_LCOEF_1_4_1_0_WORD_COUNT                    0x1
#define I2S_LCOEF_1_4_1_0_RESET_VAL                     _MK_MASK_CONST(0xf9e6)
#define I2S_LCOEF_1_4_1_0_RESET_MASK                    _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_1_4_1_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define I2S_LCOEF_1_4_1_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define I2S_LCOEF_1_4_1_0_READ_MASK                     _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_1_4_1_0_WRITE_MASK                    _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_1_4_1_0_COEF_SHIFT                    _MK_SHIFT_CONST(0)
#define I2S_LCOEF_1_4_1_0_COEF_FIELD                    _MK_FIELD_CONST(0xffff, I2S_LCOEF_1_4_1_0_COEF_SHIFT)
#define I2S_LCOEF_1_4_1_0_COEF_RANGE                    15:0
#define I2S_LCOEF_1_4_1_0_COEF_WOFFSET                  0x0
#define I2S_LCOEF_1_4_1_0_COEF_DEFAULT                  _MK_MASK_CONST(0xf9e6)
#define I2S_LCOEF_1_4_1_0_COEF_DEFAULT_MASK                     _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_1_4_1_0_COEF_SW_DEFAULT                       _MK_MASK_CONST(0x0)
#define I2S_LCOEF_1_4_1_0_COEF_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)


// Register I2S_LCOEF_1_4_2_0  
#define I2S_LCOEF_1_4_2_0                       _MK_ADDR_CONST(0x3c)
#define I2S_LCOEF_1_4_2_0_SECURE                        0x0
#define I2S_LCOEF_1_4_2_0_WORD_COUNT                    0x1
#define I2S_LCOEF_1_4_2_0_RESET_VAL                     _MK_MASK_CONST(0x20ca)
#define I2S_LCOEF_1_4_2_0_RESET_MASK                    _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_1_4_2_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define I2S_LCOEF_1_4_2_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define I2S_LCOEF_1_4_2_0_READ_MASK                     _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_1_4_2_0_WRITE_MASK                    _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_1_4_2_0_COEF_SHIFT                    _MK_SHIFT_CONST(0)
#define I2S_LCOEF_1_4_2_0_COEF_FIELD                    _MK_FIELD_CONST(0xffff, I2S_LCOEF_1_4_2_0_COEF_SHIFT)
#define I2S_LCOEF_1_4_2_0_COEF_RANGE                    15:0
#define I2S_LCOEF_1_4_2_0_COEF_WOFFSET                  0x0
#define I2S_LCOEF_1_4_2_0_COEF_DEFAULT                  _MK_MASK_CONST(0x20ca)
#define I2S_LCOEF_1_4_2_0_COEF_DEFAULT_MASK                     _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_1_4_2_0_COEF_SW_DEFAULT                       _MK_MASK_CONST(0x0)
#define I2S_LCOEF_1_4_2_0_COEF_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)


// Register I2S_LCOEF_1_4_3_0  
#define I2S_LCOEF_1_4_3_0                       _MK_ADDR_CONST(0x40)
#define I2S_LCOEF_1_4_3_0_SECURE                        0x0
#define I2S_LCOEF_1_4_3_0_WORD_COUNT                    0x1
#define I2S_LCOEF_1_4_3_0_RESET_VAL                     _MK_MASK_CONST(0x7147)
#define I2S_LCOEF_1_4_3_0_RESET_MASK                    _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_1_4_3_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define I2S_LCOEF_1_4_3_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define I2S_LCOEF_1_4_3_0_READ_MASK                     _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_1_4_3_0_WRITE_MASK                    _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_1_4_3_0_COEF_SHIFT                    _MK_SHIFT_CONST(0)
#define I2S_LCOEF_1_4_3_0_COEF_FIELD                    _MK_FIELD_CONST(0xffff, I2S_LCOEF_1_4_3_0_COEF_SHIFT)
#define I2S_LCOEF_1_4_3_0_COEF_RANGE                    15:0
#define I2S_LCOEF_1_4_3_0_COEF_WOFFSET                  0x0
#define I2S_LCOEF_1_4_3_0_COEF_DEFAULT                  _MK_MASK_CONST(0x7147)
#define I2S_LCOEF_1_4_3_0_COEF_DEFAULT_MASK                     _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_1_4_3_0_COEF_SW_DEFAULT                       _MK_MASK_CONST(0x0)
#define I2S_LCOEF_1_4_3_0_COEF_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)


// Register I2S_LCOEF_1_4_4_0  
#define I2S_LCOEF_1_4_4_0                       _MK_ADDR_CONST(0x44)
#define I2S_LCOEF_1_4_4_0_SECURE                        0x0
#define I2S_LCOEF_1_4_4_0_WORD_COUNT                    0x1
#define I2S_LCOEF_1_4_4_0_RESET_VAL                     _MK_MASK_CONST(0xf17e)
#define I2S_LCOEF_1_4_4_0_RESET_MASK                    _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_1_4_4_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define I2S_LCOEF_1_4_4_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define I2S_LCOEF_1_4_4_0_READ_MASK                     _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_1_4_4_0_WRITE_MASK                    _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_1_4_4_0_COEF_SHIFT                    _MK_SHIFT_CONST(0)
#define I2S_LCOEF_1_4_4_0_COEF_FIELD                    _MK_FIELD_CONST(0xffff, I2S_LCOEF_1_4_4_0_COEF_SHIFT)
#define I2S_LCOEF_1_4_4_0_COEF_RANGE                    15:0
#define I2S_LCOEF_1_4_4_0_COEF_WOFFSET                  0x0
#define I2S_LCOEF_1_4_4_0_COEF_DEFAULT                  _MK_MASK_CONST(0xf17e)
#define I2S_LCOEF_1_4_4_0_COEF_DEFAULT_MASK                     _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_1_4_4_0_COEF_SW_DEFAULT                       _MK_MASK_CONST(0x0)
#define I2S_LCOEF_1_4_4_0_COEF_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)


// Register I2S_LCOEF_1_4_5_0  
#define I2S_LCOEF_1_4_5_0                       _MK_ADDR_CONST(0x48)
#define I2S_LCOEF_1_4_5_0_SECURE                        0x0
#define I2S_LCOEF_1_4_5_0_WORD_COUNT                    0x1
#define I2S_LCOEF_1_4_5_0_RESET_VAL                     _MK_MASK_CONST(0x1e0)
#define I2S_LCOEF_1_4_5_0_RESET_MASK                    _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_1_4_5_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define I2S_LCOEF_1_4_5_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define I2S_LCOEF_1_4_5_0_READ_MASK                     _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_1_4_5_0_WRITE_MASK                    _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_1_4_5_0_COEF_SHIFT                    _MK_SHIFT_CONST(0)
#define I2S_LCOEF_1_4_5_0_COEF_FIELD                    _MK_FIELD_CONST(0xffff, I2S_LCOEF_1_4_5_0_COEF_SHIFT)
#define I2S_LCOEF_1_4_5_0_COEF_RANGE                    15:0
#define I2S_LCOEF_1_4_5_0_COEF_WOFFSET                  0x0
#define I2S_LCOEF_1_4_5_0_COEF_DEFAULT                  _MK_MASK_CONST(0x1e0)
#define I2S_LCOEF_1_4_5_0_COEF_DEFAULT_MASK                     _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_1_4_5_0_COEF_SW_DEFAULT                       _MK_MASK_CONST(0x0)
#define I2S_LCOEF_1_4_5_0_COEF_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)


// Register I2S_LCOEF_2_4_0_0  
#define I2S_LCOEF_2_4_0_0                       _MK_ADDR_CONST(0x4c)
#define I2S_LCOEF_2_4_0_0_SECURE                        0x0
#define I2S_LCOEF_2_4_0_0_WORD_COUNT                    0x1
#define I2S_LCOEF_2_4_0_0_RESET_VAL                     _MK_MASK_CONST(0x117)
#define I2S_LCOEF_2_4_0_0_RESET_MASK                    _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_2_4_0_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define I2S_LCOEF_2_4_0_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define I2S_LCOEF_2_4_0_0_READ_MASK                     _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_2_4_0_0_WRITE_MASK                    _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_2_4_0_0_COEF_SHIFT                    _MK_SHIFT_CONST(0)
#define I2S_LCOEF_2_4_0_0_COEF_FIELD                    _MK_FIELD_CONST(0xffff, I2S_LCOEF_2_4_0_0_COEF_SHIFT)
#define I2S_LCOEF_2_4_0_0_COEF_RANGE                    15:0
#define I2S_LCOEF_2_4_0_0_COEF_WOFFSET                  0x0
#define I2S_LCOEF_2_4_0_0_COEF_DEFAULT                  _MK_MASK_CONST(0x117)
#define I2S_LCOEF_2_4_0_0_COEF_DEFAULT_MASK                     _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_2_4_0_0_COEF_SW_DEFAULT                       _MK_MASK_CONST(0x0)
#define I2S_LCOEF_2_4_0_0_COEF_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)


// Register I2S_LCOEF_2_4_1_0  
#define I2S_LCOEF_2_4_1_0                       _MK_ADDR_CONST(0x50)
#define I2S_LCOEF_2_4_1_0_SECURE                        0x0
#define I2S_LCOEF_2_4_1_0_WORD_COUNT                    0x1
#define I2S_LCOEF_2_4_1_0_RESET_VAL                     _MK_MASK_CONST(0xf26b)
#define I2S_LCOEF_2_4_1_0_RESET_MASK                    _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_2_4_1_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define I2S_LCOEF_2_4_1_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define I2S_LCOEF_2_4_1_0_READ_MASK                     _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_2_4_1_0_WRITE_MASK                    _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_2_4_1_0_COEF_SHIFT                    _MK_SHIFT_CONST(0)
#define I2S_LCOEF_2_4_1_0_COEF_FIELD                    _MK_FIELD_CONST(0xffff, I2S_LCOEF_2_4_1_0_COEF_SHIFT)
#define I2S_LCOEF_2_4_1_0_COEF_RANGE                    15:0
#define I2S_LCOEF_2_4_1_0_COEF_WOFFSET                  0x0
#define I2S_LCOEF_2_4_1_0_COEF_DEFAULT                  _MK_MASK_CONST(0xf26b)
#define I2S_LCOEF_2_4_1_0_COEF_DEFAULT_MASK                     _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_2_4_1_0_COEF_SW_DEFAULT                       _MK_MASK_CONST(0x0)
#define I2S_LCOEF_2_4_1_0_COEF_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)


// Register I2S_LCOEF_2_4_2_0  
#define I2S_LCOEF_2_4_2_0                       _MK_ADDR_CONST(0x54)
#define I2S_LCOEF_2_4_2_0_SECURE                        0x0
#define I2S_LCOEF_2_4_2_0_WORD_COUNT                    0x1
#define I2S_LCOEF_2_4_2_0_RESET_VAL                     _MK_MASK_CONST(0x4c07)
#define I2S_LCOEF_2_4_2_0_RESET_MASK                    _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_2_4_2_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define I2S_LCOEF_2_4_2_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define I2S_LCOEF_2_4_2_0_READ_MASK                     _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_2_4_2_0_WRITE_MASK                    _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_2_4_2_0_COEF_SHIFT                    _MK_SHIFT_CONST(0)
#define I2S_LCOEF_2_4_2_0_COEF_FIELD                    _MK_FIELD_CONST(0xffff, I2S_LCOEF_2_4_2_0_COEF_SHIFT)
#define I2S_LCOEF_2_4_2_0_COEF_RANGE                    15:0
#define I2S_LCOEF_2_4_2_0_COEF_WOFFSET                  0x0
#define I2S_LCOEF_2_4_2_0_COEF_DEFAULT                  _MK_MASK_CONST(0x4c07)
#define I2S_LCOEF_2_4_2_0_COEF_DEFAULT_MASK                     _MK_MASK_CONST(0xffff)
#define I2S_LCOEF_2_4_2_0_COEF_SW_DEFAULT                       _MK_MASK_CONST(0x0)
#define I2S_LCOEF_2_4_2_0_COEF_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)

#define AUDIO_FLOWCTL_DATA_WIDTH        24
#define AUDIO_FLOWCTL_COEF_WIDTH        16
#define AUDIO_FLOWCTL_MULT_WIDTH        40
#define AUDIO_FLOWCTL_MAX_CHANNELS      1
#define AUDIO_FLOWCTL_FILT_STEPS        4
#define AUDIO_FLOWCTL_TIME_STEP_BITS    16
#define AUDIO_FLOWCTL_MAX_CYCLE_CNT     13
#define AUDIO_FLOWCTL_ACC_WIDTH 43
#define AUDIO_FLOWCTL_TIMESTEP_WIDTH    32
#define AUDIO_FLOWCTL_CNT_WIDTH 32
#define AUDIO_FLOWCTL_INTERP_SHIFT      15
#define AUDIO_FLOWCTL_TIME_SHIFT        13
#define AUDIO_FLOWCTL_LOUT_SHFT_WIDTH   28
#define AUDIO_FLOWCTL_LOUT_TMP_WIDTH    30
#define AUDIO_FLOWCTL_STEP_BIT15_MASK   32768
#define AUDIO_FLOWCTL_MAX_NEG_VAL       8388608
#define AUDIO_FLOWCTL_MAX_POS_VAL       8388607
#define I2S_DATA_WIDTH  32
#define I2S_BIT_CNT_WIDTH       5
#define I2S_FS_PIPE_STAGES      1
#define I2S_DOUT_PIPE_STAGES    1
#define I2S_CORE_PIPE_STAGES    2
#define I2S_TOTAL_PIPE_STAGES   4

//
// REGISTER LIST
//
#define LIST_ARI2S_REGS(_op_) \
_op_(I2S_CTRL_0) \
_op_(I2S_TIMING_0) \
_op_(I2S_OFFSET_0) \
_op_(I2S_CH_CTRL_0) \
_op_(I2S_SLOT_CTRL_0) \
_op_(I2S_AUDIOCIF_I2STX_CTRL_0) \
_op_(I2S_AUDIOCIF_I2SRX_CTRL_0) \
_op_(I2S_FLOWCTL_0) \
_op_(I2S_TX_STEP_0) \
_op_(I2S_FLOW_STATUS_0) \
_op_(I2S_FLOW_TOTAL_0) \
_op_(I2S_FLOW_OVER_0) \
_op_(I2S_FLOW_UNDER_0) \
_op_(I2S_LCOEF_1_4_0_0) \
_op_(I2S_LCOEF_1_4_1_0) \
_op_(I2S_LCOEF_1_4_2_0) \
_op_(I2S_LCOEF_1_4_3_0) \
_op_(I2S_LCOEF_1_4_4_0) \
_op_(I2S_LCOEF_1_4_5_0) \
_op_(I2S_LCOEF_2_4_0_0) \
_op_(I2S_LCOEF_2_4_1_0) \
_op_(I2S_LCOEF_2_4_2_0)


//
// ADDRESS SPACES
//

#define BASE_ADDRESS_I2S        0x00000000

//
// ARI2S REGISTER BANKS
//

#define I2S0_FIRST_REG 0x0000 // I2S_CTRL_0
#define I2S0_LAST_REG 0x0054 // I2S_LCOEF_2_4_2_0

// To satisfy various compilers and platforms,
// we let users control the types and syntax of certain constants, using macros.
#ifndef _MK_SHIFT_CONST
  #define _MK_SHIFT_CONST(_constant_) _constant_
#endif
#ifndef _MK_MASK_CONST
  #define _MK_MASK_CONST(_constant_) _constant_
#endif
#ifndef _MK_ENUM_CONST
  #define _MK_ENUM_CONST(_constant_) (_constant_ ## UL)
#endif
#ifndef _MK_ADDR_CONST
  #define _MK_ADDR_CONST(_constant_) _constant_
#endif
#ifndef _MK_FIELD_CONST
  #define _MK_FIELD_CONST(_mask_, _shift_) (_MK_MASK_CONST(_mask_) << _MK_SHIFT_CONST(_shift_))
#endif

#endif // ifndef ___ARI2S_H_INC_
