/*
 * Copyright (c) 2012, NVIDIA CORPORATION.  All rights reserved.
 *
 * NVIDIA CORPORATION and its licensors retain all intellectual property
 * and proprietary rights in and to this software, related documentation
 * and any modifications thereto.  Any use, reproduction, disclosure or
 * distribution of this software and related documentation without an express
 * license agreement from NVIDIA CORPORATION is strictly prohibited
 */

//
// DO NOT EDIT - generated by simspec!
//

#ifndef ___ARICTLR_H_INC_
#define ___ARICTLR_H_INC_

// Register ICTLR_VIRQ_CPU_0
#define ICTLR_VIRQ_CPU_0                        _MK_ADDR_CONST(0x0)
#define ICTLR_VIRQ_CPU_0_SECURE                         0x0
#define ICTLR_VIRQ_CPU_0_WORD_COUNT                     0x1
#define ICTLR_VIRQ_CPU_0_RESET_VAL                      _MK_MASK_CONST(0x0)
#define ICTLR_VIRQ_CPU_0_RESET_MASK                     _MK_MASK_CONST(0xffffffff)
#define ICTLR_VIRQ_CPU_0_SW_DEFAULT_VAL                         _MK_MASK_CONST(0x0)
#define ICTLR_VIRQ_CPU_0_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define ICTLR_VIRQ_CPU_0_READ_MASK                      _MK_MASK_CONST(0xffffffff)
#define ICTLR_VIRQ_CPU_0_WRITE_MASK                     _MK_MASK_CONST(0x0)
#define ICTLR_VIRQ_CPU_0_IRQ31_IRQ0_SHIFT                       _MK_SHIFT_CONST(0)
#define ICTLR_VIRQ_CPU_0_IRQ31_IRQ0_FIELD                       _MK_FIELD_CONST(0xffffffff, ICTLR_VIRQ_CPU_0_IRQ31_IRQ0_SHIFT)
#define ICTLR_VIRQ_CPU_0_IRQ31_IRQ0_RANGE                       31:0
#define ICTLR_VIRQ_CPU_0_IRQ31_IRQ0_WOFFSET                     0x0
#define ICTLR_VIRQ_CPU_0_IRQ31_IRQ0_DEFAULT                     _MK_MASK_CONST(0x0)
#define ICTLR_VIRQ_CPU_0_IRQ31_IRQ0_DEFAULT_MASK                        _MK_MASK_CONST(0xffffffff)
#define ICTLR_VIRQ_CPU_0_IRQ31_IRQ0_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define ICTLR_VIRQ_CPU_0_IRQ31_IRQ0_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)


// Register ICTLR_VIRQ_COP_0
#define ICTLR_VIRQ_COP_0                        _MK_ADDR_CONST(0x4)
#define ICTLR_VIRQ_COP_0_SECURE                         0x0
#define ICTLR_VIRQ_COP_0_WORD_COUNT                     0x1
#define ICTLR_VIRQ_COP_0_RESET_VAL                      _MK_MASK_CONST(0x0)
#define ICTLR_VIRQ_COP_0_RESET_MASK                     _MK_MASK_CONST(0xffffffff)
#define ICTLR_VIRQ_COP_0_SW_DEFAULT_VAL                         _MK_MASK_CONST(0x0)
#define ICTLR_VIRQ_COP_0_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define ICTLR_VIRQ_COP_0_READ_MASK                      _MK_MASK_CONST(0xffffffff)
#define ICTLR_VIRQ_COP_0_WRITE_MASK                     _MK_MASK_CONST(0x0)
#define ICTLR_VIRQ_COP_0_IRQ31_IRQ0_SHIFT                       _MK_SHIFT_CONST(0)
#define ICTLR_VIRQ_COP_0_IRQ31_IRQ0_FIELD                       _MK_FIELD_CONST(0xffffffff, ICTLR_VIRQ_COP_0_IRQ31_IRQ0_SHIFT)
#define ICTLR_VIRQ_COP_0_IRQ31_IRQ0_RANGE                       31:0
#define ICTLR_VIRQ_COP_0_IRQ31_IRQ0_WOFFSET                     0x0
#define ICTLR_VIRQ_COP_0_IRQ31_IRQ0_DEFAULT                     _MK_MASK_CONST(0x0)
#define ICTLR_VIRQ_COP_0_IRQ31_IRQ0_DEFAULT_MASK                        _MK_MASK_CONST(0xffffffff)
#define ICTLR_VIRQ_COP_0_IRQ31_IRQ0_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define ICTLR_VIRQ_COP_0_IRQ31_IRQ0_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)


// Register ICTLR_VFIQ_CPU_0
#define ICTLR_VFIQ_CPU_0                        _MK_ADDR_CONST(0x8)
#define ICTLR_VFIQ_CPU_0_SECURE                         0x0
#define ICTLR_VFIQ_CPU_0_WORD_COUNT                     0x1
#define ICTLR_VFIQ_CPU_0_RESET_VAL                      _MK_MASK_CONST(0x0)
#define ICTLR_VFIQ_CPU_0_RESET_MASK                     _MK_MASK_CONST(0xffffffff)
#define ICTLR_VFIQ_CPU_0_SW_DEFAULT_VAL                         _MK_MASK_CONST(0x0)
#define ICTLR_VFIQ_CPU_0_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define ICTLR_VFIQ_CPU_0_READ_MASK                      _MK_MASK_CONST(0xffffffff)
#define ICTLR_VFIQ_CPU_0_WRITE_MASK                     _MK_MASK_CONST(0x0)
#define ICTLR_VFIQ_CPU_0_FIQ31_FIQ0_SHIFT                       _MK_SHIFT_CONST(0)
#define ICTLR_VFIQ_CPU_0_FIQ31_FIQ0_FIELD                       _MK_FIELD_CONST(0xffffffff, ICTLR_VFIQ_CPU_0_FIQ31_FIQ0_SHIFT)
#define ICTLR_VFIQ_CPU_0_FIQ31_FIQ0_RANGE                       31:0
#define ICTLR_VFIQ_CPU_0_FIQ31_FIQ0_WOFFSET                     0x0
#define ICTLR_VFIQ_CPU_0_FIQ31_FIQ0_DEFAULT                     _MK_MASK_CONST(0x0)
#define ICTLR_VFIQ_CPU_0_FIQ31_FIQ0_DEFAULT_MASK                        _MK_MASK_CONST(0xffffffff)
#define ICTLR_VFIQ_CPU_0_FIQ31_FIQ0_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define ICTLR_VFIQ_CPU_0_FIQ31_FIQ0_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)


// Register ICTLR_VFIQ_COP_0
#define ICTLR_VFIQ_COP_0                        _MK_ADDR_CONST(0xc)
#define ICTLR_VFIQ_COP_0_SECURE                         0x0
#define ICTLR_VFIQ_COP_0_WORD_COUNT                     0x1
#define ICTLR_VFIQ_COP_0_RESET_VAL                      _MK_MASK_CONST(0x0)
#define ICTLR_VFIQ_COP_0_RESET_MASK                     _MK_MASK_CONST(0xffffffff)
#define ICTLR_VFIQ_COP_0_SW_DEFAULT_VAL                         _MK_MASK_CONST(0x0)
#define ICTLR_VFIQ_COP_0_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define ICTLR_VFIQ_COP_0_READ_MASK                      _MK_MASK_CONST(0xffffffff)
#define ICTLR_VFIQ_COP_0_WRITE_MASK                     _MK_MASK_CONST(0x0)
#define ICTLR_VFIQ_COP_0_FIQ31_FIQ0_SHIFT                       _MK_SHIFT_CONST(0)
#define ICTLR_VFIQ_COP_0_FIQ31_FIQ0_FIELD                       _MK_FIELD_CONST(0xffffffff, ICTLR_VFIQ_COP_0_FIQ31_FIQ0_SHIFT)
#define ICTLR_VFIQ_COP_0_FIQ31_FIQ0_RANGE                       31:0
#define ICTLR_VFIQ_COP_0_FIQ31_FIQ0_WOFFSET                     0x0
#define ICTLR_VFIQ_COP_0_FIQ31_FIQ0_DEFAULT                     _MK_MASK_CONST(0x0)
#define ICTLR_VFIQ_COP_0_FIQ31_FIQ0_DEFAULT_MASK                        _MK_MASK_CONST(0xffffffff)
#define ICTLR_VFIQ_COP_0_FIQ31_FIQ0_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define ICTLR_VFIQ_COP_0_FIQ31_FIQ0_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)


// Register ICTLR_ISR_0
#define ICTLR_ISR_0                     _MK_ADDR_CONST(0x10)
#define ICTLR_ISR_0_SECURE                      0x0
#define ICTLR_ISR_0_WORD_COUNT                  0x1
#define ICTLR_ISR_0_RESET_VAL                   _MK_MASK_CONST(0x0)
#define ICTLR_ISR_0_RESET_MASK                  _MK_MASK_CONST(0xffffffff)
#define ICTLR_ISR_0_SW_DEFAULT_VAL                      _MK_MASK_CONST(0x0)
#define ICTLR_ISR_0_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)
#define ICTLR_ISR_0_READ_MASK                   _MK_MASK_CONST(0xffffffff)
#define ICTLR_ISR_0_WRITE_MASK                  _MK_MASK_CONST(0x0)
#define ICTLR_ISR_0_ISR31_ISR0_SHIFT                    _MK_SHIFT_CONST(0)
#define ICTLR_ISR_0_ISR31_ISR0_FIELD                    _MK_FIELD_CONST(0xffffffff, ICTLR_ISR_0_ISR31_ISR0_SHIFT)
#define ICTLR_ISR_0_ISR31_ISR0_RANGE                    31:0
#define ICTLR_ISR_0_ISR31_ISR0_WOFFSET                  0x0
#define ICTLR_ISR_0_ISR31_ISR0_DEFAULT                  _MK_MASK_CONST(0x0)
#define ICTLR_ISR_0_ISR31_ISR0_DEFAULT_MASK                     _MK_MASK_CONST(0xffffffff)
#define ICTLR_ISR_0_ISR31_ISR0_SW_DEFAULT                       _MK_MASK_CONST(0x0)
#define ICTLR_ISR_0_ISR31_ISR0_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)


// Register ICTLR_FIR_0
#define ICTLR_FIR_0                     _MK_ADDR_CONST(0x14)
#define ICTLR_FIR_0_SECURE                      0x0
#define ICTLR_FIR_0_WORD_COUNT                  0x1
#define ICTLR_FIR_0_RESET_VAL                   _MK_MASK_CONST(0x0)
#define ICTLR_FIR_0_RESET_MASK                  _MK_MASK_CONST(0xffffffff)
#define ICTLR_FIR_0_SW_DEFAULT_VAL                      _MK_MASK_CONST(0x0)
#define ICTLR_FIR_0_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)
#define ICTLR_FIR_0_READ_MASK                   _MK_MASK_CONST(0xffffffff)
#define ICTLR_FIR_0_WRITE_MASK                  _MK_MASK_CONST(0x0)
#define ICTLR_FIR_0_FIR31_FIR0_SHIFT                    _MK_SHIFT_CONST(0)
#define ICTLR_FIR_0_FIR31_FIR0_FIELD                    _MK_FIELD_CONST(0xffffffff, ICTLR_FIR_0_FIR31_FIR0_SHIFT)
#define ICTLR_FIR_0_FIR31_FIR0_RANGE                    31:0
#define ICTLR_FIR_0_FIR31_FIR0_WOFFSET                  0x0
#define ICTLR_FIR_0_FIR31_FIR0_DEFAULT                  _MK_MASK_CONST(0x0)
#define ICTLR_FIR_0_FIR31_FIR0_DEFAULT_MASK                     _MK_MASK_CONST(0xffffffff)
#define ICTLR_FIR_0_FIR31_FIR0_SW_DEFAULT                       _MK_MASK_CONST(0x0)
#define ICTLR_FIR_0_FIR31_FIR0_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)


// Register ICTLR_FIR_SET_0
#define ICTLR_FIR_SET_0                 _MK_ADDR_CONST(0x18)
#define ICTLR_FIR_SET_0_SECURE                  0x0
#define ICTLR_FIR_SET_0_WORD_COUNT                      0x1
#define ICTLR_FIR_SET_0_RESET_VAL                       _MK_MASK_CONST(0x0)
#define ICTLR_FIR_SET_0_RESET_MASK                      _MK_MASK_CONST(0xffffffff)
#define ICTLR_FIR_SET_0_SW_DEFAULT_VAL                  _MK_MASK_CONST(0x0)
#define ICTLR_FIR_SET_0_SW_DEFAULT_MASK                         _MK_MASK_CONST(0x0)
#define ICTLR_FIR_SET_0_READ_MASK                       _MK_MASK_CONST(0x0)
#define ICTLR_FIR_SET_0_WRITE_MASK                      _MK_MASK_CONST(0xffffffff)
#define ICTLR_FIR_SET_0_FIR_SET_SHIFT                   _MK_SHIFT_CONST(0)
#define ICTLR_FIR_SET_0_FIR_SET_FIELD                   _MK_FIELD_CONST(0xffffffff, ICTLR_FIR_SET_0_FIR_SET_SHIFT)
#define ICTLR_FIR_SET_0_FIR_SET_RANGE                   31:0
#define ICTLR_FIR_SET_0_FIR_SET_WOFFSET                 0x0
#define ICTLR_FIR_SET_0_FIR_SET_DEFAULT                 _MK_MASK_CONST(0x0)
#define ICTLR_FIR_SET_0_FIR_SET_DEFAULT_MASK                    _MK_MASK_CONST(0xffffffff)
#define ICTLR_FIR_SET_0_FIR_SET_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define ICTLR_FIR_SET_0_FIR_SET_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)


// Register ICTLR_FIR_CLR_0
#define ICTLR_FIR_CLR_0                 _MK_ADDR_CONST(0x1c)
#define ICTLR_FIR_CLR_0_SECURE                  0x0
#define ICTLR_FIR_CLR_0_WORD_COUNT                      0x1
#define ICTLR_FIR_CLR_0_RESET_VAL                       _MK_MASK_CONST(0x0)
#define ICTLR_FIR_CLR_0_RESET_MASK                      _MK_MASK_CONST(0xffffffff)
#define ICTLR_FIR_CLR_0_SW_DEFAULT_VAL                  _MK_MASK_CONST(0x0)
#define ICTLR_FIR_CLR_0_SW_DEFAULT_MASK                         _MK_MASK_CONST(0x0)
#define ICTLR_FIR_CLR_0_READ_MASK                       _MK_MASK_CONST(0x0)
#define ICTLR_FIR_CLR_0_WRITE_MASK                      _MK_MASK_CONST(0xffffffff)
#define ICTLR_FIR_CLR_0_FIR_CLR_SHIFT                   _MK_SHIFT_CONST(0)
#define ICTLR_FIR_CLR_0_FIR_CLR_FIELD                   _MK_FIELD_CONST(0xffffffff, ICTLR_FIR_CLR_0_FIR_CLR_SHIFT)
#define ICTLR_FIR_CLR_0_FIR_CLR_RANGE                   31:0
#define ICTLR_FIR_CLR_0_FIR_CLR_WOFFSET                 0x0
#define ICTLR_FIR_CLR_0_FIR_CLR_DEFAULT                 _MK_MASK_CONST(0x0)
#define ICTLR_FIR_CLR_0_FIR_CLR_DEFAULT_MASK                    _MK_MASK_CONST(0xffffffff)
#define ICTLR_FIR_CLR_0_FIR_CLR_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define ICTLR_FIR_CLR_0_FIR_CLR_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)


// Register ICTLR_CPU_IER_0
#define ICTLR_CPU_IER_0                 _MK_ADDR_CONST(0x20)
#define ICTLR_CPU_IER_0_SECURE                  0x0
#define ICTLR_CPU_IER_0_WORD_COUNT                      0x1
#define ICTLR_CPU_IER_0_RESET_VAL                       _MK_MASK_CONST(0x0)
#define ICTLR_CPU_IER_0_RESET_MASK                      _MK_MASK_CONST(0xffffffff)
#define ICTLR_CPU_IER_0_SW_DEFAULT_VAL                  _MK_MASK_CONST(0x0)
#define ICTLR_CPU_IER_0_SW_DEFAULT_MASK                         _MK_MASK_CONST(0x0)
#define ICTLR_CPU_IER_0_READ_MASK                       _MK_MASK_CONST(0xffffffff)
#define ICTLR_CPU_IER_0_WRITE_MASK                      _MK_MASK_CONST(0x0)
#define ICTLR_CPU_IER_0_IER31_IER0_SHIFT                        _MK_SHIFT_CONST(0)
#define ICTLR_CPU_IER_0_IER31_IER0_FIELD                        _MK_FIELD_CONST(0xffffffff, ICTLR_CPU_IER_0_IER31_IER0_SHIFT)
#define ICTLR_CPU_IER_0_IER31_IER0_RANGE                        31:0
#define ICTLR_CPU_IER_0_IER31_IER0_WOFFSET                      0x0
#define ICTLR_CPU_IER_0_IER31_IER0_DEFAULT                      _MK_MASK_CONST(0x0)
#define ICTLR_CPU_IER_0_IER31_IER0_DEFAULT_MASK                 _MK_MASK_CONST(0xffffffff)
#define ICTLR_CPU_IER_0_IER31_IER0_SW_DEFAULT                   _MK_MASK_CONST(0x0)
#define ICTLR_CPU_IER_0_IER31_IER0_SW_DEFAULT_MASK                      _MK_MASK_CONST(0x0)


// Register ICTLR_CPU_IER_SET_0
#define ICTLR_CPU_IER_SET_0                     _MK_ADDR_CONST(0x24)
#define ICTLR_CPU_IER_SET_0_SECURE                      0x0
#define ICTLR_CPU_IER_SET_0_WORD_COUNT                  0x1
#define ICTLR_CPU_IER_SET_0_RESET_VAL                   _MK_MASK_CONST(0x0)
#define ICTLR_CPU_IER_SET_0_RESET_MASK                  _MK_MASK_CONST(0xffffffff)
#define ICTLR_CPU_IER_SET_0_SW_DEFAULT_VAL                      _MK_MASK_CONST(0x0)
#define ICTLR_CPU_IER_SET_0_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)
#define ICTLR_CPU_IER_SET_0_READ_MASK                   _MK_MASK_CONST(0x0)
#define ICTLR_CPU_IER_SET_0_WRITE_MASK                  _MK_MASK_CONST(0xffffffff)
#define ICTLR_CPU_IER_SET_0_CPU_IER_SET_SHIFT                   _MK_SHIFT_CONST(0)
#define ICTLR_CPU_IER_SET_0_CPU_IER_SET_FIELD                   _MK_FIELD_CONST(0xffffffff, ICTLR_CPU_IER_SET_0_CPU_IER_SET_SHIFT)
#define ICTLR_CPU_IER_SET_0_CPU_IER_SET_RANGE                   31:0
#define ICTLR_CPU_IER_SET_0_CPU_IER_SET_WOFFSET                 0x0
#define ICTLR_CPU_IER_SET_0_CPU_IER_SET_DEFAULT                 _MK_MASK_CONST(0x0)
#define ICTLR_CPU_IER_SET_0_CPU_IER_SET_DEFAULT_MASK                    _MK_MASK_CONST(0xffffffff)
#define ICTLR_CPU_IER_SET_0_CPU_IER_SET_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define ICTLR_CPU_IER_SET_0_CPU_IER_SET_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)


// Register ICTLR_CPU_IER_CLR_0
#define ICTLR_CPU_IER_CLR_0                     _MK_ADDR_CONST(0x28)
#define ICTLR_CPU_IER_CLR_0_SECURE                      0x0
#define ICTLR_CPU_IER_CLR_0_WORD_COUNT                  0x1
#define ICTLR_CPU_IER_CLR_0_RESET_VAL                   _MK_MASK_CONST(0x0)
#define ICTLR_CPU_IER_CLR_0_RESET_MASK                  _MK_MASK_CONST(0xffffffff)
#define ICTLR_CPU_IER_CLR_0_SW_DEFAULT_VAL                      _MK_MASK_CONST(0x0)
#define ICTLR_CPU_IER_CLR_0_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)
#define ICTLR_CPU_IER_CLR_0_READ_MASK                   _MK_MASK_CONST(0x0)
#define ICTLR_CPU_IER_CLR_0_WRITE_MASK                  _MK_MASK_CONST(0xffffffff)
#define ICTLR_CPU_IER_CLR_0_CPU_IER_CLR_SHIFT                   _MK_SHIFT_CONST(0)
#define ICTLR_CPU_IER_CLR_0_CPU_IER_CLR_FIELD                   _MK_FIELD_CONST(0xffffffff, ICTLR_CPU_IER_CLR_0_CPU_IER_CLR_SHIFT)
#define ICTLR_CPU_IER_CLR_0_CPU_IER_CLR_RANGE                   31:0
#define ICTLR_CPU_IER_CLR_0_CPU_IER_CLR_WOFFSET                 0x0
#define ICTLR_CPU_IER_CLR_0_CPU_IER_CLR_DEFAULT                 _MK_MASK_CONST(0x0)
#define ICTLR_CPU_IER_CLR_0_CPU_IER_CLR_DEFAULT_MASK                    _MK_MASK_CONST(0xffffffff)
#define ICTLR_CPU_IER_CLR_0_CPU_IER_CLR_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define ICTLR_CPU_IER_CLR_0_CPU_IER_CLR_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)


// Register ICTLR_CPU_IEP_CLASS_0
#define ICTLR_CPU_IEP_CLASS_0                   _MK_ADDR_CONST(0x2c)
#define ICTLR_CPU_IEP_CLASS_0_SECURE                    0x0
#define ICTLR_CPU_IEP_CLASS_0_WORD_COUNT                        0x1
#define ICTLR_CPU_IEP_CLASS_0_RESET_VAL                         _MK_MASK_CONST(0x0)
#define ICTLR_CPU_IEP_CLASS_0_RESET_MASK                        _MK_MASK_CONST(0xffffffff)
#define ICTLR_CPU_IEP_CLASS_0_SW_DEFAULT_VAL                    _MK_MASK_CONST(0x0)
#define ICTLR_CPU_IEP_CLASS_0_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define ICTLR_CPU_IEP_CLASS_0_READ_MASK                         _MK_MASK_CONST(0xffffffff)
#define ICTLR_CPU_IEP_CLASS_0_WRITE_MASK                        _MK_MASK_CONST(0xffffffff)
#define ICTLR_CPU_IEP_CLASS_0_CPU_IEP_CLASS_SHIFT                       _MK_SHIFT_CONST(0)
#define ICTLR_CPU_IEP_CLASS_0_CPU_IEP_CLASS_FIELD                       _MK_FIELD_CONST(0xffffffff, ICTLR_CPU_IEP_CLASS_0_CPU_IEP_CLASS_SHIFT)
#define ICTLR_CPU_IEP_CLASS_0_CPU_IEP_CLASS_RANGE                       31:0
#define ICTLR_CPU_IEP_CLASS_0_CPU_IEP_CLASS_WOFFSET                     0x0
#define ICTLR_CPU_IEP_CLASS_0_CPU_IEP_CLASS_DEFAULT                     _MK_MASK_CONST(0x0)
#define ICTLR_CPU_IEP_CLASS_0_CPU_IEP_CLASS_DEFAULT_MASK                        _MK_MASK_CONST(0xffffffff)
#define ICTLR_CPU_IEP_CLASS_0_CPU_IEP_CLASS_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define ICTLR_CPU_IEP_CLASS_0_CPU_IEP_CLASS_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)


// Register ICTLR_COP_IER_0
#define ICTLR_COP_IER_0                 _MK_ADDR_CONST(0x30)
#define ICTLR_COP_IER_0_SECURE                  0x0
#define ICTLR_COP_IER_0_WORD_COUNT                      0x1
#define ICTLR_COP_IER_0_RESET_VAL                       _MK_MASK_CONST(0x0)
#define ICTLR_COP_IER_0_RESET_MASK                      _MK_MASK_CONST(0xffffffff)
#define ICTLR_COP_IER_0_SW_DEFAULT_VAL                  _MK_MASK_CONST(0x0)
#define ICTLR_COP_IER_0_SW_DEFAULT_MASK                         _MK_MASK_CONST(0x0)
#define ICTLR_COP_IER_0_READ_MASK                       _MK_MASK_CONST(0xffffffff)
#define ICTLR_COP_IER_0_WRITE_MASK                      _MK_MASK_CONST(0x0)
#define ICTLR_COP_IER_0_IER31_IER0_SHIFT                        _MK_SHIFT_CONST(0)
#define ICTLR_COP_IER_0_IER31_IER0_FIELD                        _MK_FIELD_CONST(0xffffffff, ICTLR_COP_IER_0_IER31_IER0_SHIFT)
#define ICTLR_COP_IER_0_IER31_IER0_RANGE                        31:0
#define ICTLR_COP_IER_0_IER31_IER0_WOFFSET                      0x0
#define ICTLR_COP_IER_0_IER31_IER0_DEFAULT                      _MK_MASK_CONST(0x0)
#define ICTLR_COP_IER_0_IER31_IER0_DEFAULT_MASK                 _MK_MASK_CONST(0xffffffff)
#define ICTLR_COP_IER_0_IER31_IER0_SW_DEFAULT                   _MK_MASK_CONST(0x0)
#define ICTLR_COP_IER_0_IER31_IER0_SW_DEFAULT_MASK                      _MK_MASK_CONST(0x0)


// Register ICTLR_COP_IER_SET_0
#define ICTLR_COP_IER_SET_0                     _MK_ADDR_CONST(0x34)
#define ICTLR_COP_IER_SET_0_SECURE                      0x0
#define ICTLR_COP_IER_SET_0_WORD_COUNT                  0x1
#define ICTLR_COP_IER_SET_0_RESET_VAL                   _MK_MASK_CONST(0x0)
#define ICTLR_COP_IER_SET_0_RESET_MASK                  _MK_MASK_CONST(0xffffffff)
#define ICTLR_COP_IER_SET_0_SW_DEFAULT_VAL                      _MK_MASK_CONST(0x0)
#define ICTLR_COP_IER_SET_0_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)
#define ICTLR_COP_IER_SET_0_READ_MASK                   _MK_MASK_CONST(0x0)
#define ICTLR_COP_IER_SET_0_WRITE_MASK                  _MK_MASK_CONST(0xffffffff)
#define ICTLR_COP_IER_SET_0_COP_IER_SET_SHIFT                   _MK_SHIFT_CONST(0)
#define ICTLR_COP_IER_SET_0_COP_IER_SET_FIELD                   _MK_FIELD_CONST(0xffffffff, ICTLR_COP_IER_SET_0_COP_IER_SET_SHIFT)
#define ICTLR_COP_IER_SET_0_COP_IER_SET_RANGE                   31:0
#define ICTLR_COP_IER_SET_0_COP_IER_SET_WOFFSET                 0x0
#define ICTLR_COP_IER_SET_0_COP_IER_SET_DEFAULT                 _MK_MASK_CONST(0x0)
#define ICTLR_COP_IER_SET_0_COP_IER_SET_DEFAULT_MASK                    _MK_MASK_CONST(0xffffffff)
#define ICTLR_COP_IER_SET_0_COP_IER_SET_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define ICTLR_COP_IER_SET_0_COP_IER_SET_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)


// Register ICTLR_COP_IER_CLR_0
#define ICTLR_COP_IER_CLR_0                     _MK_ADDR_CONST(0x38)
#define ICTLR_COP_IER_CLR_0_SECURE                      0x0
#define ICTLR_COP_IER_CLR_0_WORD_COUNT                  0x1
#define ICTLR_COP_IER_CLR_0_RESET_VAL                   _MK_MASK_CONST(0x0)
#define ICTLR_COP_IER_CLR_0_RESET_MASK                  _MK_MASK_CONST(0xffffffff)
#define ICTLR_COP_IER_CLR_0_SW_DEFAULT_VAL                      _MK_MASK_CONST(0x0)
#define ICTLR_COP_IER_CLR_0_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)
#define ICTLR_COP_IER_CLR_0_READ_MASK                   _MK_MASK_CONST(0x0)
#define ICTLR_COP_IER_CLR_0_WRITE_MASK                  _MK_MASK_CONST(0xffffffff)
#define ICTLR_COP_IER_CLR_0_COP_IER_CLR_SHIFT                   _MK_SHIFT_CONST(0)
#define ICTLR_COP_IER_CLR_0_COP_IER_CLR_FIELD                   _MK_FIELD_CONST(0xffffffff, ICTLR_COP_IER_CLR_0_COP_IER_CLR_SHIFT)
#define ICTLR_COP_IER_CLR_0_COP_IER_CLR_RANGE                   31:0
#define ICTLR_COP_IER_CLR_0_COP_IER_CLR_WOFFSET                 0x0
#define ICTLR_COP_IER_CLR_0_COP_IER_CLR_DEFAULT                 _MK_MASK_CONST(0x0)
#define ICTLR_COP_IER_CLR_0_COP_IER_CLR_DEFAULT_MASK                    _MK_MASK_CONST(0xffffffff)
#define ICTLR_COP_IER_CLR_0_COP_IER_CLR_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define ICTLR_COP_IER_CLR_0_COP_IER_CLR_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)


// Register ICTLR_COP_IEP_CLASS_0
#define ICTLR_COP_IEP_CLASS_0                   _MK_ADDR_CONST(0x3c)
#define ICTLR_COP_IEP_CLASS_0_SECURE                    0x0
#define ICTLR_COP_IEP_CLASS_0_WORD_COUNT                        0x1
#define ICTLR_COP_IEP_CLASS_0_RESET_VAL                         _MK_MASK_CONST(0x0)
#define ICTLR_COP_IEP_CLASS_0_RESET_MASK                        _MK_MASK_CONST(0xffffffff)
#define ICTLR_COP_IEP_CLASS_0_SW_DEFAULT_VAL                    _MK_MASK_CONST(0x0)
#define ICTLR_COP_IEP_CLASS_0_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define ICTLR_COP_IEP_CLASS_0_READ_MASK                         _MK_MASK_CONST(0xffffffff)
#define ICTLR_COP_IEP_CLASS_0_WRITE_MASK                        _MK_MASK_CONST(0xffffffff)
#define ICTLR_COP_IEP_CLASS_0_COP_IEP_CLASS_SHIFT                       _MK_SHIFT_CONST(0)
#define ICTLR_COP_IEP_CLASS_0_COP_IEP_CLASS_FIELD                       _MK_FIELD_CONST(0xffffffff, ICTLR_COP_IEP_CLASS_0_COP_IEP_CLASS_SHIFT)
#define ICTLR_COP_IEP_CLASS_0_COP_IEP_CLASS_RANGE                       31:0
#define ICTLR_COP_IEP_CLASS_0_COP_IEP_CLASS_WOFFSET                     0x0
#define ICTLR_COP_IEP_CLASS_0_COP_IEP_CLASS_DEFAULT                     _MK_MASK_CONST(0x0)
#define ICTLR_COP_IEP_CLASS_0_COP_IEP_CLASS_DEFAULT_MASK                        _MK_MASK_CONST(0xffffffff)
#define ICTLR_COP_IEP_CLASS_0_COP_IEP_CLASS_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define ICTLR_COP_IEP_CLASS_0_COP_IEP_CLASS_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)


//
// REGISTER LIST
//
#define LIST_ARICTLR_REGS(_op_) \
_op_(ICTLR_VIRQ_CPU_0) \
_op_(ICTLR_VIRQ_COP_0) \
_op_(ICTLR_VFIQ_CPU_0) \
_op_(ICTLR_VFIQ_COP_0) \
_op_(ICTLR_ISR_0) \
_op_(ICTLR_FIR_0) \
_op_(ICTLR_FIR_SET_0) \
_op_(ICTLR_FIR_CLR_0) \
_op_(ICTLR_CPU_IER_0) \
_op_(ICTLR_CPU_IER_SET_0) \
_op_(ICTLR_CPU_IER_CLR_0) \
_op_(ICTLR_CPU_IEP_CLASS_0) \
_op_(ICTLR_COP_IER_0) \
_op_(ICTLR_COP_IER_SET_0) \
_op_(ICTLR_COP_IER_CLR_0) \
_op_(ICTLR_COP_IEP_CLASS_0)


//
// ADDRESS SPACES
//

#define BASE_ADDRESS_ICTLR      0x00000000

//
// ARICTLR REGISTER BANKS
//

#define ICTLR0_FIRST_REG 0x0000 // ICTLR_VIRQ_CPU_0
#define ICTLR0_LAST_REG 0x003c // ICTLR_COP_IEP_CLASS_0

// To satisfy various compilers and platforms,
// we let users control the types and syntax of certain constants, using macros.
#ifndef _MK_SHIFT_CONST
  #define _MK_SHIFT_CONST(_constant_) _constant_
#endif
#ifndef _MK_MASK_CONST
  #define _MK_MASK_CONST(_constant_) _constant_
#endif
#ifndef _MK_ENUM_CONST
  #define _MK_ENUM_CONST(_constant_) (_constant_ ## UL)
#endif
#ifndef _MK_ADDR_CONST
  #define _MK_ADDR_CONST(_constant_) _constant_
#endif
#ifndef _MK_FIELD_CONST
  #define _MK_FIELD_CONST(_mask_, _shift_) (_MK_MASK_CONST(_mask_) << _MK_SHIFT_CONST(_shift_))
#endif

#endif // ifndef ___ARICTLR_H_INC_
