/*
 * Copyright (c) 2011 NVIDIA Corporation.  All rights reserved.
 *
 * NVIDIA Corporation and its licensors retain all intellectual property
 * and proprietary rights in and to this software, related documentation
 * and any modifications thereto.  Any use, reproduction, disclosure or
 * distribution of this software and related documentation without an express
 * license agreement from NVIDIA Corporation is strictly prohibited.
 */

#ifndef __ARVDE2X_T30_H_INC_
#define __ARVDE2X_T30_H_INC_

#if defined(__cplusplus)
extern "C"
{
#endif

// Register ARVDE_BSEV_SECURE_SECURITY_0
#define ARVDE_BSEV_SECURE_SECURITY_0                    _MK_ADDR_CONST(0x1110)
#define ARVDE_BSEV_SECURE_SECURITY_0_SECURE_ENG_DIS_RANGE                       0:0


// Register ARVDE_BSEV_INTR_STATUS_0
#define ARVDE_BSEV_INTR_STATUS_0                        _MK_ADDR_CONST(0x1018)
#define ARVDE_BSEV_INTR_STATUS_0_DMA_BUSY_SHIFT                 _MK_SHIFT_CONST(9)
#define ARVDE_BSEV_INTR_STATUS_0_DMA_BUSY_FIELD                 _MK_FIELD_CONST(0x1, ARVDE_BSEV_INTR_STATUS_0_DMA_BUSY_SHIFT)
#define ARVDE_BSEV_INTR_STATUS_0_DMA_BUSY_RANGE                 9:9
#define ARVDE_BSEV_INTR_STATUS_0_DMA_BUSY_WOFFSET                       0x0
#define ARVDE_BSEV_INTR_STATUS_0_DMA_BUSY_DEFAULT                       _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_INTR_STATUS_0_DMA_BUSY_DEFAULT_MASK                  _MK_MASK_CONST(0x1)
#define ARVDE_BSEV_INTR_STATUS_0_DMA_BUSY_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_INTR_STATUS_0_DMA_BUSY_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)

#define ARVDE_BSEV_INTR_STATUS_0_ICQ_EMPTY_SHIFT                        _MK_SHIFT_CONST(3)
#define ARVDE_BSEV_INTR_STATUS_0_ICQ_EMPTY_FIELD                        _MK_FIELD_CONST(0x1, ARVDE_BSEV_INTR_STATUS_0_ICQ_EMPTY_SHIFT)
#define ARVDE_BSEV_INTR_STATUS_0_ICQ_EMPTY_RANGE                        3:3
#define ARVDE_BSEV_INTR_STATUS_0_ICQ_EMPTY_WOFFSET                      0x0
#define ARVDE_BSEV_INTR_STATUS_0_ICQ_EMPTY_DEFAULT                      _MK_MASK_CONST(0x1)
#define ARVDE_BSEV_INTR_STATUS_0_ICQ_EMPTY_DEFAULT_MASK                 _MK_MASK_CONST(0x1)
#define ARVDE_BSEV_INTR_STATUS_0_ICQ_EMPTY_SW_DEFAULT                   _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_INTR_STATUS_0_ICQ_EMPTY_SW_DEFAULT_MASK                      _MK_MASK_CONST(0x0)

#define ARVDE_BSEV_INTR_STATUS_0_ENGINE_BUSY_SHIFT                      _MK_SHIFT_CONST(0)
#define ARVDE_BSEV_INTR_STATUS_0_ENGINE_BUSY_FIELD                      _MK_FIELD_CONST(0x1, ARVDE_BSEV_INTR_STATUS_0_ENGINE_BUSY_SHIFT)
#define ARVDE_BSEV_INTR_STATUS_0_ENGINE_BUSY_RANGE                      0:0
#define ARVDE_BSEV_INTR_STATUS_0_ENGINE_BUSY_WOFFSET                    0x0
#define ARVDE_BSEV_INTR_STATUS_0_ENGINE_BUSY_DEFAULT                    _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_INTR_STATUS_0_ENGINE_BUSY_DEFAULT_MASK                       _MK_MASK_CONST(0x1)
#define ARVDE_BSEV_INTR_STATUS_0_ENGINE_BUSY_SW_DEFAULT                 _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_INTR_STATUS_0_ENGINE_BUSY_SW_DEFAULT_MASK                    _MK_MASK_CONST(0x0)



// Register ARVDE_BSEV_ICMDQUE_WR_0
#define ARVDE_BSEV_ICMDQUE_WR_0                 _MK_ADDR_CONST(0x1000)


// Register ARVDE_BSEV_SECURE_CONFIG_0
#define ARVDE_BSEV_SECURE_CONFIG_0                      _MK_ADDR_CONST(0x1108)

#define ARVDE_BSEV_SECURE_CONFIG_0_SECURE_MTM2KEY_INDEX_RANGE                   30:26

#define ARVDE_BSEV_SECURE_CONFIG_0_SECURE_KEY_INDEX_SHIFT                       _MK_SHIFT_CONST(20)
#define ARVDE_BSEV_SECURE_CONFIG_0_SECURE_KEY_INDEX_FIELD                       _MK_FIELD_CONST(0x1f, ARVDE_BSEV_SECURE_CONFIG_0_SECURE_KEY_INDEX_SHIFT)
#define ARVDE_BSEV_SECURE_CONFIG_0_SECURE_KEY_INDEX_RANGE                       24:20
#define ARVDE_BSEV_SECURE_CONFIG_0_SECURE_KEY_INDEX_WOFFSET                     0x0
#define ARVDE_BSEV_SECURE_CONFIG_0_SECURE_KEY_INDEX_DEFAULT                     _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_CONFIG_0_SECURE_KEY_INDEX_DEFAULT_MASK                        _MK_MASK_CONST(0x1f)
#define ARVDE_BSEV_SECURE_CONFIG_0_SECURE_KEY_INDEX_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_CONFIG_0_SECURE_KEY_INDEX_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)

#define ARVDE_BSEV_SECURE_CONFIG_0_SECURE_BLOCK_CNT_SHIFT                       _MK_SHIFT_CONST(0)
#define ARVDE_BSEV_SECURE_CONFIG_0_SECURE_BLOCK_CNT_FIELD                       _MK_FIELD_CONST(0xfffff, ARVDE_BSEV_SECURE_CONFIG_0_SECURE_BLOCK_CNT_SHIFT)
#define ARVDE_BSEV_SECURE_CONFIG_0_SECURE_BLOCK_CNT_RANGE                       19:0
#define ARVDE_BSEV_SECURE_CONFIG_0_SECURE_BLOCK_CNT_WOFFSET                     0x0
#define ARVDE_BSEV_SECURE_CONFIG_0_SECURE_BLOCK_CNT_DEFAULT                     _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_CONFIG_0_SECURE_BLOCK_CNT_DEFAULT_MASK                        _MK_MASK_CONST(0xfffff)
#define ARVDE_BSEV_SECURE_CONFIG_0_SECURE_BLOCK_CNT_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_CONFIG_0_SECURE_BLOCK_CNT_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)



// Register ARVDE_BSEV_SECURE_CONFIG_EXT_0
#define ARVDE_BSEV_SECURE_CONFIG_EXT_0                  _MK_ADDR_CONST(0x110c)
#define ARVDE_BSEV_SECURE_CONFIG_EXT_0_SECURE_OFFSET_CNT_SHIFT                  _MK_SHIFT_CONST(24)
#define ARVDE_BSEV_SECURE_CONFIG_EXT_0_SECURE_OFFSET_CNT_FIELD                  _MK_FIELD_CONST(0xff, ARVDE_BSEV_SECURE_CONFIG_EXT_0_SECURE_OFFSET_CNT_SHIFT)
#define ARVDE_BSEV_SECURE_CONFIG_EXT_0_SECURE_OFFSET_CNT_RANGE                  31:24
#define ARVDE_BSEV_SECURE_CONFIG_EXT_0_SECURE_OFFSET_CNT_WOFFSET                        0x0
#define ARVDE_BSEV_SECURE_CONFIG_EXT_0_SECURE_OFFSET_CNT_DEFAULT                        _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_CONFIG_EXT_0_SECURE_OFFSET_CNT_DEFAULT_MASK                   _MK_MASK_CONST(0xff)
#define ARVDE_BSEV_SECURE_CONFIG_EXT_0_SECURE_OFFSET_CNT_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_CONFIG_EXT_0_SECURE_OFFSET_CNT_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)

#define ARVDE_BSEV_SECURE_CONFIG_EXT_0_SECURE_KEY_SCH_DIS_SHIFT                 _MK_SHIFT_CONST(15)
#define ARVDE_BSEV_SECURE_CONFIG_EXT_0_SECURE_KEY_SCH_DIS_FIELD                 _MK_FIELD_CONST(0x1, ARVDE_BSEV_SECURE_CONFIG_EXT_0_SECURE_KEY_SCH_DIS_SHIFT)
#define ARVDE_BSEV_SECURE_CONFIG_EXT_0_SECURE_KEY_SCH_DIS_RANGE                 15:15
#define ARVDE_BSEV_SECURE_CONFIG_EXT_0_SECURE_KEY_SCH_DIS_WOFFSET                       0x0
#define ARVDE_BSEV_SECURE_CONFIG_EXT_0_SECURE_KEY_SCH_DIS_DEFAULT                       _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_CONFIG_EXT_0_SECURE_KEY_SCH_DIS_DEFAULT_MASK                  _MK_MASK_CONST(0x1)
#define ARVDE_BSEV_SECURE_CONFIG_EXT_0_SECURE_KEY_SCH_DIS_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_CONFIG_EXT_0_SECURE_KEY_SCH_DIS_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)



// Register ARVDE_BSEV_SECURE_SEC_SEL4_0
#define ARVDE_BSEV_SECURE_SEC_SEL4_0                    _MK_ADDR_CONST(0x1150)
#define ARVDE_BSEV_SECURE_SEC_SEL4_0_KEYUPDATE_ENB4_RANGE                       1:1
#define ARVDE_BSEV_SECURE_SEC_SEL4_0_KEYREAD_ENB4_RANGE                 0:0


// Register ARVDE_BSEV_CMDQUE_CONTROL_0
#define ARVDE_BSEV_CMDQUE_CONTROL_0                     _MK_ADDR_CONST(0x1008)
#define ARVDE_BSEV_CMDQUE_CONTROL_0_DST_STM_SEL_SHIFT                   _MK_SHIFT_CONST(5)
#define ARVDE_BSEV_CMDQUE_CONTROL_0_DST_STM_SEL_FIELD                   _MK_FIELD_CONST(0x1, ARVDE_BSEV_CMDQUE_CONTROL_0_DST_STM_SEL_SHIFT)
#define ARVDE_BSEV_CMDQUE_CONTROL_0_DST_STM_SEL_RANGE                   5:5
#define ARVDE_BSEV_CMDQUE_CONTROL_0_DST_STM_SEL_WOFFSET                 0x0
#define ARVDE_BSEV_CMDQUE_CONTROL_0_DST_STM_SEL_DEFAULT                 _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_CMDQUE_CONTROL_0_DST_STM_SEL_DEFAULT_MASK                    _MK_MASK_CONST(0x1)
#define ARVDE_BSEV_CMDQUE_CONTROL_0_DST_STM_SEL_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_CMDQUE_CONTROL_0_DST_STM_SEL_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)

#define ARVDE_BSEV_CMDQUE_CONTROL_0_SRC_STM_SEL_SHIFT                   _MK_SHIFT_CONST(4)
#define ARVDE_BSEV_CMDQUE_CONTROL_0_SRC_STM_SEL_FIELD                   _MK_FIELD_CONST(0x1, ARVDE_BSEV_CMDQUE_CONTROL_0_SRC_STM_SEL_SHIFT)
#define ARVDE_BSEV_CMDQUE_CONTROL_0_SRC_STM_SEL_RANGE                   4:4
#define ARVDE_BSEV_CMDQUE_CONTROL_0_SRC_STM_SEL_WOFFSET                 0x0
#define ARVDE_BSEV_CMDQUE_CONTROL_0_SRC_STM_SEL_DEFAULT                 _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_CMDQUE_CONTROL_0_SRC_STM_SEL_DEFAULT_MASK                    _MK_MASK_CONST(0x1)
#define ARVDE_BSEV_CMDQUE_CONTROL_0_SRC_STM_SEL_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_CMDQUE_CONTROL_0_SRC_STM_SEL_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)

#define ARVDE_BSEV_CMDQUE_CONTROL_0_ERROR_FLUSH_ENB_SHIFT                       _MK_SHIFT_CONST(2)
#define ARVDE_BSEV_CMDQUE_CONTROL_0_ERROR_FLUSH_ENB_FIELD                       _MK_FIELD_CONST(0x1, ARVDE_BSEV_CMDQUE_CONTROL_0_ERROR_FLUSH_ENB_SHIFT)
#define ARVDE_BSEV_CMDQUE_CONTROL_0_ERROR_FLUSH_ENB_RANGE                       2:2
#define ARVDE_BSEV_CMDQUE_CONTROL_0_ERROR_FLUSH_ENB_WOFFSET                     0x0
#define ARVDE_BSEV_CMDQUE_CONTROL_0_ERROR_FLUSH_ENB_DEFAULT                     _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_CMDQUE_CONTROL_0_ERROR_FLUSH_ENB_DEFAULT_MASK                        _MK_MASK_CONST(0x1)
#define ARVDE_BSEV_CMDQUE_CONTROL_0_ERROR_FLUSH_ENB_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_CMDQUE_CONTROL_0_ERROR_FLUSH_ENB_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)

#define ARVDE_BSEV_CMDQUE_CONTROL_0_ICMDQUE_ENB_SHIFT                   _MK_SHIFT_CONST(1)
#define ARVDE_BSEV_CMDQUE_CONTROL_0_ICMDQUE_ENB_FIELD                   _MK_FIELD_CONST(0x1, ARVDE_BSEV_CMDQUE_CONTROL_0_ICMDQUE_ENB_SHIFT)
#define ARVDE_BSEV_CMDQUE_CONTROL_0_ICMDQUE_ENB_RANGE                   1:1
#define ARVDE_BSEV_CMDQUE_CONTROL_0_ICMDQUE_ENB_WOFFSET                 0x0
#define ARVDE_BSEV_CMDQUE_CONTROL_0_ICMDQUE_ENB_DEFAULT                 _MK_MASK_CONST(0x1)
#define ARVDE_BSEV_CMDQUE_CONTROL_0_ICMDQUE_ENB_DEFAULT_MASK                    _MK_MASK_CONST(0x1)
#define ARVDE_BSEV_CMDQUE_CONTROL_0_ICMDQUE_ENB_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_CMDQUE_CONTROL_0_ICMDQUE_ENB_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)

#define ARVDE_BSEV_CMDQUE_CONTROL_0_UCMDQUE_ENB_SHIFT                   _MK_SHIFT_CONST(0)
#define ARVDE_BSEV_CMDQUE_CONTROL_0_UCMDQUE_ENB_FIELD                   _MK_FIELD_CONST(0x1, ARVDE_BSEV_CMDQUE_CONTROL_0_UCMDQUE_ENB_SHIFT)
#define ARVDE_BSEV_CMDQUE_CONTROL_0_UCMDQUE_ENB_RANGE                   0:0
#define ARVDE_BSEV_CMDQUE_CONTROL_0_UCMDQUE_ENB_WOFFSET                 0x0
#define ARVDE_BSEV_CMDQUE_CONTROL_0_UCMDQUE_ENB_DEFAULT                 _MK_MASK_CONST(0x1)
#define ARVDE_BSEV_CMDQUE_CONTROL_0_UCMDQUE_ENB_DEFAULT_MASK                    _MK_MASK_CONST(0x1)
#define ARVDE_BSEV_CMDQUE_CONTROL_0_UCMDQUE_ENB_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_CMDQUE_CONTROL_0_UCMDQUE_ENB_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)



// Register ARVDE_BSEV_BSE_CONFIG_0
#define ARVDE_BSEV_BSE_CONFIG_0                 _MK_ADDR_CONST(0x1044)
#define ARVDE_BSEV_BSE_CONFIG_0_ENDIAN_ENB_SHIFT                        _MK_SHIFT_CONST(10)
#define ARVDE_BSEV_BSE_CONFIG_0_ENDIAN_ENB_FIELD                        _MK_FIELD_CONST(0x1, ARVDE_BSEV_BSE_CONFIG_0_ENDIAN_ENB_SHIFT)
#define ARVDE_BSEV_BSE_CONFIG_0_ENDIAN_ENB_RANGE                        10:10
#define ARVDE_BSEV_BSE_CONFIG_0_ENDIAN_ENB_WOFFSET                      0x0
#define ARVDE_BSEV_BSE_CONFIG_0_ENDIAN_ENB_DEFAULT                      _MK_MASK_CONST(0x1)
#define ARVDE_BSEV_BSE_CONFIG_0_ENDIAN_ENB_DEFAULT_MASK                 _MK_MASK_CONST(0x1)
#define ARVDE_BSEV_BSE_CONFIG_0_ENDIAN_ENB_SW_DEFAULT                   _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_BSE_CONFIG_0_ENDIAN_ENB_SW_DEFAULT_MASK                      _MK_MASK_CONST(0x0)

#define ARVDE_BSEV_BSE_CONFIG_0_BSE_MODE_SEL_SHIFT                      _MK_SHIFT_CONST(0)
#define ARVDE_BSEV_BSE_CONFIG_0_BSE_MODE_SEL_FIELD                      _MK_FIELD_CONST(0x1f, ARVDE_BSEV_BSE_CONFIG_0_BSE_MODE_SEL_SHIFT)
#define ARVDE_BSEV_BSE_CONFIG_0_BSE_MODE_SEL_RANGE                      4:0
#define ARVDE_BSEV_BSE_CONFIG_0_BSE_MODE_SEL_WOFFSET                    0x0
#define ARVDE_BSEV_BSE_CONFIG_0_BSE_MODE_SEL_DEFAULT                    _MK_MASK_CONST(0x8)
#define ARVDE_BSEV_BSE_CONFIG_0_BSE_MODE_SEL_DEFAULT_MASK                       _MK_MASK_CONST(0x1f)
#define ARVDE_BSEV_BSE_CONFIG_0_BSE_MODE_SEL_SW_DEFAULT                 _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_BSE_CONFIG_0_BSE_MODE_SEL_SW_DEFAULT_MASK                    _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_BSE_CONFIG_0_BSE_MODE_SEL_AES                        _MK_ENUM_CONST(0)
#define ARVDE_BSEV_BSE_CONFIG_0_BSE_MODE_SEL_MP3_2                      _MK_ENUM_CONST(4)
#define ARVDE_BSEV_BSE_CONFIG_0_BSE_MODE_SEL_AAC_2                      _MK_ENUM_CONST(5)
#define ARVDE_BSEV_BSE_CONFIG_0_BSE_MODE_SEL_MP3_ACC_4                  _MK_ENUM_CONST(6)
#define ARVDE_BSEV_BSE_CONFIG_0_BSE_MODE_SEL_JPEGD                      _MK_ENUM_CONST(8)
#define ARVDE_BSEV_BSE_CONFIG_0_BSE_MODE_SEL_MPEG1                      _MK_ENUM_CONST(9)
#define ARVDE_BSEV_BSE_CONFIG_0_BSE_MODE_SEL_MPEG2                      _MK_ENUM_CONST(10)
#define ARVDE_BSEV_BSE_CONFIG_0_BSE_MODE_SEL_MPEG4_VLC                  _MK_ENUM_CONST(11)
#define ARVDE_BSEV_BSE_CONFIG_0_BSE_MODE_SEL_MPEG4_RVLC                 _MK_ENUM_CONST(12)
#define ARVDE_BSEV_BSE_CONFIG_0_BSE_MODE_SEL_H264                       _MK_ENUM_CONST(13)
#define ARVDE_BSEV_BSE_CONFIG_0_BSE_MODE_SEL_VC1                        _MK_ENUM_CONST(14)
#define ARVDE_BSEV_BSE_CONFIG_0_BSE_MODE_SEL_JPEGE                      _MK_ENUM_CONST(16)



// Register ARVDE_BSEV_SECURE_DEST_ADDR_0
#define ARVDE_BSEV_SECURE_DEST_ADDR_0                   _MK_ADDR_CONST(0x1100)
#define ARVDE_BSEV_SECURE_DEST_ADDR_0_SECURE                    0x0
#define ARVDE_BSEV_SECURE_DEST_ADDR_0_WORD_COUNT                        0x1
#define ARVDE_BSEV_SECURE_DEST_ADDR_0_RESET_VAL                         _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_DEST_ADDR_0_RESET_MASK                        _MK_MASK_CONST(0xffffffff)
#define ARVDE_BSEV_SECURE_DEST_ADDR_0_SW_DEFAULT_VAL                    _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_DEST_ADDR_0_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_DEST_ADDR_0_READ_MASK                         _MK_MASK_CONST(0xffffffff)
#define ARVDE_BSEV_SECURE_DEST_ADDR_0_WRITE_MASK                        _MK_MASK_CONST(0xffffffff)

#define ARVDE_BSEV_SECURE_DEST_ADDR_0_SECURE_DEST_ADDR_SHIFT                    _MK_SHIFT_CONST(0)
#define ARVDE_BSEV_SECURE_DEST_ADDR_0_SECURE_DEST_ADDR_FIELD                    _MK_FIELD_CONST(0xffffffff, ARVDE_BSEV_SECURE_DEST_ADDR_0_SECURE_DEST_ADDR_SHIFT)
#define ARVDE_BSEV_SECURE_DEST_ADDR_0_SECURE_DEST_ADDR_RANGE                    31:0
#define ARVDE_BSEV_SECURE_DEST_ADDR_0_SECURE_DEST_ADDR_WOFFSET                  0x0
#define ARVDE_BSEV_SECURE_DEST_ADDR_0_SECURE_DEST_ADDR_DEFAULT                  _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_DEST_ADDR_0_SECURE_DEST_ADDR_DEFAULT_MASK                     _MK_MASK_CONST(0xffffffff)
#define ARVDE_BSEV_SECURE_DEST_ADDR_0_SECURE_DEST_ADDR_SW_DEFAULT                       _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_DEST_ADDR_0_SECURE_DEST_ADDR_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)



// Register ARVDE_BSEV_SECURE_INPUT_SELECT_0
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0                        _MK_ADDR_CONST(0x1104)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_INPUT_ALG_SEL_SHIFT                     _MK_SHIFT_CONST(28)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_INPUT_ALG_SEL_FIELD                     _MK_FIELD_CONST(0xf, ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_INPUT_ALG_SEL_SHIFT)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_INPUT_ALG_SEL_RANGE                     31:28
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_INPUT_ALG_SEL_WOFFSET                   0x0
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_INPUT_ALG_SEL_DEFAULT                   _MK_MASK_CONST(0x1)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_INPUT_ALG_SEL_DEFAULT_MASK                      _MK_MASK_CONST(0xf)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_INPUT_ALG_SEL_SW_DEFAULT                        _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_INPUT_ALG_SEL_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_INPUT_ALG_SEL_CLEAR                     _MK_ENUM_CONST(0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_INPUT_ALG_SEL_AES                       _MK_ENUM_CONST(1)

#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_KEY_LENGTH_SHIFT                        _MK_SHIFT_CONST(16)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_KEY_LENGTH_FIELD                        _MK_FIELD_CONST(0xfff, ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_KEY_LENGTH_SHIFT)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_KEY_LENGTH_RANGE                        27:16
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_KEY_LENGTH_WOFFSET                      0x0
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_KEY_LENGTH_DEFAULT                      _MK_MASK_CONST(0x80)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_KEY_LENGTH_DEFAULT_MASK                 _MK_MASK_CONST(0xfff)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_KEY_LENGTH_SW_DEFAULT                   _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_KEY_LENGTH_SW_DEFAULT_MASK                      _MK_MASK_CONST(0x0)

#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_MTM2KEY_ENB_RANGE                       12:12

#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_RNG_ENB_SHIFT                   _MK_SHIFT_CONST(11)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_RNG_ENB_FIELD                   _MK_FIELD_CONST(0x1, ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_RNG_ENB_SHIFT)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_RNG_ENB_RANGE                   11:11
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_RNG_ENB_WOFFSET                 0x0
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_RNG_ENB_DEFAULT                 _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_RNG_ENB_DEFAULT_MASK                    _MK_MASK_CONST(0x1)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_RNG_ENB_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_RNG_ENB_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)

#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_IV_SELECT_SHIFT                 _MK_SHIFT_CONST(10)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_IV_SELECT_FIELD                 _MK_FIELD_CONST(0x1, ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_IV_SELECT_SHIFT)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_IV_SELECT_RANGE                 10:10
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_IV_SELECT_WOFFSET                       0x0
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_IV_SELECT_DEFAULT                       _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_IV_SELECT_DEFAULT_MASK                  _MK_MASK_CONST(0x1)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_IV_SELECT_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_IV_SELECT_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_IV_SELECT_ORIGINAL                      _MK_ENUM_CONST(0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_IV_SELECT_UPDATED                       _MK_ENUM_CONST(1)

#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_CORE_SEL_SHIFT                  _MK_SHIFT_CONST(9)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_CORE_SEL_FIELD                  _MK_FIELD_CONST(0x1, ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_CORE_SEL_SHIFT)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_CORE_SEL_RANGE                  9:9
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_CORE_SEL_WOFFSET                        0x0
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_CORE_SEL_DEFAULT                        _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_CORE_SEL_DEFAULT_MASK                   _MK_MASK_CONST(0x1)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_CORE_SEL_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_CORE_SEL_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_CORE_SEL_REVERSE                        _MK_ENUM_CONST(0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_CORE_SEL_DIRECT                 _MK_ENUM_CONST(1)

#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_VCTRAM_SEL_SHIFT                        _MK_SHIFT_CONST(7)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_VCTRAM_SEL_FIELD                        _MK_FIELD_CONST(0x3, ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_VCTRAM_SEL_SHIFT)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_VCTRAM_SEL_RANGE                        8:7
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_VCTRAM_SEL_WOFFSET                      0x0
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_VCTRAM_SEL_DEFAULT                      _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_VCTRAM_SEL_DEFAULT_MASK                 _MK_MASK_CONST(0x3)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_VCTRAM_SEL_SW_DEFAULT                   _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_VCTRAM_SEL_SW_DEFAULT_MASK                      _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_VCTRAM_SEL_OFB_CNTR                     _MK_ENUM_CONST(0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_VCTRAM_SEL_RESERVED                     _MK_ENUM_CONST(1)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_VCTRAM_SEL_CBC_DIRECT                   _MK_ENUM_CONST(2)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_VCTRAM_SEL_CBC_REVERSE                  _MK_ENUM_CONST(3)

#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_INPUT_SEL_SHIFT                 _MK_SHIFT_CONST(5)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_INPUT_SEL_FIELD                 _MK_FIELD_CONST(0x3, ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_INPUT_SEL_SHIFT)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_INPUT_SEL_RANGE                 6:5
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_INPUT_SEL_WOFFSET                       0x0
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_INPUT_SEL_DEFAULT                       _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_INPUT_SEL_DEFAULT_MASK                  _MK_MASK_CONST(0x3)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_INPUT_SEL_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_INPUT_SEL_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_INPUT_SEL_ECB_CBC                       _MK_ENUM_CONST(0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_INPUT_SEL_RSVD                  _MK_ENUM_CONST(1)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_INPUT_SEL_OFB                   _MK_ENUM_CONST(2)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_INPUT_SEL_CNTR                  _MK_ENUM_CONST(3)

#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_XOR_POS_SHIFT                   _MK_SHIFT_CONST(3)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_XOR_POS_FIELD                   _MK_FIELD_CONST(0x3, ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_XOR_POS_SHIFT)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_XOR_POS_RANGE                   4:3
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_XOR_POS_WOFFSET                 0x0
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_XOR_POS_DEFAULT                 _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_XOR_POS_DEFAULT_MASK                    _MK_MASK_CONST(0x3)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_XOR_POS_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_XOR_POS_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_XOR_POS_BYPASS                  _MK_ENUM_CONST(0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_XOR_POS_BYPASS1                 _MK_ENUM_CONST(1)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_XOR_POS_TOP                     _MK_ENUM_CONST(2)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_XOR_POS_BOTTOM                  _MK_ENUM_CONST(3)

#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_HASH_ENB_SHIFT                  _MK_SHIFT_CONST(2)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_HASH_ENB_FIELD                  _MK_FIELD_CONST(0x1, ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_HASH_ENB_SHIFT)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_HASH_ENB_RANGE                  2:2
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_HASH_ENB_WOFFSET                        0x0
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_HASH_ENB_DEFAULT                        _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_HASH_ENB_DEFAULT_MASK                   _MK_MASK_CONST(0x1)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_HASH_ENB_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_SECURE_HASH_ENB_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)

#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_ON_THE_FLY_ENB_SHIFT                   _MK_SHIFT_CONST(0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_ON_THE_FLY_ENB_FIELD                   _MK_FIELD_CONST(0x1, ARVDE_BSEV_SECURE_INPUT_SELECT_0_ON_THE_FLY_ENB_SHIFT)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_ON_THE_FLY_ENB_RANGE                   0:0
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_ON_THE_FLY_ENB_WOFFSET                 0x0
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_ON_THE_FLY_ENB_DEFAULT                 _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_ON_THE_FLY_ENB_DEFAULT_MASK                    _MK_MASK_CONST(0x1)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_ON_THE_FLY_ENB_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_INPUT_SELECT_0_ON_THE_FLY_ENB_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)



// Register ARVDE_BSEV_SECURE_SEC_SEL0_0
#define ARVDE_BSEV_SECURE_SEC_SEL0_0                    _MK_ADDR_CONST(0x1140)
#define ARVDE_BSEV_SECURE_SEC_SEL0_0_KEYREAD_ENB0_SHIFT                 _MK_SHIFT_CONST(0)
#define ARVDE_BSEV_SECURE_SEC_SEL0_0_KEYREAD_ENB0_FIELD                 _MK_FIELD_CONST(0x1, ARVDE_BSEV_SECURE_SEC_SEL0_0_KEYREAD_ENB0_SHIFT)
#define ARVDE_BSEV_SECURE_SEC_SEL0_0_KEYREAD_ENB0_RANGE                 0:0
#define ARVDE_BSEV_SECURE_SEC_SEL0_0_KEYREAD_ENB0_WOFFSET                       0x0
#define ARVDE_BSEV_SECURE_SEC_SEL0_0_KEYREAD_ENB0_DEFAULT                       _MK_MASK_CONST(0x1)
#define ARVDE_BSEV_SECURE_SEC_SEL0_0_KEYREAD_ENB0_DEFAULT_MASK                  _MK_MASK_CONST(0x1)
#define ARVDE_BSEV_SECURE_SEC_SEL0_0_KEYREAD_ENB0_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define ARVDE_BSEV_SECURE_SEC_SEL0_0_KEYREAD_ENB0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)

#if defined(__cplusplus)
}
#endif

#endif

