/*
 * Copyright (c) 2012-2013, NVIDIA CORPORATION.  All rights reserved.
 *
 * NVIDIA Corporation and its licensors retain all intellectual property
 * and proprietary rights in and to this software, related documentation
 * and any modifications thereto.  Any use, reproduction, disclosure or
 * distribution of this software and related documentation without an express
 * license agreement from NVIDIA Corporation is strictly prohibited.
 */

#include "pinmux.h"
#include "pinmux_soc.h"
#include "nvcommon.h"
#include "nvodm_pinmux_init.h"

#define PINMUX_AUX_GPIO_W3_AUD_0_PM_RSVD                0
#define PINMUX_AUX_GPIO_PV1_0_PM_RSVD                   0
#define PINMUX_AUX_SDMMC1_WP_N_0_PM_RSVD                0
#define PINMUX_AUX_GPIO_PU4_0_PM_RSVD                   0
#define PINMUX_AUX_GPIO_PU5_0_PM_RSVD                   0
#define PINMUX_AUX_GPIO_PU6_0_PM_RSVD                   0
#define PINMUX_AUX_GPIO_X7_AUD_0_PM_RSVD                0

#if AVP_PINMUX == 0

// Building for T114 Dalmore
static NvPinDrivePingroupConfig dalmore_drive_pinmux[] = {
    /* DEFAULT_DRIVE(<pin_group>), */
    /* SDMMC1 */
    SET_DRIVE(SDIO1, DISABLE, DISABLE, DIV_1, 36, 20, SLOW, SLOW),

    /* SDMMC4 */
    SET_DRIVE_GMA(GMA, DISABLE, DISABLE, 1, 2, 1, FASTEST, FASTEST),
};

static NvPingroupConfig dalmore_pinmux_common[] = {

    /* EXTPERIPH1 pinmux */
    DEFAULT_PINMUX(CLK1_OUT,      EXTPERIPH1,  NORMAL,    NORMAL,   DISABLE),

    /* I2S0 pinmux */
    DEFAULT_PINMUX(DAP1_DIN,      I2S0,    NORMAL,    TRISTATE, ENABLE),
    DEFAULT_PINMUX(DAP1_DOUT,     I2S0,    NORMAL,    NORMAL,   DISABLE),
    DEFAULT_PINMUX(DAP1_FS,       I2S0,    NORMAL,    NORMAL,   DISABLE),
    DEFAULT_PINMUX(DAP1_SCLK,     I2S0,    NORMAL,    NORMAL,   DISABLE),

    /* I2S1 pinmux */
    DEFAULT_PINMUX(DAP2_DIN,      I2S1,    NORMAL,    TRISTATE, ENABLE),
    DEFAULT_PINMUX(DAP2_DOUT,     I2S1,    NORMAL,    NORMAL,   DISABLE),
    DEFAULT_PINMUX(DAP2_FS,       I2S1,    NORMAL,    NORMAL,   DISABLE),
    DEFAULT_PINMUX(DAP2_SCLK,     I2S1,    NORMAL,    NORMAL,   DISABLE),

    /* CLDVFS pinmux */
    DEFAULT_PINMUX(DVFS_PWM,      CLDVFS,      NORMAL,    NORMAL,   DISABLE),
    DEFAULT_PINMUX(DVFS_CLK,      CLDVFS,      NORMAL,    NORMAL,   DISABLE),

    /* ULPI pinmux */
    DEFAULT_PINMUX(ULPI_CLK,      ULPI,    NORMAL,    NORMAL,   ENABLE),
    DEFAULT_PINMUX(ULPI_DATA0,    ULPI,    NORMAL,    NORMAL,   ENABLE),
    DEFAULT_PINMUX(ULPI_DATA1,    ULPI,    NORMAL,    NORMAL,   ENABLE),
    DEFAULT_PINMUX(ULPI_DATA2,    ULPI,    NORMAL,    NORMAL,   ENABLE),
    DEFAULT_PINMUX(ULPI_DATA3,    ULPI,    NORMAL,    NORMAL,   ENABLE),
    DEFAULT_PINMUX(ULPI_DATA4,    ULPI,    NORMAL,    NORMAL,   ENABLE),
    DEFAULT_PINMUX(ULPI_DATA5,    ULPI,    NORMAL,    NORMAL,   ENABLE),
    DEFAULT_PINMUX(ULPI_DATA6,    ULPI,    NORMAL,    NORMAL,   ENABLE),
    DEFAULT_PINMUX(ULPI_DATA7,    ULPI,    NORMAL,    NORMAL,   ENABLE),
    DEFAULT_PINMUX(ULPI_DIR,      ULPI,    NORMAL,    TRISTATE, ENABLE),
    DEFAULT_PINMUX(ULPI_NXT,      ULPI,    NORMAL,    TRISTATE, ENABLE),
    DEFAULT_PINMUX(ULPI_STP,      ULPI,    NORMAL,    NORMAL,   DISABLE),

    /* I2C3 pinmux */
    I2C_PINMUX(CAM_I2C_SCL, I2C3, NORMAL, NORMAL, ENABLE, DISABLE, DISABLE),
    I2C_PINMUX(CAM_I2C_SDA, I2C3, NORMAL, NORMAL, ENABLE, DISABLE, DISABLE),

    /* VI pinmux */
    VI_PINMUX(CAM_MCLK, VI, NORMAL, NORMAL, DISABLE, DEFAULT, DEFAULT),

    /* VI_ALT1 pinmux */
    VI_PINMUX(GPIO_PBB0, VI_ALT1, NORMAL, NORMAL, DISABLE, DEFAULT, DEFAULT),

    /* I2C2 pinmux */
    I2C_PINMUX(GEN2_I2C_SCL, I2C2, NORMAL, NORMAL, ENABLE, DISABLE, DISABLE),
    I2C_PINMUX(GEN2_I2C_SDA, I2C2, NORMAL, NORMAL, ENABLE, DISABLE, DISABLE),

    /* UARTD pinmux */
    DEFAULT_PINMUX(GMI_A16,       UARTD,       NORMAL,    NORMAL,   DISABLE),
    DEFAULT_PINMUX(GMI_A17,       UARTD,       NORMAL,    TRISTATE, ENABLE),
    DEFAULT_PINMUX(GMI_A18,       UARTD,       NORMAL,    TRISTATE, ENABLE),
    DEFAULT_PINMUX(GMI_A19,       UARTD,       NORMAL,    NORMAL,   DISABLE),

    /* SPI4 pinmux */
    DEFAULT_PINMUX(GMI_AD5,       SPI4,    NORMAL,    NORMAL,   DISABLE),
    DEFAULT_PINMUX(GMI_AD6,       SPI4,    NORMAL,    NORMAL,   DISABLE),
    DEFAULT_PINMUX(GMI_AD7,       SPI4,    NORMAL,    TRISTATE, ENABLE),
    DEFAULT_PINMUX(GMI_CS6_N,     SPI4,    NORMAL,    NORMAL,   DISABLE),
    DEFAULT_PINMUX(GMI_WR_N,      SPI4,    NORMAL,    NORMAL,   DISABLE),

    /* SPI 1 pinmux */
    DEFAULT_PINMUX(GPIO_X4_AUD,   SPI1,    NORMAL,    NORMAL,   ENABLE),

    /* PWM1 pinmux */
    DEFAULT_PINMUX(GMI_AD9,       PWM1,    NORMAL,    NORMAL,   DISABLE),

    /* SOC pinmux */
    DEFAULT_PINMUX(GMI_CS1_N,     SOC,     NORMAL,    TRISTATE, ENABLE),
    DEFAULT_PINMUX(GMI_OE_N,      SOC,     NORMAL,    TRISTATE, ENABLE),

    /* EXTPERIPH2 pinmux */
    DEFAULT_PINMUX(CLK2_OUT,      EXTPERIPH2,  NORMAL,    NORMAL,   DISABLE),

    /* SDMMC1 pinmux */
    DEFAULT_PINMUX(SDMMC1_CLK,    SDMMC1,      NORMAL,    NORMAL,   ENABLE),
    DEFAULT_PINMUX(SDMMC1_CMD,    SDMMC1,      PULL_UP,   NORMAL,   ENABLE),
    DEFAULT_PINMUX(SDMMC1_DAT0,   SDMMC1,      PULL_UP,   NORMAL,   ENABLE),
    DEFAULT_PINMUX(SDMMC1_DAT1,   SDMMC1,      PULL_UP,   NORMAL,   ENABLE),
    DEFAULT_PINMUX(SDMMC1_DAT2,   SDMMC1,      PULL_UP,   NORMAL,   ENABLE),
    DEFAULT_PINMUX(SDMMC1_DAT3,   SDMMC1,      PULL_UP,   NORMAL,   ENABLE),

    /* SDMMC3 pinmux */
    DEFAULT_PINMUX(SDMMC3_CLK,    SDMMC3,      NORMAL,    NORMAL,   ENABLE),
    DEFAULT_PINMUX(SDMMC3_CMD,    SDMMC3,      PULL_UP,   NORMAL,   ENABLE),
    DEFAULT_PINMUX(SDMMC3_DAT0,   SDMMC3,      PULL_UP,   NORMAL,   ENABLE),
    DEFAULT_PINMUX(SDMMC3_DAT1,   SDMMC3,      PULL_UP,   NORMAL,   ENABLE),
    DEFAULT_PINMUX(SDMMC3_DAT2,   SDMMC3,      PULL_UP,   NORMAL,   ENABLE),
    DEFAULT_PINMUX(SDMMC3_DAT3,   SDMMC3,      PULL_UP,   NORMAL,   ENABLE),
    DEFAULT_PINMUX(SDMMC3_CLK_LB_OUT, SDMMC3,  PULL_UP,   NORMAL,   ENABLE),
    DEFAULT_PINMUX(SDMMC3_CLK_LB_IN,  SDMMC3,  PULL_UP,   NORMAL,   ENABLE),
    DEFAULT_PINMUX(KB_COL4,       SDMMC3,      PULL_UP,   NORMAL,   ENABLE),
    DEFAULT_PINMUX(SDMMC3_CD_N,   SDMMC3,      PULL_UP,   NORMAL,   ENABLE),

    /* SDMMC4 pinmux */
    DEFAULT_PINMUX(SDMMC4_CLK,    SDMMC4,      NORMAL,    NORMAL,   ENABLE),
    DEFAULT_PINMUX(SDMMC4_CMD,    SDMMC4,      PULL_UP,   NORMAL,   ENABLE),
    DEFAULT_PINMUX(SDMMC4_DAT0,   SDMMC4,      PULL_UP,   NORMAL,   ENABLE),
    DEFAULT_PINMUX(SDMMC4_DAT1,   SDMMC4,      PULL_UP,   NORMAL,   ENABLE),
    DEFAULT_PINMUX(SDMMC4_DAT2,   SDMMC4,      PULL_UP,   NORMAL,   ENABLE),
    DEFAULT_PINMUX(SDMMC4_DAT3,   SDMMC4,      PULL_UP,   NORMAL,   ENABLE),
    DEFAULT_PINMUX(SDMMC4_DAT4,   SDMMC4,      PULL_UP,   NORMAL,   ENABLE),
    DEFAULT_PINMUX(SDMMC4_DAT5,   SDMMC4,      PULL_UP,   NORMAL,   ENABLE),
    DEFAULT_PINMUX(SDMMC4_DAT6,   SDMMC4,      PULL_UP,   NORMAL,   ENABLE),
    DEFAULT_PINMUX(SDMMC4_DAT7,   SDMMC4,      PULL_UP,   NORMAL,   ENABLE),

    /* BLINK pinmux */
    DEFAULT_PINMUX(CLK_32K_OUT,   BLINK,       NORMAL,    NORMAL,   DISABLE),

    /* KBC pinmux */
    DEFAULT_PINMUX(KB_COL0,       KBC,     PULL_UP,    NORMAL,   ENABLE),
    DEFAULT_PINMUX(KB_COL1,       KBC,     PULL_UP,    NORMAL,   ENABLE),
    DEFAULT_PINMUX(KB_COL2,       KBC,     PULL_UP,    NORMAL,   ENABLE),
    DEFAULT_PINMUX(KB_ROW0,       KBC,     PULL_UP,    NORMAL,   ENABLE),
    DEFAULT_PINMUX(KB_ROW1,       KBC,     PULL_UP,    NORMAL,   ENABLE),
    DEFAULT_PINMUX(KB_ROW2,       KBC,     PULL_UP,    NORMAL,   ENABLE),

    /* UARTA pinmux */
    DEFAULT_PINMUX(KB_ROW10,      UARTA,       NORMAL,    TRISTATE, ENABLE),
    DEFAULT_PINMUX(KB_ROW9,       UARTA,       NORMAL,    NORMAL,   DISABLE),

    /* I2CPWR pinmux */
    I2C_PINMUX(PWR_I2C_SCL, I2CPWR, NORMAL, NORMAL, ENABLE, DISABLE, DISABLE),
    I2C_PINMUX(PWR_I2C_SDA, I2CPWR, NORMAL, NORMAL, ENABLE, DISABLE, DISABLE),

    /* SYSCLK pinmux */
    DEFAULT_PINMUX(SYS_CLK_REQ,   SYSCLK,      NORMAL,    NORMAL,   DISABLE),

    /* RTCK pinmux */
//    DEFAULT_PINMUX(JTAG_RTCK,     RTCK,    NORMAL,    NORMAL, ENABLE),

    /* CLK pinmux */
    DEFAULT_PINMUX(CLK_32K_IN,    CLK,     NORMAL,    TRISTATE, ENABLE),

    /* PWRON pinmux */
    DEFAULT_PINMUX(CORE_PWR_REQ,  PWRON,       NORMAL,    NORMAL,   DISABLE),

    /* CPU pinmux */
    DEFAULT_PINMUX(CPU_PWR_REQ,   CPU,     NORMAL,    NORMAL,   DISABLE),

    /* PMI pinmux */
    DEFAULT_PINMUX(PWR_INT_N,     PMI,     NORMAL,    TRISTATE, ENABLE),

    /* RESET_OUT_N pinmux */
    DEFAULT_PINMUX(RESET_OUT_N,   RESET_OUT_N, NORMAL,    NORMAL,   DISABLE),

    /* EXTPERIPH3 pinmux */
    DEFAULT_PINMUX(CLK3_OUT,      EXTPERIPH3,  NORMAL,    NORMAL,   DISABLE),

    /* I2S3 pinmux */
    DEFAULT_PINMUX(DAP4_DIN,      I2S3,    NORMAL,    TRISTATE, ENABLE),
    DEFAULT_PINMUX(DAP4_DOUT,     I2S3,    NORMAL,    NORMAL,   DISABLE),
    DEFAULT_PINMUX(DAP4_FS,       I2S3,    NORMAL,    NORMAL,   DISABLE),
    DEFAULT_PINMUX(DAP4_SCLK,     I2S3,    NORMAL,    NORMAL,   DISABLE),

    /* I2C1 pinmux */
    I2C_PINMUX(GEN1_I2C_SCL, I2C1, NORMAL, NORMAL, ENABLE, DISABLE, DISABLE),
    I2C_PINMUX(GEN1_I2C_SDA, I2C1, NORMAL, NORMAL, ENABLE, DISABLE, DISABLE),

    /* UARTB pinmux */
    DEFAULT_PINMUX(UART2_CTS_N,   UARTB,       NORMAL,    TRISTATE, ENABLE),
    DEFAULT_PINMUX(UART2_RTS_N,   UARTB,       NORMAL,    NORMAL,   DISABLE),

    /* IRDA pinmux */
    DEFAULT_PINMUX(UART2_RXD,     IRDA,    NORMAL,    TRISTATE, ENABLE),
    DEFAULT_PINMUX(UART2_TXD,     IRDA,    NORMAL,    NORMAL,   DISABLE),

    /* UARTC pinmux */
    DEFAULT_PINMUX(UART3_CTS_N,   UARTC,       NORMAL,    TRISTATE, ENABLE),
    DEFAULT_PINMUX(UART3_RTS_N,   UARTC,       NORMAL,    NORMAL,   DISABLE),
    DEFAULT_PINMUX(UART3_RXD,     UARTC,       NORMAL,    TRISTATE, ENABLE),
    DEFAULT_PINMUX(UART3_TXD,     UARTC,       NORMAL,    NORMAL,   DISABLE),

    /* OWR pinmux */
    DEFAULT_PINMUX(OWR,       OWR,     NORMAL,    NORMAL,   ENABLE),

    /* CEC pinmux */
    CEC_PINMUX(HDMI_CEC, CEC, NORMAL, NORMAL, ENABLE, DISABLE, DISABLE),

    /* I2C4 pinmux */
    DDC_PINMUX(DDC_SCL, I2C4, NORMAL, NORMAL, ENABLE, DISABLE, HIGH),
    DDC_PINMUX(DDC_SDA, I2C4, NORMAL, NORMAL, ENABLE, DISABLE, HIGH),

    /* USB pinmux */
    USB_PINMUX(USB_VBUS_EN0, USB, PULL_UP, NORMAL, ENABLE, DISABLE, ENABLE),
};

static NvPingroupConfig unused_pins_lowpower[] = {
    DEFAULT_PINMUX(CLK1_REQ,      RSVD2,    PULL_DOWN, TRISTATE, DISABLE),
    DEFAULT_PINMUX(USB_VBUS_EN1,  RSVD1,    PULL_DOWN, TRISTATE, DISABLE),
};

#endif

static NvPingroupConfig dalmore_pinmux_avp[] = {
    /* UART D : DEBUG */
    DEFAULT_PINMUX(GMI_A16,     UARTD,       NORMAL,    NORMAL,     DISABLE),
    DEFAULT_PINMUX(GMI_A17,     UARTD,       NORMAL,    NORMAL,     ENABLE),
    DEFAULT_PINMUX(GMI_A18,     UARTD,       NORMAL,    NORMAL,     ENABLE),
    DEFAULT_PINMUX(GMI_A19,     UARTD,       NORMAL,    NORMAL,     DISABLE),
    /* I2C1 pinmux */
    I2C_PINMUX(GEN1_I2C_SCL, I2C1, NORMAL, NORMAL, ENABLE, DISABLE, DISABLE),
    I2C_PINMUX(GEN1_I2C_SDA, I2C1, NORMAL, NORMAL, ENABLE, DISABLE, DISABLE),
    /* Power I2C pinmux */
    I2C_PINMUX(PWR_I2C_SCL,     I2CPWR,     NORMAL, NORMAL, ENABLE,  DISABLE,    ENABLE),
    I2C_PINMUX(PWR_I2C_SDA,     I2CPWR,     NORMAL, NORMAL, ENABLE,  DISABLE,    ENABLE),
};

NvError NvOdmPinmuxInit(NvU32 BoardId)
{
    NvError err = 0;

    err = NvPinmuxConfigTable(dalmore_pinmux_avp, NV_ARRAY_SIZE(dalmore_pinmux_avp));
    NV_CHECK_PINMUX_ERROR(err);
#if AVP_PINMUX == 0
    err = NvPinmuxConfigTable(dalmore_pinmux_common, NV_ARRAY_SIZE(dalmore_pinmux_common));
    NV_CHECK_PINMUX_ERROR(err);

    err = NvPinmuxDriveConfigTable(dalmore_drive_pinmux,
       NV_ARRAY_SIZE(dalmore_drive_pinmux));
    NV_CHECK_PINMUX_ERROR(err);
    err = NvPinmuxConfigTable(unused_pins_lowpower,
    NV_ARRAY_SIZE(unused_pins_lowpower));
    NV_CHECK_PINMUX_ERROR(err);
#endif

fail:
    return err;
}

NvError NvOdmSdmmc3UartPinmuxInit(void)
{
    return NvSuccess;
}
