LOCAL_PATH:= $(call my-dir)

include $(NVIDIA_DEFAULTS)

ifeq ($(NV_MOBILE_DGPU),1)

#
# nvidia.ko (Resman Kernel Module)
#
include $(NVIDIA_DEFAULTS)

LOCAL_MODULE := nvidia.ko
LOCAL_MODULE_PATH := $(TARGET_OUT_DATA)/nvidia/dgpu/debug
LOCAL_STRIP_MODULE := false

ifdef RESMAN_TOP
  LOCAL_NVIDIA_NVMAKE_OVERRIDE_TOP := $(RESMAN_TOP)
endif

ifeq ($(TARGET_BUILD_TYPE),debug)
LOCAL_NVIDIA_NVMAKE_OVERRIDE_BUILD_TYPE := develop
endif

LOCAL_NVIDIA_NVMAKE_OVERRIDE_TARGET_OS := Linux
LOCAL_NVIDIA_NVMAKE_OVERRIDE_TARGET_ABI := gnueabi
LOCAL_NVIDIA_NVMAKE_OVERRIDE_MODULE_PRIVATE_PATH := kernel-interface
LOCAL_NVIDIA_NVMAKE_TREE := drv
LOCAL_NVIDIA_NVMAKE_BUILD_DIR := drivers/resman
LOCAL_NVIDIA_NVMAKE_ARGS := NV_MOBILE_DGPU=$(NV_MOBILE_DGPU)

ifeq ($(ONE_SHOT_MAKEFILE),)
  LOCAL_ADDITIONAL_DEPENDENCIES += $(BUILT_KERNEL_TARGET)
endif

include $(NVIDIA_NVMAKE_EXECUTABLE)

endif
