/*
* Copyright (c) 2008-2012, NVIDIA CORPORATION.  All rights reserved.
* 
* NVIDIA Corporation and its licensors retain all intellectual property
* and proprietary rights in and to this software and related documentation
* and any modifications thereto.  Any use, reproduction, disclosure or
* distribution of this software and related documentation without an express
* license agreement from NVIDIA Corporation is strictly prohibited.
*/
#ifndef SENSOR_BAYER_CAMERA_CONFIG_H
#define SENSOR_BAYER_CAMERA_CONFIG_H
#if defined(__cplusplus)
extern "C"
{
#endif
// GENERATED FILE - DO NOT MODIFY!
static const char *pSensorCalibrationData = {
	"##\n"
	"## Autocalibration\n"
	"## Sensor  :   sensor name \n"
	"## Size    :   (width, height)\n"
	"## Version :   version number \n"
	"## Generated : time to generate this file \n"
	"## \n"
	"\n"
	"# Notes for this calibration run\n"
	"## global configurations\n"
	"##\n"
	"global.configType = 1;\n"
	"global.configVersion = 0x100;\n"
	"\n"
	"## isp functionality attributes\n"
	"## - Some blocks have detailed control entries below.\n"
	"## - Turning a block's attribute to FALSE will cause corresponding control entries to be ignored. \n"
	"##\n"
	"ap15Function.opticalBlack = TRUE;\n"
	"ap15Function.deknee = FALSE;\n"
	"ap15Function.lensShading = TRUE;\n"
	"ap15Function.badPixel = TRUE;\n"
	"ap15Function.noiseControl1 = TRUE;\n"
	"ap15Function.demosaic = TRUE;\n"
	"ap15Function.programmableDemosaic = FALSE;\n"
	"ap15Function.colorArtifactReduction = TRUE;\n"
	"ap15Function.noiseControl2 = FALSE;\n"
	"ap15Function.colorCorrection = TRUE;\n"
	"ap15Function.edgeEnhance = TRUE;\n"
	"ap15Function.gammaCorrection = TRUE;\n"
	"\n"
	"## deknee\n"
	"## - 16 segments for each color {R/Gr/Gb/B}\n"
	"##   Line definitions must be provided in ascending order (of input range).\n"
	"##   -- arg format: {inputStart,outPutStart,slope}\n"
	"##   -- inputStart/outputStart is integer value in [0,1023]\n"
	"##   -- slope in format U2.10\n"
	"##   First segment's input start must be 0.\n"
	"##\n"
	"deknee.curveR[0]   = { 0,   0,   1.0 };\n"
	"deknee.curveR[1]   = { 67,  67,  1.0 };\n"
	"deknee.curveR[2]   = { 134, 134, 1.0 };\n"
	"deknee.curveR[3]   = { 201, 201, 1.0 };\n"
	"deknee.curveR[4]   = { 268, 268, 1.0 };\n"
	"deknee.curveR[5]   = { 335, 335, 1.0 };\n"
	"deknee.curveR[6]   = { 402, 402, 1.0 };\n"
	"deknee.curveR[7]   = { 469, 469, 1.0 };\n"
	"deknee.curveR[8]   = { 536, 536, 1.0 };\n"
	"deknee.curveR[9]   = { 603, 603, 1.0 };\n"
	"deknee.curveR[10]  = { 670, 670, 1.0 };\n"
	"deknee.curveR[11]  = { 737, 737, 1.0 };\n"
	"deknee.curveR[12]  = { 804, 804, 1.0 };\n"
	"deknee.curveR[13]  = { 871, 871, 1.0 };\n"
	"deknee.curveR[14]  = { 938, 938, 1.0 };\n"
	"deknee.curveR[15]  = { 1005,1005,1.0 };\n"
	"deknee.curveGR[0]  = { 0,   0,   1.0 };\n"
	"deknee.curveGR[1]  = { 67,  67,  1.0 };\n"
	"deknee.curveGR[2]  = { 134, 134, 1.0 };\n"
	"deknee.curveGR[3]  = { 201, 201, 1.0 };\n"
	"deknee.curveGR[4]  = { 268, 268, 1.0 };\n"
	"deknee.curveGR[5]  = { 335, 335, 1.0 };\n"
	"deknee.curveGR[6]  = { 402, 402, 1.0 };\n"
	"deknee.curveGR[7]  = { 469, 469, 1.0 };\n"
	"deknee.curveGR[8]  = { 536, 536, 1.0 };\n"
	"deknee.curveGR[9]  = { 603, 603, 1.0 };\n"
	"deknee.curveGR[10] = { 670, 670, 1.0 };\n"
	"deknee.curveGR[11] = { 737, 737, 1.0 };\n"
	"deknee.curveGR[12] = { 804, 804, 1.0 };\n"
	"deknee.curveGR[13] = { 871, 871, 1.0 };\n"
	"deknee.curveGR[14] = { 938, 938, 1.0 };\n"
	"deknee.curveGR[15] = { 1005,1005,1.0 };\n"
	"deknee.curveGB[0]  = { 0,   0,   1.0 };\n"
	"deknee.curveGB[1]  = { 67,  67,  1.0 };\n"
	"deknee.curveGB[2]  = { 134, 134, 1.0 };\n"
	"deknee.curveGB[3]  = { 201, 201, 1.0 };\n"
	"deknee.curveGB[4]  = { 268, 268, 1.0 };\n"
	"deknee.curveGB[5]  = { 335, 335, 1.0 };\n"
	"deknee.curveGB[6]  = { 402, 402, 1.0 };\n"
	"deknee.curveGB[7]  = { 469, 469, 1.0 };\n"
	"deknee.curveGB[8]  = { 536, 536, 1.0 };\n"
	"deknee.curveGB[9]  = { 603, 603, 1.0 };\n"
	"deknee.curveGB[10] = { 670, 670, 1.0 };\n"
	"deknee.curveGB[11] = { 737, 737, 1.0 };\n"
	"deknee.curveGB[12] = { 804, 804, 1.0 };\n"
	"deknee.curveGB[13] = { 871, 871, 1.0 };\n"
	"deknee.curveGB[14] = { 938, 938, 1.0 };\n"
	"deknee.curveGB[15] = { 1005,1005,1.0 };\n"
	"deknee.curveB[0]   = { 0,   0,   1.0 };\n"
	"deknee.curveB[1]   = { 67,  67,  1.0 };\n"
	"deknee.curveB[2]   = { 134, 134, 1.0 };\n"
	"deknee.curveB[3]   = { 201, 201, 1.0 };\n"
	"deknee.curveB[4]   = { 268, 268, 1.0 };\n"
	"deknee.curveB[5]   = { 335, 335, 1.0 };\n"
	"deknee.curveB[6]   = { 402, 402, 1.0 };\n"
	"deknee.curveB[7]   = { 469, 469, 1.0 };\n"
	"deknee.curveB[8]   = { 536, 536, 1.0 };\n"
	"deknee.curveB[9]   = { 603, 603, 1.0 };\n"
	"deknee.curveB[10]  = { 670, 670, 1.0 };\n"
	"deknee.curveB[11]  = { 737, 737, 1.0 };\n"
	"deknee.curveB[12]  = { 804, 804, 1.0 };\n"
	"deknee.curveB[13]  = { 871, 871, 1.0 };\n"
	"deknee.curveB[14]  = { 938, 938, 1.0 };\n"
	"deknee.curveB[15]  = { 1005,1005,1.0 };\n"
	"\n"
	"## bad pixel concealment\n"
	"##\n"
	"## If a pixel value is highly deviated from its surrounding pixels, the pixel is considered\n"
	"## as a bad pixel.  The deviation is defined in terms of the percentage of the average value\n"
	"## of the pixel surrounding.  Two ratio coefficients are used: if the pixel is at flat area,\n"
	"## LT_COEF is used, otherwise if it's at edge region, UT_COEF is used.\n"
	"## If the average of pixel surround is lower than BP_DARK, it's considered at shadow region,\n"
	"## and BP_DARK instead of average value will be used to calculate deviation threshold.\n"
	"##\n"
	"## - darkLevel in U10.0\n"
	"## - upperThreshold: U1.3 ratio for Upper-threshold\n"
	"## - lowerThreshold: U1.3 ratio for Lower-threshold\n"
	"##\n"
	"badPixel.darkLevel = 0;\n"
	"badPixel.upperThreshold = 1.0;\n"
	"badPixel.lowerThreshold = 0.125;\n"
	"\n"
	"## edge enhancement\n"
	"##\n"
	"## Edge enhancement is done by (1) extracting high frequency component (HF) of the pixel,\n"
	"## (2) amplifying the HF if the extracted value is \"large\" (i.e., coring), and\n"
	"## (3) adding the amplified HF back to the Y channel of the pixel.\n"
	"##\n"
	"## - gCoreLimit: U6.0, specifies the minimum coring level.  The coring level increases when pixel surround's brightness level goes up\n"
	"## - gCoreScale: Scaling factor range of GCORELIMIT. 0 = range [1,4.5], 1 = range [1,8.5], 2 = range [1,16.5], 3 = range [1,32.5].\n"
	"##   0 = CORE4\n"
	"##   1 = CORE8\n"
	"##   2 = CORE16\n"
	"##   3 = CORE32\n"
	"## 'gCoreScale' specifies the influence of the brightness level to the coring level.\n"
	"## The higher the 'gCoreScale' is, the larger the coring level grows under the same brightness\n"
	"##\n"
	"## - enhCoef: Gain factor of edge enhancement Multiply this value to the edge signal.\n"
	"##            In U2.3; combined with a posible fixed gain value of 1 or 4, can go up to 4*3.875=15.5.\n"
	"##\n"
	"##\n"
	"edgeEnhance.enhCoef = 1.75;\n"
	"edgeEnhance.gCoreScale = 32;\n"
	"edgeEnhance.gCoreLimit = 8;\n"
	"\n"
	"## ae control\n"
	"##\n"
	"## - sensor gain value corresponding to ISO100\n"
	"## - sensor gain adjustments\n"
	"## - noise reduction table\n"
	"##   -- column-wise is higher lux to low lux;\n"
	"##   -- row-wise is small sensor gain to larger gain value\n"
	"##\n"
	"ae.noiseReduction[0] = { 3, 3, 3, 3, 3, 4, 4 };\n"
	"ae.noiseReduction[1] = { 3, 3, 3, 3, 3, 4, 4 };\n"
	"ae.noiseReduction[2] = { 3, 3, 3, 3, 4, 4, 4 };\n"
	"ae.noiseReduction[3] = { 3, 3, 3, 4, 4, 4, 4 };\n"
	"\n"
	"## optical black\n"
	"## - valid value for OB adjustments are integer value in [-1024,1023]\n"
	"##\n"
	"opticalBlack.mode = 0;\n"
	"opticalBlack.manualBiasR =  42;\n"
	"opticalBlack.manualBiasGR = 42;\n"
	"opticalBlack.manualBiasGB = 42;\n"
	"opticalBlack.manualBiasB =  42;\n"
	"\n"
	"\n"
	"\n"
	"# Lens shading data\n"
	"lensShading.leftPatchWidth = 128;\n"
	"lensShading.centerPatchWidth  = 128;\n"
	"## lensShading.rightPatchWidth   = 128; \n"
	"lensShading.topPatchHeight = 128;\n"
	"lensShading.middlePatchHeight = 128;\n"
	"## lensShading.bottomPatchHeight = 128; \n"
	"lensShading.leftPatchDeltaUMSB   = 0x0;\n"
	"lensShading.leftPatchDeltaULSB   = 0x10000000;\n"
	"lensShading.centerPatchDeltaUMSB = 0x0;\n"
	"lensShading.centerPatchDeltaULSB = 0x10000000;\n"
	"lensShading.rightPatchDeltaUMSB  = 0x0;\n"
	"lensShading.rightPatchDeltaULSB  = 0x10000000;\n"
	"lensShading.topPatchDeltaVMSB    = 0x0;\n"
	"lensShading.topPatchDeltaVLSB    = 0x10000000;\n"
	"lensShading.middlePatchDeltaVMSB = 0x0;\n"
	"lensShading.middlePatchDeltaVLSB = 0x10000000;\n"
	"lensShading.bottomPatchDeltaVMSB = 0x0;\n"
	"lensShading.bottomPatchDeltaVLSB = 0x10000000;\n"
	"lensShading.controlPointR[0][0]  = 1;\n"
	"lensShading.controlPointGR[0][0] = 1;\n"
	"lensShading.controlPointGB[0][0] = 1;\n"
	"lensShading.controlPointB[0][0]  = 1;\n"
	"lensShading.controlPointR[1][0]  = 1;\n"
	"lensShading.controlPointGR[1][0] = 1;\n"
	"lensShading.controlPointGB[1][0] = 1;\n"
	"lensShading.controlPointB[1][0]  = 1;\n"
	"lensShading.controlPointR[2][0]  = 1;\n"
	"lensShading.controlPointGR[2][0] = 1;\n"
	"lensShading.controlPointGB[2][0] = 1;\n"
	"lensShading.controlPointB[2][0]  = 1;\n"
	"lensShading.controlPointR[3][0]  = 1;\n"
	"lensShading.controlPointGR[3][0] = 1;\n"
	"lensShading.controlPointGB[3][0] = 1;\n"
	"lensShading.controlPointB[3][0]  = 1;\n"
	"lensShading.controlPointR[4][0]  = 1;\n"
	"lensShading.controlPointGR[4][0] = 1;\n"
	"lensShading.controlPointGB[4][0] = 1;\n"
	"lensShading.controlPointB[4][0]  = 1;\n"
	"lensShading.controlPointR[5][0]  = 1;\n"
	"lensShading.controlPointGR[5][0] = 1;\n"
	"lensShading.controlPointGB[5][0] = 1;\n"
	"lensShading.controlPointB[5][0]  = 1;\n"
	"lensShading.controlPointR[6][0]  = 1;\n"
	"lensShading.controlPointGR[6][0] = 1;\n"
	"lensShading.controlPointGB[6][0] = 1;\n"
	"lensShading.controlPointB[6][0]  = 1;\n"
	"lensShading.controlPointR[7][0]  = 1;\n"
	"lensShading.controlPointGR[7][0] = 1;\n"
	"lensShading.controlPointGB[7][0] = 1;\n"
	"lensShading.controlPointB[7][0]  = 1;\n"
	"lensShading.controlPointR[8][0]  = 1;\n"
	"lensShading.controlPointGR[8][0] = 1;\n"
	"lensShading.controlPointGB[8][0] = 1;\n"
	"lensShading.controlPointB[8][0]  = 1;\n"
	"lensShading.controlPointR[9][0]  = 1;\n"
	"lensShading.controlPointGR[9][0] = 1;\n"
	"lensShading.controlPointGB[9][0] = 1;\n"
	"lensShading.controlPointB[9][0]  = 1;\n"
	"lensShading.controlPointR[0][1]  = 1;\n"
	"lensShading.controlPointGR[0][1] = 1;\n"
	"lensShading.controlPointGB[0][1] = 1;\n"
	"lensShading.controlPointB[0][1]  = 1;\n"
	"lensShading.controlPointR[1][1]  = 1;\n"
	"lensShading.controlPointGR[1][1] = 1;\n"
	"lensShading.controlPointGB[1][1] = 1;\n"
	"lensShading.controlPointB[1][1]  = 1;\n"
	"lensShading.controlPointR[2][1]  = 1;\n"
	"lensShading.controlPointGR[2][1] = 1;\n"
	"lensShading.controlPointGB[2][1] = 1;\n"
	"lensShading.controlPointB[2][1]  = 1;\n"
	"lensShading.controlPointR[3][1]  = 1;\n"
	"lensShading.controlPointGR[3][1] = 1;\n"
	"lensShading.controlPointGB[3][1] = 1;\n"
	"lensShading.controlPointB[3][1]  = 1;\n"
	"lensShading.controlPointR[4][1]  = 1;\n"
	"lensShading.controlPointGR[4][1] = 1;\n"
	"lensShading.controlPointGB[4][1] = 1;\n"
	"lensShading.controlPointB[4][1]  = 1;\n"
	"lensShading.controlPointR[5][1]  = 1;\n"
	"lensShading.controlPointGR[5][1] = 1;\n"
	"lensShading.controlPointGB[5][1] = 1;\n"
	"lensShading.controlPointB[5][1]  = 1;\n"
	"lensShading.controlPointR[6][1]  = 1;\n"
	"lensShading.controlPointGR[6][1] = 1;\n"
	"lensShading.controlPointGB[6][1] = 1;\n"
	"lensShading.controlPointB[6][1]  = 1;\n"
	"lensShading.controlPointR[7][1]  = 1;\n"
	"lensShading.controlPointGR[7][1] = 1;\n"
	"lensShading.controlPointGB[7][1] = 1;\n"
	"lensShading.controlPointB[7][1]  = 1;\n"
	"lensShading.controlPointR[8][1]  = 1;\n"
	"lensShading.controlPointGR[8][1] = 1;\n"
	"lensShading.controlPointGB[8][1] = 1;\n"
	"lensShading.controlPointB[8][1]  = 1;\n"
	"lensShading.controlPointR[9][1]  = 1;\n"
	"lensShading.controlPointGR[9][1] = 1;\n"
	"lensShading.controlPointGB[9][1] = 1;\n"
	"lensShading.controlPointB[9][1]  = 1;\n"
	"lensShading.controlPointR[0][2]  = 1;\n"
	"lensShading.controlPointGR[0][2] = 1;\n"
	"lensShading.controlPointGB[0][2] = 1;\n"
	"lensShading.controlPointB[0][2]  = 1;\n"
	"lensShading.controlPointR[1][2]  = 1;\n"
	"lensShading.controlPointGR[1][2] = 1;\n"
	"lensShading.controlPointGB[1][2] = 1;\n"
	"lensShading.controlPointB[1][2]  = 1;\n"
	"lensShading.controlPointR[2][2]  = 1;\n"
	"lensShading.controlPointGR[2][2] = 1;\n"
	"lensShading.controlPointGB[2][2] = 1;\n"
	"lensShading.controlPointB[2][2]  = 1;\n"
	"lensShading.controlPointR[3][2]  = 1;\n"
	"lensShading.controlPointGR[3][2] = 1;\n"
	"lensShading.controlPointGB[3][2] = 1;\n"
	"lensShading.controlPointB[3][2]  = 1;\n"
	"lensShading.controlPointR[4][2]  = 1;\n"
	"lensShading.controlPointGR[4][2] = 1;\n"
	"lensShading.controlPointGB[4][2] = 1;\n"
	"lensShading.controlPointB[4][2]  = 1;\n"
	"lensShading.controlPointR[5][2]  = 1;\n"
	"lensShading.controlPointGR[5][2] = 1;\n"
	"lensShading.controlPointGB[5][2] = 1;\n"
	"lensShading.controlPointB[5][2]  = 1;\n"
	"lensShading.controlPointR[6][2]  = 1;\n"
	"lensShading.controlPointGR[6][2] = 1;\n"
	"lensShading.controlPointGB[6][2] = 1;\n"
	"lensShading.controlPointB[6][2]  = 1;\n"
	"lensShading.controlPointR[7][2]  = 1;\n"
	"lensShading.controlPointGR[7][2] = 1;\n"
	"lensShading.controlPointGB[7][2] = 1;\n"
	"lensShading.controlPointB[7][2]  = 1;\n"
	"lensShading.controlPointR[8][2]  = 1;\n"
	"lensShading.controlPointGR[8][2] = 1;\n"
	"lensShading.controlPointGB[8][2] = 1;\n"
	"lensShading.controlPointB[8][2]  = 1;\n"
	"lensShading.controlPointR[9][2]  = 1;\n"
	"lensShading.controlPointGR[9][2] = 1;\n"
	"lensShading.controlPointGB[9][2] = 1;\n"
	"lensShading.controlPointB[9][2]  = 1;\n"
	"lensShading.controlPointR[0][3]  = 1;\n"
	"lensShading.controlPointGR[0][3] = 1;\n"
	"lensShading.controlPointGB[0][3] = 1;\n"
	"lensShading.controlPointB[0][3]  = 1;\n"
	"lensShading.controlPointR[1][3]  = 1;\n"
	"lensShading.controlPointGR[1][3] = 1;\n"
	"lensShading.controlPointGB[1][3] = 1;\n"
	"lensShading.controlPointB[1][3]  = 1;\n"
	"lensShading.controlPointR[2][3]  = 1;\n"
	"lensShading.controlPointGR[2][3] = 1;\n"
	"lensShading.controlPointGB[2][3] = 1;\n"
	"lensShading.controlPointB[2][3]  = 1;\n"
	"lensShading.controlPointR[3][3]  = 1;\n"
	"lensShading.controlPointGR[3][3] = 1;\n"
	"lensShading.controlPointGB[3][3] = 1;\n"
	"lensShading.controlPointB[3][3]  = 1;\n"
	"lensShading.controlPointR[4][3]  = 1;\n"
	"lensShading.controlPointGR[4][3] = 1;\n"
	"lensShading.controlPointGB[4][3] = 1;\n"
	"lensShading.controlPointB[4][3]  = 1;\n"
	"lensShading.controlPointR[5][3]  = 1;\n"
	"lensShading.controlPointGR[5][3] = 1;\n"
	"lensShading.controlPointGB[5][3] = 1;\n"
	"lensShading.controlPointB[5][3]  = 1;\n"
	"lensShading.controlPointR[6][3]  = 1;\n"
	"lensShading.controlPointGR[6][3] = 1;\n"
	"lensShading.controlPointGB[6][3] = 1;\n"
	"lensShading.controlPointB[6][3]  = 1;\n"
	"lensShading.controlPointR[7][3]  = 1;\n"
	"lensShading.controlPointGR[7][3] = 1;\n"
	"lensShading.controlPointGB[7][3] = 1;\n"
	"lensShading.controlPointB[7][3]  = 1;\n"
	"lensShading.controlPointR[8][3]  = 1;\n"
	"lensShading.controlPointGR[8][3] = 1;\n"
	"lensShading.controlPointGB[8][3] = 1;\n"
	"lensShading.controlPointB[8][3]  = 1;\n"
	"lensShading.controlPointR[9][3]  = 1;\n"
	"lensShading.controlPointGR[9][3] = 1;\n"
	"lensShading.controlPointGB[9][3] = 1;\n"
	"lensShading.controlPointB[9][3]  = 1;\n"
	"lensShading.controlPointR[0][4]  = 1;\n"
	"lensShading.controlPointGR[0][4] = 1;\n"
	"lensShading.controlPointGB[0][4] = 1;\n"
	"lensShading.controlPointB[0][4]  = 1;\n"
	"lensShading.controlPointR[1][4]  = 1;\n"
	"lensShading.controlPointGR[1][4] = 1;\n"
	"lensShading.controlPointGB[1][4] = 1;\n"
	"lensShading.controlPointB[1][4]  = 1;\n"
	"lensShading.controlPointR[2][4]  = 1;\n"
	"lensShading.controlPointGR[2][4] = 1;\n"
	"lensShading.controlPointGB[2][4] = 1;\n"
	"lensShading.controlPointB[2][4]  = 1;\n"
	"lensShading.controlPointR[3][4]  = 1;\n"
	"lensShading.controlPointGR[3][4] = 1;\n"
	"lensShading.controlPointGB[3][4] = 1;\n"
	"lensShading.controlPointB[3][4]  = 1;\n"
	"lensShading.controlPointR[4][4]  = 1;\n"
	"lensShading.controlPointGR[4][4] = 1;\n"
	"lensShading.controlPointGB[4][4] = 1;\n"
	"lensShading.controlPointB[4][4]  = 1;\n"
	"lensShading.controlPointR[5][4]  = 1;\n"
	"lensShading.controlPointGR[5][4] = 1;\n"
	"lensShading.controlPointGB[5][4] = 1;\n"
	"lensShading.controlPointB[5][4]  = 1;\n"
	"lensShading.controlPointR[6][4]  = 1;\n"
	"lensShading.controlPointGR[6][4] = 1;\n"
	"lensShading.controlPointGB[6][4] = 1;\n"
	"lensShading.controlPointB[6][4]  = 1;\n"
	"lensShading.controlPointR[7][4]  = 1;\n"
	"lensShading.controlPointGR[7][4] = 1;\n"
	"lensShading.controlPointGB[7][4] = 1;\n"
	"lensShading.controlPointB[7][4]  = 1;\n"
	"lensShading.controlPointR[8][4]  = 1;\n"
	"lensShading.controlPointGR[8][4] = 1;\n"
	"lensShading.controlPointGB[8][4] = 1;\n"
	"lensShading.controlPointB[8][4]  = 1;\n"
	"lensShading.controlPointR[9][4]  = 1;\n"
	"lensShading.controlPointGR[9][4] = 1;\n"
	"lensShading.controlPointGB[9][4] = 1;\n"
	"lensShading.controlPointB[9][4]  = 1;\n"
	"lensShading.controlPointR[0][5]  = 1;\n"
	"lensShading.controlPointGR[0][5] = 1;\n"
	"lensShading.controlPointGB[0][5] = 1;\n"
	"lensShading.controlPointB[0][5]  = 1;\n"
	"lensShading.controlPointR[1][5]  = 1;\n"
	"lensShading.controlPointGR[1][5] = 1;\n"
	"lensShading.controlPointGB[1][5] = 1;\n"
	"lensShading.controlPointB[1][5]  = 1;\n"
	"lensShading.controlPointR[2][5]  = 1;\n"
	"lensShading.controlPointGR[2][5] = 1;\n"
	"lensShading.controlPointGB[2][5] = 1;\n"
	"lensShading.controlPointB[2][5]  = 1;\n"
	"lensShading.controlPointR[3][5]  = 1;\n"
	"lensShading.controlPointGR[3][5] = 1;\n"
	"lensShading.controlPointGB[3][5] = 1;\n"
	"lensShading.controlPointB[3][5]  = 1;\n"
	"lensShading.controlPointR[4][5]  = 1;\n"
	"lensShading.controlPointGR[4][5] = 1;\n"
	"lensShading.controlPointGB[4][5] = 1;\n"
	"lensShading.controlPointB[4][5]  = 1;\n"
	"lensShading.controlPointR[5][5]  = 1;\n"
	"lensShading.controlPointGR[5][5] = 1;\n"
	"lensShading.controlPointGB[5][5] = 1;\n"
	"lensShading.controlPointB[5][5]  = 1;\n"
	"lensShading.controlPointR[6][5]  = 1;\n"
	"lensShading.controlPointGR[6][5] = 1;\n"
	"lensShading.controlPointGB[6][5] = 1;\n"
	"lensShading.controlPointB[6][5]  = 1;\n"
	"lensShading.controlPointR[7][5]  = 1;\n"
	"lensShading.controlPointGR[7][5] = 1;\n"
	"lensShading.controlPointGB[7][5] = 1;\n"
	"lensShading.controlPointB[7][5]  = 1;\n"
	"lensShading.controlPointR[8][5]  = 1;\n"
	"lensShading.controlPointGR[8][5] = 1;\n"
	"lensShading.controlPointGB[8][5] = 1;\n"
	"lensShading.controlPointB[8][5]  = 1;\n"
	"lensShading.controlPointR[9][5]  = 1;\n"
	"lensShading.controlPointGR[9][5] = 1;\n"
	"lensShading.controlPointGB[9][5] = 1;\n"
	"lensShading.controlPointB[9][5]  = 1;\n"
	"lensShading.controlPointR[0][6]  = 1;\n"
	"lensShading.controlPointGR[0][6] = 1;\n"
	"lensShading.controlPointGB[0][6] = 1;\n"
	"lensShading.controlPointB[0][6]  = 1;\n"
	"lensShading.controlPointR[1][6]  = 1;\n"
	"lensShading.controlPointGR[1][6] = 1;\n"
	"lensShading.controlPointGB[1][6] = 1;\n"
	"lensShading.controlPointB[1][6]  = 1;\n"
	"lensShading.controlPointR[2][6]  = 1;\n"
	"lensShading.controlPointGR[2][6] = 1;\n"
	"lensShading.controlPointGB[2][6] = 1;\n"
	"lensShading.controlPointB[2][6]  = 1;\n"
	"lensShading.controlPointR[3][6]  = 1;\n"
	"lensShading.controlPointGR[3][6] = 1;\n"
	"lensShading.controlPointGB[3][6] = 1;\n"
	"lensShading.controlPointB[3][6]  = 1;\n"
	"lensShading.controlPointR[4][6]  = 1;\n"
	"lensShading.controlPointGR[4][6] = 1;\n"
	"lensShading.controlPointGB[4][6] = 1;\n"
	"lensShading.controlPointB[4][6]  = 1;\n"
	"lensShading.controlPointR[5][6]  = 1;\n"
	"lensShading.controlPointGR[5][6] = 1;\n"
	"lensShading.controlPointGB[5][6] = 1;\n"
	"lensShading.controlPointB[5][6]  = 1;\n"
	"lensShading.controlPointR[6][6]  = 1;\n"
	"lensShading.controlPointGR[6][6] = 1;\n"
	"lensShading.controlPointGB[6][6] = 1;\n"
	"lensShading.controlPointB[6][6]  = 1;\n"
	"lensShading.controlPointR[7][6]  = 1;\n"
	"lensShading.controlPointGR[7][6] = 1;\n"
	"lensShading.controlPointGB[7][6] = 1;\n"
	"lensShading.controlPointB[7][6]  = 1;\n"
	"lensShading.controlPointR[8][6]  = 1;\n"
	"lensShading.controlPointGR[8][6] = 1;\n"
	"lensShading.controlPointGB[8][6] = 1;\n"
	"lensShading.controlPointB[8][6]  = 1;\n"
	"lensShading.controlPointR[9][6]  = 1;\n"
	"lensShading.controlPointGR[9][6] = 1;\n"
	"lensShading.controlPointGB[9][6] = 1;\n"
	"lensShading.controlPointB[9][6]  = 1;\n"
	"lensShading.controlPointR[0][7]  = 1;\n"
	"lensShading.controlPointGR[0][7] = 1;\n"
	"lensShading.controlPointGB[0][7] = 1;\n"
	"lensShading.controlPointB[0][7]  = 1;\n"
	"lensShading.controlPointR[1][7]  = 1;\n"
	"lensShading.controlPointGR[1][7] = 1;\n"
	"lensShading.controlPointGB[1][7] = 1;\n"
	"lensShading.controlPointB[1][7]  = 1;\n"
	"lensShading.controlPointR[2][7]  = 1;\n"
	"lensShading.controlPointGR[2][7] = 1;\n"
	"lensShading.controlPointGB[2][7] = 1;\n"
	"lensShading.controlPointB[2][7]  = 1;\n"
	"lensShading.controlPointR[3][7]  = 1;\n"
	"lensShading.controlPointGR[3][7] = 1;\n"
	"lensShading.controlPointGB[3][7] = 1;\n"
	"lensShading.controlPointB[3][7]  = 1;\n"
	"lensShading.controlPointR[4][7]  = 1;\n"
	"lensShading.controlPointGR[4][7] = 1;\n"
	"lensShading.controlPointGB[4][7] = 1;\n"
	"lensShading.controlPointB[4][7]  = 1;\n"
	"lensShading.controlPointR[5][7]  = 1;\n"
	"lensShading.controlPointGR[5][7] = 1;\n"
	"lensShading.controlPointGB[5][7] = 1;\n"
	"lensShading.controlPointB[5][7]  = 1;\n"
	"lensShading.controlPointR[6][7]  = 1;\n"
	"lensShading.controlPointGR[6][7] = 1;\n"
	"lensShading.controlPointGB[6][7] = 1;\n"
	"lensShading.controlPointB[6][7]  = 1;\n"
	"lensShading.controlPointR[7][7]  = 1;\n"
	"lensShading.controlPointGR[7][7] = 1;\n"
	"lensShading.controlPointGB[7][7] = 1;\n"
	"lensShading.controlPointB[7][7]  = 1;\n"
	"lensShading.controlPointR[8][7]  = 1;\n"
	"lensShading.controlPointGR[8][7] = 1;\n"
	"lensShading.controlPointGB[8][7] = 1;\n"
	"lensShading.controlPointB[8][7]  = 1;\n"
	"lensShading.controlPointR[9][7]  = 1;\n"
	"lensShading.controlPointGR[9][7] = 1;\n"
	"lensShading.controlPointGB[9][7] = 1;\n"
	"lensShading.controlPointB[9][7]  = 1;\n"
	"lensShading.controlPointR[0][8]  = 1;\n"
	"lensShading.controlPointGR[0][8] = 1;\n"
	"lensShading.controlPointGB[0][8] = 1;\n"
	"lensShading.controlPointB[0][8]  = 1;\n"
	"lensShading.controlPointR[1][8]  = 1;\n"
	"lensShading.controlPointGR[1][8] = 1;\n"
	"lensShading.controlPointGB[1][8] = 1;\n"
	"lensShading.controlPointB[1][8]  = 1;\n"
	"lensShading.controlPointR[2][8]  = 1;\n"
	"lensShading.controlPointGR[2][8] = 1;\n"
	"lensShading.controlPointGB[2][8] = 1;\n"
	"lensShading.controlPointB[2][8]  = 1;\n"
	"lensShading.controlPointR[3][8]  = 1;\n"
	"lensShading.controlPointGR[3][8] = 1;\n"
	"lensShading.controlPointGB[3][8] = 1;\n"
	"lensShading.controlPointB[3][8]  = 1;\n"
	"lensShading.controlPointR[4][8]  = 1;\n"
	"lensShading.controlPointGR[4][8] = 1;\n"
	"lensShading.controlPointGB[4][8] = 1;\n"
	"lensShading.controlPointB[4][8]  = 1;\n"
	"lensShading.controlPointR[5][8]  = 1;\n"
	"lensShading.controlPointGR[5][8] = 1;\n"
	"lensShading.controlPointGB[5][8] = 1;\n"
	"lensShading.controlPointB[5][8]  = 1;\n"
	"lensShading.controlPointR[6][8]  = 1;\n"
	"lensShading.controlPointGR[6][8] = 1;\n"
	"lensShading.controlPointGB[6][8] = 1;\n"
	"lensShading.controlPointB[6][8]  = 1;\n"
	"lensShading.controlPointR[7][8]  = 1;\n"
	"lensShading.controlPointGR[7][8] = 1;\n"
	"lensShading.controlPointGB[7][8] = 1;\n"
	"lensShading.controlPointB[7][8]  = 1;\n"
	"lensShading.controlPointR[8][8]  = 1;\n"
	"lensShading.controlPointGR[8][8] = 1;\n"
	"lensShading.controlPointGB[8][8] = 1;\n"
	"lensShading.controlPointB[8][8]  = 1;\n"
	"lensShading.controlPointR[9][8]  = 1;\n"
	"lensShading.controlPointGR[9][8] = 1;\n"
	"lensShading.controlPointGB[9][8] = 1;\n"
	"lensShading.controlPointB[9][8]  = 1;\n"
	"lensShading.controlPointR[0][9]  = 1;\n"
	"lensShading.controlPointGR[0][9] = 1;\n"
	"lensShading.controlPointGB[0][9] = 1;\n"
	"lensShading.controlPointB[0][9]  = 1;\n"
	"lensShading.controlPointR[1][9]  = 1;\n"
	"lensShading.controlPointGR[1][9] = 1;\n"
	"lensShading.controlPointGB[1][9] = 1;\n"
	"lensShading.controlPointB[1][9]  = 1;\n"
	"lensShading.controlPointR[2][9]  = 1;\n"
	"lensShading.controlPointGR[2][9] = 1;\n"
	"lensShading.controlPointGB[2][9] = 1;\n"
	"lensShading.controlPointB[2][9]  = 1;\n"
	"lensShading.controlPointR[3][9]  = 1;\n"
	"lensShading.controlPointGR[3][9] = 1;\n"
	"lensShading.controlPointGB[3][9] = 1;\n"
	"lensShading.controlPointB[3][9]  = 1;\n"
	"lensShading.controlPointR[4][9]  = 1;\n"
	"lensShading.controlPointGR[4][9] = 1;\n"
	"lensShading.controlPointGB[4][9] = 1;\n"
	"lensShading.controlPointB[4][9]  = 1;\n"
	"lensShading.controlPointR[5][9]  = 1;\n"
	"lensShading.controlPointGR[5][9] = 1;\n"
	"lensShading.controlPointGB[5][9] = 1;\n"
	"lensShading.controlPointB[5][9]  = 1;\n"
	"lensShading.controlPointR[6][9]  = 1;\n"
	"lensShading.controlPointGR[6][9] = 1;\n"
	"lensShading.controlPointGB[6][9] = 1;\n"
	"lensShading.controlPointB[6][9]  = 1;\n"
	"lensShading.controlPointR[7][9]  = 1;\n"
	"lensShading.controlPointGR[7][9] = 1;\n"
	"lensShading.controlPointGB[7][9] = 1;\n"
	"lensShading.controlPointB[7][9]  = 1;\n"
	"lensShading.controlPointR[8][9]  = 1;\n"
	"lensShading.controlPointGR[8][9] = 1;\n"
	"lensShading.controlPointGB[8][9] = 1;\n"
	"lensShading.controlPointB[8][9]  = 1;\n"
	"lensShading.controlPointR[9][9]  = 1;\n"
	"lensShading.controlPointGR[9][9] = 1;\n"
	"lensShading.controlPointGB[9][9] = 1;\n"
	"lensShading.controlPointB[9][9]  = 1;\n"
	"\n"
	"# Calibration for the Gain, per Channel for this sensor, for optimal linear response\n"
	"ae.gainForISO100 = 1.00;          # ISO100 equates to this gain\n"
	"ae.PerChannelGainAdjustment = {1.0, 1.0, 1.0, 1.0};\n"
	"\n"
	"# Data for AWB and Color Correction\n"
	"#\n"
	"# entries for 3 X 3 color correction matrix. Row\n"
	"#   colorCorrection.srgbMatrix[0] = \n"
	"#   colorCorrection.srgbMatrix[1] \n"
	"#   colorCorrection.srgbMatrix[2]\n"
	"#\n"
	"# entries for line fitting through white point colors\n"
	"#   awb.GrayLineSlope\n"
	"#   awb.GrayLineIntercept\n"
	"#   awb.GrayLineThickness\n"
	"# \n"
	"# entries for transfer function polynomial that goes between CCT and color coordinate U \n"
	"#   awb.CCTtoU\n"
	"#   awb.UtoCCT\n"
	"#\n"
	"# entries for soft clamping function. Piece-wise line segments.\n"
	"#   awb.GrayLineSoftClampSlopeBeforeFirstPoint\n"
	"#   awb.GrayLineSoftClampSlopeAfterLastPoint\n"
	"#   awb.NumGrayLineSoftClampPoints = <n>;\n"
	"#   awb.GrayLineSoftClamp[0] = {U, U'}\n"
	"#   ...\n"
	"#   awb.GrayLineSoftClamp[n-1] = {U, U'}\n"
	"#\n"
	"#\n"
	"colorCorrection.srgbMatrix[0] = {1.0, 0.0, 0.0};\n"
	"colorCorrection.srgbMatrix[1] = {0.0, 1.0, 0.0};\n"
	"colorCorrection.srgbMatrix[2] = {0.0, 0.0, 1.0};\n"
	"awb.GrayLineSlope = -1.26813098991;\n"
	"awb.GrayLineIntercept = 2.15997525187;\n"
	"awb.GrayLineThickness = 1.0;\n"
	"awb.CCTtoU = {0.000108199278008, 0.164565613404};\n"
	"awb.UtoCCT = {8911.05417001, -1279.76149889};\n"
	"awb.GrayLineSoftClampSlopeBeforeFirstPoint = 0.0;\n"
	"awb.GrayLineSoftClampSlopeAfterLastPoint = 0.5;\n"
	"awb.NumGrayLineSoftClampPoints = 3;\n"
	"awb.GrayLineSoftClamp[0] = {0.489163447428, 0.489163447428 }; # Tungsten limit\n"
	"awb.GrayLineSoftClamp[1] = {0.867860920457, 0.867860920457 }; # Daylight limit\n"
	"awb.GrayLineSoftClamp[2] = {1.24655839349, 1.24655839349}; # Deep blue limit\n"
	"\n"
};
#if defined(__cplusplus)
}
#endif
#endif //SENSOR_BAYER_CAMERA_CONFIG_H
