/*
 * Copyright (c) 2013 NVIDIA Corporation.  All rights reserved.
 *
 * NVIDIA Corporation and its licensors retain all intellectual property
 * and proprietary rights in and to this software, related documentation
 * and any modifications thereto.  Any use, reproduction, disclosure or
 * distribution of this software and related documentation without an express
 * license agreement from NVIDIA Corporation is strictly prohibited.
 */

#ifndef INCLUDED_NVODM_IMAGER_BUILD_DATE
#define INCLUDED_NVODM_IMAGER_BUILD_DATE

#if defined(__cplusplus)
extern "C"
{
#endif

    // C file with the declaration is autogenerated by the Makefile
    // look in $(OUTDIR)/ for nvodm_imager_build_date.c
extern const char *g_BuildDate;

#if defined(__cplusplus)
}
#endif

/** @} */

#endif // INCLUDED_NVODM_IMAGER_BUILD_DATE

