/*
 * Copyright (c) 2013 NVIDIA Corporation.  All rights reserved.
 *
 * NVIDIA Corporation and its licensors retain all intellectual property
 * and proprietary rights in and to this software and related documentation
 * and any modifications thereto.  Any use, reproduction, disclosure or
 * distribution of this software and related documentation without an express
 * license agreement from NVIDIA Corporation is strictly prohibited.
 */

#ifndef ARDEV_T_SATA_H_
#define ARDEV_T_SATA_H_

// generated by manual_ref_to_h.py from dev_t_sata.ref - do not edit

//
// =~= copyright begin =~=
// Copyright 2010 NVIDIA Corp.
// =~= copyright end =~=
//

#define BASE_ADDRESS_SATA                                  0x00000000
#define SATA_PRI_CMD_0                                     0x00000000
#define SATA_PRI_CMD_0_SECURE                              0
#define SATA_PRI_CMD_0_WORD_COUNT                          1
#define SATA_PRI_CMD_0_RESET_VAL                           0x0
#define SATA_PRI_CMD_0_RESET_MASK                          0x8
#define SATA_PRI_CMD_0_SW_DEFAULT_VAL                      0x0
#define SATA_PRI_CMD_0_SW_DEFAULT_MASK                     0x8
#define SATA_PRI_CMD_0_READ_MASK                           0x8
#define SATA_PRI_CMD_0_WRITE_MASK                          0x9
#define SATA_PRI_CMD_0_BM_SS_SHIFT                          _MK_SHIFT_CONST(0)
#define SATA_PRI_CMD_0_BM_SS_FIELD                         (_MK_SHIFT_CONST(0x1) << SATA_PRI_CMD_0_BM_SS_SHIFT)
#define SATA_PRI_CMD_0_BM_SS_RANGE                         0:0
#define SATA_PRI_CMD_0_BM_SS_WOFFSET                       0
#define SATA_PRI_CMD_0_BM_SS__NOPRDCHK                     _MK_ENUM_CONST(0x00000001)
#define SATA_PRI_CMD_0_BM_SS_STOP                          _MK_ENUM_CONST(0x00000000)
#define SATA_PRI_CMD_0_BM_SS_START                         _MK_ENUM_CONST(0x00000001)
#define SATA_PRI_CMD_0_BM_RW_SHIFT                          _MK_SHIFT_CONST(3)
#define SATA_PRI_CMD_0_BM_RW_FIELD                         (_MK_SHIFT_CONST(0x1) << SATA_PRI_CMD_0_BM_RW_SHIFT)
#define SATA_PRI_CMD_0_BM_RW_RANGE                         3:3
#define SATA_PRI_CMD_0_BM_RW_WOFFSET                       0
#define SATA_PRI_CMD_0_BM_RW__NOPRDCHK                     _MK_ENUM_CONST(0x00000001)
#define SATA_PRI_CMD_0_BM_RW_READ                          _MK_ENUM_CONST(0x00000000)
#define SATA_PRI_CMD_0_BM_RW_WRITE                         _MK_ENUM_CONST(0x00000001)
#define SATA_PRI_STS_0                                     0x00000002
#define SATA_PRI_STS_0_SECURE                              0
#define SATA_PRI_STS_0_WORD_COUNT                          1
#define SATA_PRI_STS_0_RESET_VAL                           0x0
#define SATA_PRI_STS_0_RESET_MASK                          0x65
#define SATA_PRI_STS_0_SW_DEFAULT_VAL                      0x0
#define SATA_PRI_STS_0_SW_DEFAULT_MASK                     0x65
#define SATA_PRI_STS_0_READ_MASK                           0xe7
#define SATA_PRI_STS_0_WRITE_MASK                          0x64
#define SATA_PRI_STS_0_BMSATAA_SHIFT                        _MK_SHIFT_CONST(0)
#define SATA_PRI_STS_0_BMSATAA_FIELD                       (_MK_SHIFT_CONST(0x1) << SATA_PRI_STS_0_BMSATAA_SHIFT)
#define SATA_PRI_STS_0_BMSATAA_RANGE                       0:0
#define SATA_PRI_STS_0_BMSATAA_WOFFSET                     0
#define SATA_PRI_STS_0_BMSATAA__NOPRDCHK                   _MK_ENUM_CONST(0x00000001)
#define SATA_PRI_STS_0_BMSATAA_NACTV                       _MK_ENUM_CONST(0x00000000)
#define SATA_PRI_STS_0_BMSATAA_ACTV                        _MK_ENUM_CONST(0x00000001)
#define SATA_PRI_STS_0_ERR_SHIFT                            _MK_SHIFT_CONST(1)
#define SATA_PRI_STS_0_ERR_FIELD                           (_MK_SHIFT_CONST(0x1) << SATA_PRI_STS_0_ERR_SHIFT)
#define SATA_PRI_STS_0_ERR_RANGE                           1:1
#define SATA_PRI_STS_0_ERR_WOFFSET                         0
#define SATA_PRI_STS_0_ERR__NOPRDCHK                       _MK_ENUM_CONST(0x00000001)
#define SATA_PRI_STS_0_ERR_NO                              _MK_ENUM_CONST(0x00000000)
#define SATA_PRI_STS_0_ERR_YES                             _MK_ENUM_CONST(0x00000001)
#define SATA_PRI_STS_0_INTR_SHIFT                           _MK_SHIFT_CONST(2)
#define SATA_PRI_STS_0_INTR_FIELD                          (_MK_SHIFT_CONST(0x1) << SATA_PRI_STS_0_INTR_SHIFT)
#define SATA_PRI_STS_0_INTR_RANGE                          2:2
#define SATA_PRI_STS_0_INTR_WOFFSET                        0
#define SATA_PRI_STS_0_INTR__NOPRDCHK                      _MK_ENUM_CONST(0x00000001)
#define SATA_PRI_STS_0_INTR_NO                             _MK_ENUM_CONST(0x00000000)
#define SATA_PRI_STS_0_INTR_YES                            _MK_ENUM_CONST(0x00000001)
#define SATA_PRI_STS_0_INTR_CLEAR                          _MK_ENUM_CONST(0x00000001)
#define SATA_PRI_STS_0_DMA0_SHIFT                           _MK_SHIFT_CONST(5)
#define SATA_PRI_STS_0_DMA0_FIELD                          (_MK_SHIFT_CONST(0x1) << SATA_PRI_STS_0_DMA0_SHIFT)
#define SATA_PRI_STS_0_DMA0_RANGE                          5:5
#define SATA_PRI_STS_0_DMA0_WOFFSET                        0
#define SATA_PRI_STS_0_DMA0__NOPRDCHK                      _MK_ENUM_CONST(0x00000001)
#define SATA_PRI_STS_0_DMA0_NO                             _MK_ENUM_CONST(0x00000000)
#define SATA_PRI_STS_0_DMA0_YES                            _MK_ENUM_CONST(0x00000001)
#define SATA_PRI_STS_0_DMA1_SHIFT                           _MK_SHIFT_CONST(6)
#define SATA_PRI_STS_0_DMA1_FIELD                          (_MK_SHIFT_CONST(0x1) << SATA_PRI_STS_0_DMA1_SHIFT)
#define SATA_PRI_STS_0_DMA1_RANGE                          6:6
#define SATA_PRI_STS_0_DMA1_WOFFSET                        0
#define SATA_PRI_STS_0_DMA1__NOPRDCHK                      _MK_ENUM_CONST(0x00000001)
#define SATA_PRI_STS_0_DMA1_NO                             _MK_ENUM_CONST(0x00000000)
#define SATA_PRI_STS_0_DMA1_YES                            _MK_ENUM_CONST(0x00000001)
#define SATA_PRI_STS_0_SMPLX_SHIFT                          _MK_SHIFT_CONST(7)
#define SATA_PRI_STS_0_SMPLX_FIELD                         (_MK_SHIFT_CONST(0x1) << SATA_PRI_STS_0_SMPLX_SHIFT)
#define SATA_PRI_STS_0_SMPLX_RANGE                         7:7
#define SATA_PRI_STS_0_SMPLX_WOFFSET                       0
#define SATA_PRI_STS_0_SMPLX__NOPRDCHK                     _MK_ENUM_CONST(0x00000001)
#define SATA_PRI_STS_0_SMPLX_NO                            _MK_ENUM_CONST(0x00000000)
#define SATA_PRI_STS_0_SMPLX_YES                           _MK_ENUM_CONST(0x00000001)
#define SATA_PRI_PRD_ADD_0                                 0x00000004
#define SATA_PRI_PRD_ADD_0_SECURE                          0
#define SATA_PRI_PRD_ADD_0_WORD_COUNT                      1
#define SATA_PRI_PRD_ADD_0_RESET_VAL                       0x0
#define SATA_PRI_PRD_ADD_0_RESET_MASK                      0xfffffffc
#define SATA_PRI_PRD_ADD_0_SW_DEFAULT_VAL                  0x0
#define SATA_PRI_PRD_ADD_0_SW_DEFAULT_MASK                 0xfffffffc
#define SATA_PRI_PRD_ADD_0_READ_MASK                       0xfffffffc
#define SATA_PRI_PRD_ADD_0_WRITE_MASK                      0xfffffffc
#define SATA_PRI_PRD_ADD_0_DW_SHIFT                         _MK_SHIFT_CONST(2)
#define SATA_PRI_PRD_ADD_0_DW_FIELD                        (_MK_SHIFT_CONST(0x3fffffff) << SATA_PRI_PRD_ADD_0_DW_SHIFT)
#define SATA_PRI_PRD_ADD_0_DW_RANGE                        31:2
#define SATA_PRI_PRD_ADD_0_DW_WOFFSET                      0
#define SATA_PRI_PRD_ADD_0_DW__NOPRDCHK                    _MK_ENUM_CONST(0x00000001)
#define SATA_PRI_PRD_ADD_0_DW_0                            _MK_ENUM_CONST(0x00000000)
#define SATA_SEC_CMD_0                                     0x00000008
#define SATA_SEC_CMD_0_SECURE                              0
#define SATA_SEC_CMD_0_WORD_COUNT                          1
#define SATA_SEC_CMD_0_RESET_VAL                           0x0
#define SATA_SEC_CMD_0_RESET_MASK                          0x8
#define SATA_SEC_CMD_0_SW_DEFAULT_VAL                      0x0
#define SATA_SEC_CMD_0_SW_DEFAULT_MASK                     0x8
#define SATA_SEC_CMD_0_READ_MASK                           0x8
#define SATA_SEC_CMD_0_WRITE_MASK                          0x9
#define SATA_SEC_CMD_0_BM_SS_SHIFT                          _MK_SHIFT_CONST(0)
#define SATA_SEC_CMD_0_BM_SS_FIELD                         (_MK_SHIFT_CONST(0x1) << SATA_SEC_CMD_0_BM_SS_SHIFT)
#define SATA_SEC_CMD_0_BM_SS_RANGE                         0:0
#define SATA_SEC_CMD_0_BM_SS_WOFFSET                       0
#define SATA_SEC_CMD_0_BM_SS__NOPRDCHK                     _MK_ENUM_CONST(0x00000001)
#define SATA_SEC_CMD_0_BM_SS_STOP                          _MK_ENUM_CONST(0x00000000)
#define SATA_SEC_CMD_0_BM_SS_START                         _MK_ENUM_CONST(0x00000001)
#define SATA_SEC_CMD_0_BM_RW_SHIFT                          _MK_SHIFT_CONST(3)
#define SATA_SEC_CMD_0_BM_RW_FIELD                         (_MK_SHIFT_CONST(0x1) << SATA_SEC_CMD_0_BM_RW_SHIFT)
#define SATA_SEC_CMD_0_BM_RW_RANGE                         3:3
#define SATA_SEC_CMD_0_BM_RW_WOFFSET                       0
#define SATA_SEC_CMD_0_BM_RW__NOPRDCHK                     _MK_ENUM_CONST(0x00000001)
#define SATA_SEC_CMD_0_BM_RW_READ                          _MK_ENUM_CONST(0x00000000)
#define SATA_SEC_CMD_0_BM_RW_WRITE                         _MK_ENUM_CONST(0x00000001)
#define SATA_SEC_STS_0                                     0x0000000A
#define SATA_SEC_STS_0_SECURE                              0
#define SATA_SEC_STS_0_WORD_COUNT                          1
#define SATA_SEC_STS_0_RESET_VAL                           0x0
#define SATA_SEC_STS_0_RESET_MASK                          0x65
#define SATA_SEC_STS_0_SW_DEFAULT_VAL                      0x0
#define SATA_SEC_STS_0_SW_DEFAULT_MASK                     0x65
#define SATA_SEC_STS_0_READ_MASK                           0xe7
#define SATA_SEC_STS_0_WRITE_MASK                          0x64
#define SATA_SEC_STS_0_BMSATAA_SHIFT                        _MK_SHIFT_CONST(0)
#define SATA_SEC_STS_0_BMSATAA_FIELD                       (_MK_SHIFT_CONST(0x1) << SATA_SEC_STS_0_BMSATAA_SHIFT)
#define SATA_SEC_STS_0_BMSATAA_RANGE                       0:0
#define SATA_SEC_STS_0_BMSATAA_WOFFSET                     0
#define SATA_SEC_STS_0_BMSATAA__NOPRDCHK                   _MK_ENUM_CONST(0x00000001)
#define SATA_SEC_STS_0_BMSATAA_NACTV                       _MK_ENUM_CONST(0x00000000)
#define SATA_SEC_STS_0_BMSATAA_ACTV                        _MK_ENUM_CONST(0x00000001)
#define SATA_SEC_STS_0_ERR_SHIFT                            _MK_SHIFT_CONST(1)
#define SATA_SEC_STS_0_ERR_FIELD                           (_MK_SHIFT_CONST(0x1) << SATA_SEC_STS_0_ERR_SHIFT)
#define SATA_SEC_STS_0_ERR_RANGE                           1:1
#define SATA_SEC_STS_0_ERR_WOFFSET                         0
#define SATA_SEC_STS_0_ERR__NOPRDCHK                       _MK_ENUM_CONST(0x00000001)
#define SATA_SEC_STS_0_ERR_NO                              _MK_ENUM_CONST(0x00000000)
#define SATA_SEC_STS_0_ERR_YES                             _MK_ENUM_CONST(0x00000001)
#define SATA_SEC_STS_0_INTR_SHIFT                           _MK_SHIFT_CONST(2)
#define SATA_SEC_STS_0_INTR_FIELD                          (_MK_SHIFT_CONST(0x1) << SATA_SEC_STS_0_INTR_SHIFT)
#define SATA_SEC_STS_0_INTR_RANGE                          2:2
#define SATA_SEC_STS_0_INTR_WOFFSET                        0
#define SATA_SEC_STS_0_INTR__NOPRDCHK                      _MK_ENUM_CONST(0x00000001)
#define SATA_SEC_STS_0_INTR_NO                             _MK_ENUM_CONST(0x00000000)
#define SATA_SEC_STS_0_INTR_YES                            _MK_ENUM_CONST(0x00000001)
#define SATA_SEC_STS_0_INTR_CLEAR                          _MK_ENUM_CONST(0x00000001)
#define SATA_SEC_STS_0_DMA0_SHIFT                           _MK_SHIFT_CONST(5)
#define SATA_SEC_STS_0_DMA0_FIELD                          (_MK_SHIFT_CONST(0x1) << SATA_SEC_STS_0_DMA0_SHIFT)
#define SATA_SEC_STS_0_DMA0_RANGE                          5:5
#define SATA_SEC_STS_0_DMA0_WOFFSET                        0
#define SATA_SEC_STS_0_DMA0__NOPRDCHK                      _MK_ENUM_CONST(0x00000001)
#define SATA_SEC_STS_0_DMA0_NO                             _MK_ENUM_CONST(0x00000000)
#define SATA_SEC_STS_0_DMA0_YES                            _MK_ENUM_CONST(0x00000001)
#define SATA_SEC_STS_0_DMA1_SHIFT                           _MK_SHIFT_CONST(6)
#define SATA_SEC_STS_0_DMA1_FIELD                          (_MK_SHIFT_CONST(0x1) << SATA_SEC_STS_0_DMA1_SHIFT)
#define SATA_SEC_STS_0_DMA1_RANGE                          6:6
#define SATA_SEC_STS_0_DMA1_WOFFSET                        0
#define SATA_SEC_STS_0_DMA1__NOPRDCHK                      _MK_ENUM_CONST(0x00000001)
#define SATA_SEC_STS_0_DMA1_NO                             _MK_ENUM_CONST(0x00000000)
#define SATA_SEC_STS_0_DMA1_YES                            _MK_ENUM_CONST(0x00000001)
#define SATA_SEC_STS_0_SMPLX_SHIFT                          _MK_SHIFT_CONST(7)
#define SATA_SEC_STS_0_SMPLX_FIELD                         (_MK_SHIFT_CONST(0x1) << SATA_SEC_STS_0_SMPLX_SHIFT)
#define SATA_SEC_STS_0_SMPLX_RANGE                         7:7
#define SATA_SEC_STS_0_SMPLX_WOFFSET                       0
#define SATA_SEC_STS_0_SMPLX__NOPRDCHK                     _MK_ENUM_CONST(0x00000001)
#define SATA_SEC_STS_0_SMPLX_NO                            _MK_ENUM_CONST(0x00000000)
#define SATA_SEC_STS_0_SMPLX_YES                           _MK_ENUM_CONST(0x00000001)
#define SATA_SEC_PRD_ADD_0                                 0x0000000C
#define SATA_SEC_PRD_ADD_0_SECURE                          0
#define SATA_SEC_PRD_ADD_0_WORD_COUNT                      1
#define SATA_SEC_PRD_ADD_0_RESET_VAL                       0x0
#define SATA_SEC_PRD_ADD_0_RESET_MASK                      0xfffffffc
#define SATA_SEC_PRD_ADD_0_SW_DEFAULT_VAL                  0x0
#define SATA_SEC_PRD_ADD_0_SW_DEFAULT_MASK                 0xfffffffc
#define SATA_SEC_PRD_ADD_0_READ_MASK                       0xfffffffc
#define SATA_SEC_PRD_ADD_0_WRITE_MASK                      0xfffffffc
#define SATA_SEC_PRD_ADD_0_DW_SHIFT                         _MK_SHIFT_CONST(2)
#define SATA_SEC_PRD_ADD_0_DW_FIELD                        (_MK_SHIFT_CONST(0x3fffffff) << SATA_SEC_PRD_ADD_0_DW_SHIFT)
#define SATA_SEC_PRD_ADD_0_DW_RANGE                        31:2
#define SATA_SEC_PRD_ADD_0_DW_WOFFSET                      0
#define SATA_SEC_PRD_ADD_0_DW__NOPRDCHK                    _MK_ENUM_CONST(0x00000001)
#define SATA_SEC_PRD_ADD_0_DW_0                            _MK_ENUM_CONST(0x00000000)
#define SATA_PRI_COMMAND_0_0                               0x000001F0
#define SATA_PRI_COMMAND_0_0_SECURE                        0
#define SATA_PRI_COMMAND_0_0_WORD_COUNT                    1
#define SATA_PRI_COMMAND_0_0_RESET_VAL                     0x0
#define SATA_PRI_COMMAND_0_0_RESET_MASK                    0xffffffff
#define SATA_PRI_COMMAND_0_0_SW_DEFAULT_VAL                0x0
#define SATA_PRI_COMMAND_0_0_SW_DEFAULT_MASK               0xffffffff
#define SATA_PRI_COMMAND_0_0_READ_MASK                     0xffffffff
#define SATA_PRI_COMMAND_0_0_WRITE_MASK                    0xffffffff
#define SATA_PRI_COMMAND_0_0_DATA_SHIFT                     _MK_SHIFT_CONST(0)
#define SATA_PRI_COMMAND_0_0_DATA_FIELD                    (_MK_SHIFT_CONST(0xff) << SATA_PRI_COMMAND_0_0_DATA_SHIFT)
#define SATA_PRI_COMMAND_0_0_DATA_RANGE                    7:0
#define SATA_PRI_COMMAND_0_0_DATA_WOFFSET                  0
#define SATA_PRI_COMMAND_0_0_DATA_INIT                     _MK_ENUM_CONST(0x00000000)
#define SATA_PRI_COMMAND_0_0_DATA__NOPRDCHK                _MK_ENUM_CONST(0x00000001)
#define SATA_PRI_COMMAND_0_0_FEATURE_ERR_SHIFT              _MK_SHIFT_CONST(8)
#define SATA_PRI_COMMAND_0_0_FEATURE_ERR_FIELD             (_MK_SHIFT_CONST(0xff) << SATA_PRI_COMMAND_0_0_FEATURE_ERR_SHIFT)
#define SATA_PRI_COMMAND_0_0_FEATURE_ERR_RANGE             15:8
#define SATA_PRI_COMMAND_0_0_FEATURE_ERR_WOFFSET           0
#define SATA_PRI_COMMAND_0_0_FEATURE_ERR_INIT              _MK_ENUM_CONST(0x00000000)
#define SATA_PRI_COMMAND_0_0_FEATURE_ERR__NOPRDCHK         _MK_ENUM_CONST(0x00000001)
#define SATA_PRI_COMMAND_0_0_SECTOR_COUNT_SHIFT             _MK_SHIFT_CONST(16)
#define SATA_PRI_COMMAND_0_0_SECTOR_COUNT_FIELD            (_MK_SHIFT_CONST(0xff) << SATA_PRI_COMMAND_0_0_SECTOR_COUNT_SHIFT)
#define SATA_PRI_COMMAND_0_0_SECTOR_COUNT_RANGE            23:16
#define SATA_PRI_COMMAND_0_0_SECTOR_COUNT_WOFFSET          0
#define SATA_PRI_COMMAND_0_0_SECTOR_COUNT_INIT             _MK_ENUM_CONST(0x00000000)
#define SATA_PRI_COMMAND_0_0_SECTOR_COUNT__NOPRDCHK        _MK_ENUM_CONST(0x00000001)
#define SATA_PRI_COMMAND_0_0_LBA_LOW_SHIFT                  _MK_SHIFT_CONST(24)
#define SATA_PRI_COMMAND_0_0_LBA_LOW_FIELD                 (_MK_SHIFT_CONST(0xff) << SATA_PRI_COMMAND_0_0_LBA_LOW_SHIFT)
#define SATA_PRI_COMMAND_0_0_LBA_LOW_RANGE                 31:24
#define SATA_PRI_COMMAND_0_0_LBA_LOW_WOFFSET               0
#define SATA_PRI_COMMAND_0_0_LBA_LOW_INIT                  _MK_ENUM_CONST(0x00000000)
#define SATA_PRI_COMMAND_0_0_LBA_LOW__NOPRDCHK             _MK_ENUM_CONST(0x00000001)
#define SATA_PRI_COMMAND_1_0                               0x000001F4
#define SATA_PRI_COMMAND_1_0_SECURE                        0
#define SATA_PRI_COMMAND_1_0_WORD_COUNT                    1
#define SATA_PRI_COMMAND_1_0_RESET_VAL                     0x0
#define SATA_PRI_COMMAND_1_0_RESET_MASK                    0xffffffff
#define SATA_PRI_COMMAND_1_0_SW_DEFAULT_VAL                0x0
#define SATA_PRI_COMMAND_1_0_SW_DEFAULT_MASK               0xffffffff
#define SATA_PRI_COMMAND_1_0_READ_MASK                     0xffffffff
#define SATA_PRI_COMMAND_1_0_WRITE_MASK                    0xffffffff
#define SATA_PRI_COMMAND_1_0_LBA_MID_SHIFT                  _MK_SHIFT_CONST(0)
#define SATA_PRI_COMMAND_1_0_LBA_MID_FIELD                 (_MK_SHIFT_CONST(0xff) << SATA_PRI_COMMAND_1_0_LBA_MID_SHIFT)
#define SATA_PRI_COMMAND_1_0_LBA_MID_RANGE                 7:0
#define SATA_PRI_COMMAND_1_0_LBA_MID_WOFFSET               0
#define SATA_PRI_COMMAND_1_0_LBA_MID_INIT                  _MK_ENUM_CONST(0x00000000)
#define SATA_PRI_COMMAND_1_0_LBA_MID__NOPRDCHK             _MK_ENUM_CONST(0x00000001)
#define SATA_PRI_COMMAND_1_0_LBA_HIGH_SHIFT                 _MK_SHIFT_CONST(8)
#define SATA_PRI_COMMAND_1_0_LBA_HIGH_FIELD                (_MK_SHIFT_CONST(0xff) << SATA_PRI_COMMAND_1_0_LBA_HIGH_SHIFT)
#define SATA_PRI_COMMAND_1_0_LBA_HIGH_RANGE                15:8
#define SATA_PRI_COMMAND_1_0_LBA_HIGH_WOFFSET              0
#define SATA_PRI_COMMAND_1_0_LBA_HIGH_INIT                 _MK_ENUM_CONST(0x00000000)
#define SATA_PRI_COMMAND_1_0_LBA_HIGH__NOPRDCHK            _MK_ENUM_CONST(0x00000001)
#define SATA_PRI_COMMAND_1_0_DEVICE_SHIFT                   _MK_SHIFT_CONST(16)
#define SATA_PRI_COMMAND_1_0_DEVICE_FIELD                  (_MK_SHIFT_CONST(0xff) << SATA_PRI_COMMAND_1_0_DEVICE_SHIFT)
#define SATA_PRI_COMMAND_1_0_DEVICE_RANGE                  23:16
#define SATA_PRI_COMMAND_1_0_DEVICE_WOFFSET                0
#define SATA_PRI_COMMAND_1_0_DEVICE_INIT                   _MK_ENUM_CONST(0x00000000)
#define SATA_PRI_COMMAND_1_0_DEVICE__NOPRDCHK              _MK_ENUM_CONST(0x00000001)
#define SATA_PRI_COMMAND_1_0_COMMAND_STATUS_SHIFT           _MK_SHIFT_CONST(24)
#define SATA_PRI_COMMAND_1_0_COMMAND_STATUS_FIELD          (_MK_SHIFT_CONST(0xff) << SATA_PRI_COMMAND_1_0_COMMAND_STATUS_SHIFT)
#define SATA_PRI_COMMAND_1_0_COMMAND_STATUS_RANGE          31:24
#define SATA_PRI_COMMAND_1_0_COMMAND_STATUS_WOFFSET        0
#define SATA_PRI_COMMAND_1_0_COMMAND_STATUS_INIT           _MK_ENUM_CONST(0x00000000)
#define SATA_PRI_COMMAND_1_0_COMMAND_STATUS__NOPRDCHK      _MK_ENUM_CONST(0x00000001)
#define SATA_PRI_CONTROL_0                                 0x000003F4
#define SATA_PRI_CONTROL_0_SECURE                          0
#define SATA_PRI_CONTROL_0_WORD_COUNT                      1
#define SATA_PRI_CONTROL_0_RESET_VAL                       0x0
#define SATA_PRI_CONTROL_0_RESET_MASK                      0xff0000
#define SATA_PRI_CONTROL_0_SW_DEFAULT_VAL                  0x0
#define SATA_PRI_CONTROL_0_SW_DEFAULT_MASK                 0xff0000
#define SATA_PRI_CONTROL_0_READ_MASK                       0xff0000
#define SATA_PRI_CONTROL_0_WRITE_MASK                      0xff0000
#define SATA_PRI_CONTROL_0_DEVICE_ALTERNATE_STATUS_SHIFT    _MK_SHIFT_CONST(16)
#define SATA_PRI_CONTROL_0_DEVICE_ALTERNATE_STATUS_FIELD   (_MK_SHIFT_CONST(0xff) << SATA_PRI_CONTROL_0_DEVICE_ALTERNATE_STATUS_SHIFT)
#define SATA_PRI_CONTROL_0_DEVICE_ALTERNATE_STATUS_RANGE   23:16
#define SATA_PRI_CONTROL_0_DEVICE_ALTERNATE_STATUS_WOFFSET 0
#define SATA_PRI_CONTROL_0_DEVICE_ALTERNATE_STATUS_INIT    _MK_ENUM_CONST(0x00000000)
#define SATA_PRI_CONTROL_0_DEVICE_ALTERNATE_STATUS__NOPRDCHK _MK_ENUM_CONST(0x00000001)
#define SATA_SEC_COMMAND_0_0                               0x00000170
#define SATA_SEC_COMMAND_0_0_SECURE                        0
#define SATA_SEC_COMMAND_0_0_WORD_COUNT                    1
#define SATA_SEC_COMMAND_0_0_RESET_VAL                     0x0
#define SATA_SEC_COMMAND_0_0_RESET_MASK                    0xffffffff
#define SATA_SEC_COMMAND_0_0_SW_DEFAULT_VAL                0x0
#define SATA_SEC_COMMAND_0_0_SW_DEFAULT_MASK               0xffffffff
#define SATA_SEC_COMMAND_0_0_READ_MASK                     0xffffffff
#define SATA_SEC_COMMAND_0_0_WRITE_MASK                    0xffffffff
#define SATA_SEC_COMMAND_0_0_DATA_SHIFT                     _MK_SHIFT_CONST(0)
#define SATA_SEC_COMMAND_0_0_DATA_FIELD                    (_MK_SHIFT_CONST(0xff) << SATA_SEC_COMMAND_0_0_DATA_SHIFT)
#define SATA_SEC_COMMAND_0_0_DATA_RANGE                    7:0
#define SATA_SEC_COMMAND_0_0_DATA_WOFFSET                  0
#define SATA_SEC_COMMAND_0_0_DATA_INIT                     _MK_ENUM_CONST(0x00000000)
#define SATA_SEC_COMMAND_0_0_DATA__NOPRDCHK                _MK_ENUM_CONST(0x00000001)
#define SATA_SEC_COMMAND_0_0_FEATURE_ERR_SHIFT              _MK_SHIFT_CONST(8)
#define SATA_SEC_COMMAND_0_0_FEATURE_ERR_FIELD             (_MK_SHIFT_CONST(0xff) << SATA_SEC_COMMAND_0_0_FEATURE_ERR_SHIFT)
#define SATA_SEC_COMMAND_0_0_FEATURE_ERR_RANGE             15:8
#define SATA_SEC_COMMAND_0_0_FEATURE_ERR_WOFFSET           0
#define SATA_SEC_COMMAND_0_0_FEATURE_ERR_INIT              _MK_ENUM_CONST(0x00000000)
#define SATA_SEC_COMMAND_0_0_FEATURE_ERR__NOPRDCHK         _MK_ENUM_CONST(0x00000001)
#define SATA_SEC_COMMAND_0_0_SECTOR_COUNT_SHIFT             _MK_SHIFT_CONST(16)
#define SATA_SEC_COMMAND_0_0_SECTOR_COUNT_FIELD            (_MK_SHIFT_CONST(0xff) << SATA_SEC_COMMAND_0_0_SECTOR_COUNT_SHIFT)
#define SATA_SEC_COMMAND_0_0_SECTOR_COUNT_RANGE            23:16
#define SATA_SEC_COMMAND_0_0_SECTOR_COUNT_WOFFSET          0
#define SATA_SEC_COMMAND_0_0_SECTOR_COUNT_INIT             _MK_ENUM_CONST(0x00000000)
#define SATA_SEC_COMMAND_0_0_SECTOR_COUNT__NOPRDCHK        _MK_ENUM_CONST(0x00000001)
#define SATA_SEC_COMMAND_0_0_LBA_LOW_SHIFT                  _MK_SHIFT_CONST(24)
#define SATA_SEC_COMMAND_0_0_LBA_LOW_FIELD                 (_MK_SHIFT_CONST(0xff) << SATA_SEC_COMMAND_0_0_LBA_LOW_SHIFT)
#define SATA_SEC_COMMAND_0_0_LBA_LOW_RANGE                 31:24
#define SATA_SEC_COMMAND_0_0_LBA_LOW_WOFFSET               0
#define SATA_SEC_COMMAND_0_0_LBA_LOW_INIT                  _MK_ENUM_CONST(0x00000000)
#define SATA_SEC_COMMAND_0_0_LBA_LOW__NOPRDCHK             _MK_ENUM_CONST(0x00000001)
#define SATA_SEC_COMMAND_1_0                               0x00000174
#define SATA_SEC_COMMAND_1_0_SECURE                        0
#define SATA_SEC_COMMAND_1_0_WORD_COUNT                    1
#define SATA_SEC_COMMAND_1_0_RESET_VAL                     0x0
#define SATA_SEC_COMMAND_1_0_RESET_MASK                    0xffffffff
#define SATA_SEC_COMMAND_1_0_SW_DEFAULT_VAL                0x0
#define SATA_SEC_COMMAND_1_0_SW_DEFAULT_MASK               0xffffffff
#define SATA_SEC_COMMAND_1_0_READ_MASK                     0xffffffff
#define SATA_SEC_COMMAND_1_0_WRITE_MASK                    0xffffffff
#define SATA_SEC_COMMAND_1_0_LBA_MID_SHIFT                  _MK_SHIFT_CONST(0)
#define SATA_SEC_COMMAND_1_0_LBA_MID_FIELD                 (_MK_SHIFT_CONST(0xff) << SATA_SEC_COMMAND_1_0_LBA_MID_SHIFT)
#define SATA_SEC_COMMAND_1_0_LBA_MID_RANGE                 7:0
#define SATA_SEC_COMMAND_1_0_LBA_MID_WOFFSET               0
#define SATA_SEC_COMMAND_1_0_LBA_MID_INIT                  _MK_ENUM_CONST(0x00000000)
#define SATA_SEC_COMMAND_1_0_LBA_MID__NOPRDCHK             _MK_ENUM_CONST(0x00000001)
#define SATA_SEC_COMMAND_1_0_LBA_HIGH_SHIFT                 _MK_SHIFT_CONST(8)
#define SATA_SEC_COMMAND_1_0_LBA_HIGH_FIELD                (_MK_SHIFT_CONST(0xff) << SATA_SEC_COMMAND_1_0_LBA_HIGH_SHIFT)
#define SATA_SEC_COMMAND_1_0_LBA_HIGH_RANGE                15:8
#define SATA_SEC_COMMAND_1_0_LBA_HIGH_WOFFSET              0
#define SATA_SEC_COMMAND_1_0_LBA_HIGH_INIT                 _MK_ENUM_CONST(0x00000000)
#define SATA_SEC_COMMAND_1_0_LBA_HIGH__NOPRDCHK            _MK_ENUM_CONST(0x00000001)
#define SATA_SEC_COMMAND_1_0_DEVICE_SHIFT                   _MK_SHIFT_CONST(16)
#define SATA_SEC_COMMAND_1_0_DEVICE_FIELD                  (_MK_SHIFT_CONST(0xff) << SATA_SEC_COMMAND_1_0_DEVICE_SHIFT)
#define SATA_SEC_COMMAND_1_0_DEVICE_RANGE                  23:16
#define SATA_SEC_COMMAND_1_0_DEVICE_WOFFSET                0
#define SATA_SEC_COMMAND_1_0_DEVICE_INIT                   _MK_ENUM_CONST(0x00000000)
#define SATA_SEC_COMMAND_1_0_DEVICE__NOPRDCHK              _MK_ENUM_CONST(0x00000001)
#define SATA_SEC_COMMAND_1_0_COMMAND_STATUS_SHIFT           _MK_SHIFT_CONST(24)
#define SATA_SEC_COMMAND_1_0_COMMAND_STATUS_FIELD          (_MK_SHIFT_CONST(0xff) << SATA_SEC_COMMAND_1_0_COMMAND_STATUS_SHIFT)
#define SATA_SEC_COMMAND_1_0_COMMAND_STATUS_RANGE          31:24
#define SATA_SEC_COMMAND_1_0_COMMAND_STATUS_WOFFSET        0
#define SATA_SEC_COMMAND_1_0_COMMAND_STATUS_INIT           _MK_ENUM_CONST(0x00000000)
#define SATA_SEC_COMMAND_1_0_COMMAND_STATUS__NOPRDCHK      _MK_ENUM_CONST(0x00000001)
#define SATA_SEC_CONTROL_0                                 0x00000374
#define SATA_SEC_CONTROL_0_SECURE                          0
#define SATA_SEC_CONTROL_0_WORD_COUNT                      1
#define SATA_SEC_CONTROL_0_RESET_VAL                       0x0
#define SATA_SEC_CONTROL_0_RESET_MASK                      0xff0000
#define SATA_SEC_CONTROL_0_SW_DEFAULT_VAL                  0x0
#define SATA_SEC_CONTROL_0_SW_DEFAULT_MASK                 0xff0000
#define SATA_SEC_CONTROL_0_READ_MASK                       0xff0000
#define SATA_SEC_CONTROL_0_WRITE_MASK                      0xff0000
#define SATA_SEC_CONTROL_0_DEVICE_ALTERNATE_STATUS_SHIFT    _MK_SHIFT_CONST(16)
#define SATA_SEC_CONTROL_0_DEVICE_ALTERNATE_STATUS_FIELD   (_MK_SHIFT_CONST(0xff) << SATA_SEC_CONTROL_0_DEVICE_ALTERNATE_STATUS_SHIFT)
#define SATA_SEC_CONTROL_0_DEVICE_ALTERNATE_STATUS_RANGE   23:16
#define SATA_SEC_CONTROL_0_DEVICE_ALTERNATE_STATUS_WOFFSET 0
#define SATA_SEC_CONTROL_0_DEVICE_ALTERNATE_STATUS_INIT    _MK_ENUM_CONST(0x00000000)
#define SATA_SEC_CONTROL_0_DEVICE_ALTERNATE_STATUS__NOPRDCHK _MK_ENUM_CONST(0x00000001)

// REGISTER LIST

#define LIST_SATA_REGS(_op_) \
  _op_(SATA_PRI_CMD_0) \
  _op_(SATA_PRI_STS_0) \
  _op_(SATA_PRI_PRD_ADD_0) \
  _op_(SATA_SEC_CMD_0) \
  _op_(SATA_SEC_STS_0) \
  _op_(SATA_SEC_PRD_ADD_0) \
  _op_(SATA_PRI_COMMAND_0_0) \
  _op_(SATA_PRI_COMMAND_1_0) \
  _op_(SATA_PRI_CONTROL_0) \
  _op_(SATA_SEC_COMMAND_0_0) \
  _op_(SATA_SEC_COMMAND_1_0) \
  _op_(SATA_SEC_CONTROL_0)


#ifndef _MK_SHIFT_CONST
  #define _MK_SHIFT_CONST(_constant_) _constant_
#endif
#ifndef _MK_MASK_CONST
  #define _MK_MASK_CONST(_constant_) _constant_
#endif
#ifndef _MK_ENUM_CONST
  #define _MK_ENUM_CONST(_constant_) (_constant_ ## UL)
#endif
#ifndef _MK_ADDR_CONST
  #define _MK_ADDR_CONST(_constant_) _constant_
#endif

#endif
