/*
 * Copyright (c) 2013 NVIDIA Corporation.  All rights reserved.
 *
 * NVIDIA Corporation and its licensors retain all intellectual property
 * and proprietary rights in and to this software and related documentation
 * and any modifications thereto.  Any use, reproduction, disclosure or
 * distribution of this software and related documentation without an express
 * license agreement from NVIDIA Corporation is strictly prohibited.
 */

#define T_SATA                               0x0000000F:0x00000000 /* RW--D */
#define T_SATA_PRI_CMD                                  0x00000000 /* RWI1R */
#define T_SATA_PRI_CMD_BM_SS                                   0:0 /* -W--F */
#define T_SATA_PRI_CMD_BM_SS__NOPRDCHK                  0x00000001 /* ----V */
#define T_SATA_PRI_CMD_BM_SS_STOP                       0x00000000 /* -W--V */
#define T_SATA_PRI_CMD_BM_SS_START                      0x00000001 /* -W--V */
#define T_SATA_PRI_CMD_BM_RW                                   3:3 /* RWI-F */
#define T_SATA_PRI_CMD_BM_RW__NOPRDCHK                  0x00000001 /* ----V */
#define T_SATA_PRI_CMD_BM_RW_READ                       0x00000000 /* RWI-V */
#define T_SATA_PRI_CMD_BM_RW_WRITE                      0x00000001 /* RW--V */
#define T_SATA_PRI_STS                                  0x00000002 /* RWI1R */
#define T_SATA_PRI_STS_BMSATAA                                 0:0 /* R-I-F */
#define T_SATA_PRI_STS_BMSATAA__NOPRDCHK                0x00000001 /* ----V */
#define T_SATA_PRI_STS_BMSATAA_NACTV                    0x00000000 /* R-I-V */
#define T_SATA_PRI_STS_BMSATAA_ACTV                     0x00000001 /* R---V */
#define T_SATA_PRI_STS_ERR                                     1:1 /* C--VF */
#define T_SATA_PRI_STS_ERR__NOPRDCHK                    0x00000001 /* ----V */
#define T_SATA_PRI_STS_ERR_NO                           0x00000000 /* C---V */
#define T_SATA_PRI_STS_ERR_YES                          0x00000001 /* ----V */
#define T_SATA_PRI_STS_INTR                                    2:2 /* RWIVF */
#define T_SATA_PRI_STS_INTR__NOPRDCHK                   0x00000001 /* ----V */
#define T_SATA_PRI_STS_INTR_NO                          0x00000000 /* R-I-V */
#define T_SATA_PRI_STS_INTR_YES                         0x00000001 /* R---V */
#define T_SATA_PRI_STS_INTR_CLEAR                       0x00000001 /* -W--V */
#define T_SATA_PRI_STS_DMA0                                    5:5 /* RWIVF */
#define T_SATA_PRI_STS_DMA0__NOPRDCHK                   0x00000001 /* ----V */
#define T_SATA_PRI_STS_DMA0_NO                          0x00000000 /* RWI-V */
#define T_SATA_PRI_STS_DMA0_YES                         0x00000001 /* RW--V */
#define T_SATA_PRI_STS_DMA1                                    6:6 /* RWIVF */
#define T_SATA_PRI_STS_DMA1__NOPRDCHK                   0x00000001 /* ----V */
#define T_SATA_PRI_STS_DMA1_NO                          0x00000000 /* RWI-V */
#define T_SATA_PRI_STS_DMA1_YES                         0x00000001 /* RW--V */
#define T_SATA_PRI_STS_SMPLX                                   7:7 /* C--VF */
#define T_SATA_PRI_STS_SMPLX__NOPRDCHK                  0x00000001 /* ----V */
#define T_SATA_PRI_STS_SMPLX_NO                         0x00000000 /* C---V */
#define T_SATA_PRI_STS_SMPLX_YES                        0x00000001 /* ----V */
#define T_SATA_PRI_PRD_ADD                              0x00000004 /* RWI4R */
#define T_SATA_PRI_PRD_ADD_DW                                 31:2 /* RWIVF */
#define T_SATA_PRI_PRD_ADD_DW__NOPRDCHK                 0x00000001 /* ----V */
#define T_SATA_PRI_PRD_ADD_DW_0                         0x00000000 /* RWI-V */
#define T_SATA_SEC_CMD                                  0x00000008 /* RWI1R */
#define T_SATA_SEC_CMD_BM_SS                                   0:0 /* -W--F */
#define T_SATA_SEC_CMD_BM_SS__NOPRDCHK                  0x00000001 /* ----V */
#define T_SATA_SEC_CMD_BM_SS_STOP                       0x00000000 /* -W--V */
#define T_SATA_SEC_CMD_BM_SS_START                      0x00000001 /* -W--V */
#define T_SATA_SEC_CMD_BM_RW                                   3:3 /* RWI-F */
#define T_SATA_SEC_CMD_BM_RW__NOPRDCHK                  0x00000001 /* ----V */
#define T_SATA_SEC_CMD_BM_RW_READ                       0x00000000 /* RWI-V */
#define T_SATA_SEC_CMD_BM_RW_WRITE                      0x00000001 /* RW--V */
#define T_SATA_SEC_STS                                  0x0000000A /* RWI1R */
#define T_SATA_SEC_STS_BMSATAA                                 0:0 /* R-I-F */
#define T_SATA_SEC_STS_BMSATAA__NOPRDCHK                0x00000001 /* ----V */
#define T_SATA_SEC_STS_BMSATAA_NACTV                    0x00000000 /* R-I-V */
#define T_SATA_SEC_STS_BMSATAA_ACTV                     0x00000001 /* R---V */
#define T_SATA_SEC_STS_ERR                                     1:1 /* C--VF */
#define T_SATA_SEC_STS_ERR__NOPRDCHK                    0x00000001 /* ----V */
#define T_SATA_SEC_STS_ERR_NO                           0x00000000 /* C---V */
#define T_SATA_SEC_STS_ERR_YES                          0x00000001 /* ----V */
#define T_SATA_SEC_STS_INTR                                    2:2 /* RWIVF */
#define T_SATA_SEC_STS_INTR__NOPRDCHK                   0x00000001 /* ----V */
#define T_SATA_SEC_STS_INTR_NO                          0x00000000 /* R-I-V */
#define T_SATA_SEC_STS_INTR_YES                         0x00000001 /* R---V */
#define T_SATA_SEC_STS_INTR_CLEAR                       0x00000001 /* -W--V */
#define T_SATA_SEC_STS_DMA0                                    5:5 /* RWIVF */
#define T_SATA_SEC_STS_DMA0__NOPRDCHK                   0x00000001 /* ----V */
#define T_SATA_SEC_STS_DMA0_NO                          0x00000000 /* RWI-V */
#define T_SATA_SEC_STS_DMA0_YES                         0x00000001 /* RW--V */
#define T_SATA_SEC_STS_DMA1                                    6:6 /* RWIVF */
#define T_SATA_SEC_STS_DMA1__NOPRDCHK                   0x00000001 /* ----V */
#define T_SATA_SEC_STS_DMA1_NO                          0x00000000 /* RWI-V */
#define T_SATA_SEC_STS_DMA1_YES                         0x00000001 /* RW--V */
#define T_SATA_SEC_STS_SMPLX                                   7:7 /* C--VF */
#define T_SATA_SEC_STS_SMPLX__NOPRDCHK                  0x00000001 /* ----V */
#define T_SATA_SEC_STS_SMPLX_NO                         0x00000000 /* C---V */
#define T_SATA_SEC_STS_SMPLX_YES                        0x00000001 /* ----V */
#define T_SATA_SEC_PRD_ADD                              0x0000000C /* RWI4R */
#define T_SATA_SEC_PRD_ADD_DW                                 31:2 /* RWIVF */
#define T_SATA_SEC_PRD_ADD_DW__NOPRDCHK                 0x00000001 /* ----V */
#define T_SATA_SEC_PRD_ADD_DW_0                         0x00000000 /* RWI-V */
#define T_SATA_PRI_COMMAND_0                            0x000001F0 /* RWI4R */
#define T_SATA_PRI_COMMAND_0_DATA                              7:0 /* RWIVF */
#define T_SATA_PRI_COMMAND_0_DATA_INIT                  0x00000000 /* RWI-V */
#define T_SATA_PRI_COMMAND_0_DATA__NOPRDCHK             0x00000001 /* ----V */
#define T_SATA_PRI_COMMAND_0_FEATURE_ERR                      15:8 /* RWIVF */
#define T_SATA_PRI_COMMAND_0_FEATURE_ERR_INIT           0x00000000 /* RWI-V */
#define T_SATA_PRI_COMMAND_0_FEATURE_ERR__NOPRDCHK      0x00000001 /* ----V */
#define T_SATA_PRI_COMMAND_0_SECTOR_COUNT                    23:16 /* RWIVF */
#define T_SATA_PRI_COMMAND_0_SECTOR_COUNT_INIT          0x00000000 /* RWI-V */
#define T_SATA_PRI_COMMAND_0_SECTOR_COUNT__NOPRDCHK     0x00000001 /* ----V */
#define T_SATA_PRI_COMMAND_0_LBA_LOW                         31:24 /* RWIVF */
#define T_SATA_PRI_COMMAND_0_LBA_LOW_INIT               0x00000000 /* RWI-V */
#define T_SATA_PRI_COMMAND_0_LBA_LOW__NOPRDCHK          0x00000001 /* ----V */
#define T_SATA_PRI_COMMAND_1                            0x000001F4 /* RWI4R */
#define T_SATA_PRI_COMMAND_1_LBA_MID                           7:0 /* RWIVF */
#define T_SATA_PRI_COMMAND_1_LBA_MID_INIT               0x00000000 /* RWI-V */
#define T_SATA_PRI_COMMAND_1_LBA_MID__NOPRDCHK          0x00000001 /* ----V */
#define T_SATA_PRI_COMMAND_1_LBA_HIGH                         15:8 /* RWIVF */
#define T_SATA_PRI_COMMAND_1_LBA_HIGH_INIT              0x00000000 /* RWI-V */
#define T_SATA_PRI_COMMAND_1_LBA_HIGH__NOPRDCHK         0x00000001 /* ----V */
#define T_SATA_PRI_COMMAND_1_DEVICE                          23:16 /* RWIVF */
#define T_SATA_PRI_COMMAND_1_DEVICE_INIT                0x00000000 /* RWI-V */
#define T_SATA_PRI_COMMAND_1_DEVICE__NOPRDCHK           0x00000001 /* ----V */
#define T_SATA_PRI_COMMAND_1_COMMAND_STATUS                  31:24 /* RWIVF */
#define T_SATA_PRI_COMMAND_1_COMMAND_STATUS_INIT        0x00000000 /* RWI-V */
#define T_SATA_PRI_COMMAND_1_COMMAND_STATUS__NOPRDCHK   0x00000001 /* ----V */
#define T_SATA_PRI_CONTROL                                     0x000003F4 /* RWI4R */
#define T_SATA_PRI_CONTROL_DEVICE_ALTERNATE_STATUS                  23:16 /* RWIVF */
#define T_SATA_PRI_CONTROL_DEVICE_ALTERNATE_STATUS_INIT        0x00000000 /* RWI-V */
#define T_SATA_PRI_CONTROL_DEVICE_ALTERNATE_STATUS__NOPRDCHK   0x00000001 /* ----V */
#define T_SATA_SEC_COMMAND_0                            0x00000170 /* RWI4R */
#define T_SATA_SEC_COMMAND_0_DATA                              7:0 /* RWIVF */
#define T_SATA_SEC_COMMAND_0_DATA_INIT                  0x00000000 /* RWI-V */
#define T_SATA_SEC_COMMAND_0_DATA__NOPRDCHK             0x00000001 /* ----V */
#define T_SATA_SEC_COMMAND_0_FEATURE_ERR                      15:8 /* RWIVF */
#define T_SATA_SEC_COMMAND_0_FEATURE_ERR_INIT           0x00000000 /* RWI-V */
#define T_SATA_SEC_COMMAND_0_FEATURE_ERR__NOPRDCHK      0x00000001 /* ----V */
#define T_SATA_SEC_COMMAND_0_SECTOR_COUNT                    23:16 /* RWIVF */
#define T_SATA_SEC_COMMAND_0_SECTOR_COUNT_INIT          0x00000000 /* RWI-V */
#define T_SATA_SEC_COMMAND_0_SECTOR_COUNT__NOPRDCHK     0x00000001 /* ----V */
#define T_SATA_SEC_COMMAND_0_LBA_LOW                         31:24 /* RWIVF */
#define T_SATA_SEC_COMMAND_0_LBA_LOW_INIT               0x00000000 /* RWI-V */
#define T_SATA_SEC_COMMAND_0_LBA_LOW__NOPRDCHK          0x00000001 /* ----V */
#define T_SATA_SEC_COMMAND_1                            0x00000174 /* RWI4R */
#define T_SATA_SEC_COMMAND_1_LBA_MID                           7:0 /* RWIVF */
#define T_SATA_SEC_COMMAND_1_LBA_MID_INIT               0x00000000 /* RWI-V */
#define T_SATA_SEC_COMMAND_1_LBA_MID__NOPRDCHK          0x00000001 /* ----V */
#define T_SATA_SEC_COMMAND_1_LBA_HIGH                         15:8 /* RWIVF */
#define T_SATA_SEC_COMMAND_1_LBA_HIGH_INIT              0x00000000 /* RWI-V */
#define T_SATA_SEC_COMMAND_1_LBA_HIGH__NOPRDCHK         0x00000001 /* ----V */
#define T_SATA_SEC_COMMAND_1_DEVICE                          23:16 /* RWIVF */
#define T_SATA_SEC_COMMAND_1_DEVICE_INIT                0x00000000 /* RWI-V */
#define T_SATA_SEC_COMMAND_1_DEVICE__NOPRDCHK           0x00000001 /* ----V */
#define T_SATA_SEC_COMMAND_1_COMMAND_STATUS                  31:24 /* RWIVF */
#define T_SATA_SEC_COMMAND_1_COMMAND_STATUS_INIT        0x00000000 /* RWI-V */
#define T_SATA_SEC_COMMAND_1_COMMAND_STATUS__NOPRDCHK   0x00000001 /* ----V */
#define T_SATA_SEC_CONTROL                                     0x00000374 /* RWI4R */
#define T_SATA_SEC_CONTROL_DEVICE_ALTERNATE_STATUS                  23:16 /* RWIVF */
#define T_SATA_SEC_CONTROL_DEVICE_ALTERNATE_STATUS_INIT        0x00000000 /* RWI-V */
#define T_SATA_SEC_CONTROL_DEVICE_ALTERNATE_STATUS__NOPRDCHK   0x00000001 /* ----V */
