//
// Copyright (c) 2013 NVIDIA Corporation.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// Redistributions of source code must retain the above copyright notice,
// this list of conditions and the following disclaimer.
//
// Redistributions in binary form must reproduce the above copyright notice,
// this list of conditions and the following disclaimer in the documentation
// and/or other materials provided with the distribution.
//
// Neither the name of the NVIDIA Corporation nor the names of its contributors
// may be used to endorse or promote products derived from this software
// without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.
//

//
// DO NOT EDIT - generated by simspec!
//

#ifndef ___ARAPB_MISC_PP_H_INC_
#define ___ARAPB_MISC_PP_H_INC_

// Reserved address 0 [0x0]

// Reserved address 4 [0x4]

// Reserved address 8 [0x8]

// Reserved address 12 [0xc]

// Reserved address 16 [0x10]

// Reserved address 20 [0x14]

// Reserved address 24 [0x18]

// Reserved address 28 [0x1c]

// Reserved address 32 [0x20]

// Register APB_MISC_PP_CONFIG_CTL_0
#define APB_MISC_PP_CONFIG_CTL_0                        _MK_ADDR_CONST(0x24)
#define APB_MISC_PP_CONFIG_CTL_0_SECURE                         0x0
#define APB_MISC_PP_CONFIG_CTL_0_WORD_COUNT                     0x1
#define APB_MISC_PP_CONFIG_CTL_0_RESET_VAL                      _MK_MASK_CONST(0x40)
#define APB_MISC_PP_CONFIG_CTL_0_RESET_MASK                     _MK_MASK_CONST(0xc3)
#define APB_MISC_PP_CONFIG_CTL_0_SW_DEFAULT_VAL                         _MK_MASK_CONST(0x0)
#define APB_MISC_PP_CONFIG_CTL_0_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define APB_MISC_PP_CONFIG_CTL_0_READ_MASK                      _MK_MASK_CONST(0xc3)
#define APB_MISC_PP_CONFIG_CTL_0_WRITE_MASK                     _MK_MASK_CONST(0xc3)
#define APB_MISC_PP_CONFIG_CTL_0_TBE_SHIFT                      _MK_SHIFT_CONST(7)
#define APB_MISC_PP_CONFIG_CTL_0_TBE_FIELD                      _MK_FIELD_CONST(0x1, APB_MISC_PP_CONFIG_CTL_0_TBE_SHIFT)
#define APB_MISC_PP_CONFIG_CTL_0_TBE_RANGE                      7:7
#define APB_MISC_PP_CONFIG_CTL_0_TBE_WOFFSET                    0x0
#define APB_MISC_PP_CONFIG_CTL_0_TBE_DEFAULT                    _MK_MASK_CONST(0x0)
#define APB_MISC_PP_CONFIG_CTL_0_TBE_DEFAULT_MASK                       _MK_MASK_CONST(0x1)
#define APB_MISC_PP_CONFIG_CTL_0_TBE_SW_DEFAULT                 _MK_MASK_CONST(0x0)
#define APB_MISC_PP_CONFIG_CTL_0_TBE_SW_DEFAULT_MASK                    _MK_MASK_CONST(0x0)
#define APB_MISC_PP_CONFIG_CTL_0_TBE_INIT_ENUM                  DISABLE
#define APB_MISC_PP_CONFIG_CTL_0_TBE_DISABLE                    _MK_ENUM_CONST(0)
#define APB_MISC_PP_CONFIG_CTL_0_TBE_ENABLE                     _MK_ENUM_CONST(1)

#define APB_MISC_PP_CONFIG_CTL_0_JTAG_SHIFT                     _MK_SHIFT_CONST(6)
#define APB_MISC_PP_CONFIG_CTL_0_JTAG_FIELD                     _MK_FIELD_CONST(0x1, APB_MISC_PP_CONFIG_CTL_0_JTAG_SHIFT)
#define APB_MISC_PP_CONFIG_CTL_0_JTAG_RANGE                     6:6
#define APB_MISC_PP_CONFIG_CTL_0_JTAG_WOFFSET                   0x0
#define APB_MISC_PP_CONFIG_CTL_0_JTAG_DEFAULT                   _MK_MASK_CONST(0x1)
#define APB_MISC_PP_CONFIG_CTL_0_JTAG_DEFAULT_MASK                      _MK_MASK_CONST(0x1)
#define APB_MISC_PP_CONFIG_CTL_0_JTAG_SW_DEFAULT                        _MK_MASK_CONST(0x0)
#define APB_MISC_PP_CONFIG_CTL_0_JTAG_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define APB_MISC_PP_CONFIG_CTL_0_JTAG_INIT_ENUM                 ENABLE
#define APB_MISC_PP_CONFIG_CTL_0_JTAG_DISABLE                   _MK_ENUM_CONST(0)
#define APB_MISC_PP_CONFIG_CTL_0_JTAG_ENABLE                    _MK_ENUM_CONST(1)

#define APB_MISC_PP_CONFIG_CTL_0_XBAR_SO_DEFAULT_SHIFT                  _MK_SHIFT_CONST(1)
#define APB_MISC_PP_CONFIG_CTL_0_XBAR_SO_DEFAULT_FIELD                  _MK_FIELD_CONST(0x1, APB_MISC_PP_CONFIG_CTL_0_XBAR_SO_DEFAULT_SHIFT)
#define APB_MISC_PP_CONFIG_CTL_0_XBAR_SO_DEFAULT_RANGE                  1:1
#define APB_MISC_PP_CONFIG_CTL_0_XBAR_SO_DEFAULT_WOFFSET                        0x0
#define APB_MISC_PP_CONFIG_CTL_0_XBAR_SO_DEFAULT_DEFAULT                        _MK_MASK_CONST(0x0)
#define APB_MISC_PP_CONFIG_CTL_0_XBAR_SO_DEFAULT_DEFAULT_MASK                   _MK_MASK_CONST(0x1)
#define APB_MISC_PP_CONFIG_CTL_0_XBAR_SO_DEFAULT_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define APB_MISC_PP_CONFIG_CTL_0_XBAR_SO_DEFAULT_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define APB_MISC_PP_CONFIG_CTL_0_XBAR_SO_DEFAULT_INIT_ENUM                      DISABLE
#define APB_MISC_PP_CONFIG_CTL_0_XBAR_SO_DEFAULT_DISABLE                        _MK_ENUM_CONST(0)
#define APB_MISC_PP_CONFIG_CTL_0_XBAR_SO_DEFAULT_ENABLE                 _MK_ENUM_CONST(1)

#define APB_MISC_PP_CONFIG_CTL_0_CPU_XBAR_SO_ENABLE_SHIFT                       _MK_SHIFT_CONST(0)
#define APB_MISC_PP_CONFIG_CTL_0_CPU_XBAR_SO_ENABLE_FIELD                       _MK_FIELD_CONST(0x1, APB_MISC_PP_CONFIG_CTL_0_CPU_XBAR_SO_ENABLE_SHIFT)
#define APB_MISC_PP_CONFIG_CTL_0_CPU_XBAR_SO_ENABLE_RANGE                       0:0
#define APB_MISC_PP_CONFIG_CTL_0_CPU_XBAR_SO_ENABLE_WOFFSET                     0x0
#define APB_MISC_PP_CONFIG_CTL_0_CPU_XBAR_SO_ENABLE_DEFAULT                     _MK_MASK_CONST(0x0)
#define APB_MISC_PP_CONFIG_CTL_0_CPU_XBAR_SO_ENABLE_DEFAULT_MASK                        _MK_MASK_CONST(0x1)
#define APB_MISC_PP_CONFIG_CTL_0_CPU_XBAR_SO_ENABLE_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define APB_MISC_PP_CONFIG_CTL_0_CPU_XBAR_SO_ENABLE_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)
#define APB_MISC_PP_CONFIG_CTL_0_CPU_XBAR_SO_ENABLE_INIT_ENUM                   DISABLE
#define APB_MISC_PP_CONFIG_CTL_0_CPU_XBAR_SO_ENABLE_DISABLE                     _MK_ENUM_CONST(0)
#define APB_MISC_PP_CONFIG_CTL_0_CPU_XBAR_SO_ENABLE_ENABLE                      _MK_ENUM_CONST(1)


// Reserved address 40 [0x28]

// Reserved address 48 [0x30]

// Reserved address 52 [0x34]

// Reserved address 56 [0x38]

// Register APB_MISC_PP_PINMUX_GLOBAL_0_0
#define APB_MISC_PP_PINMUX_GLOBAL_0_0                   _MK_ADDR_CONST(0x40)
#define APB_MISC_PP_PINMUX_GLOBAL_0_0_SECURE                    0x0
#define APB_MISC_PP_PINMUX_GLOBAL_0_0_WORD_COUNT                        0x1
#define APB_MISC_PP_PINMUX_GLOBAL_0_0_RESET_VAL                         _MK_MASK_CONST(0x0)
#define APB_MISC_PP_PINMUX_GLOBAL_0_0_RESET_MASK                        _MK_MASK_CONST(0x1)
#define APB_MISC_PP_PINMUX_GLOBAL_0_0_SW_DEFAULT_VAL                    _MK_MASK_CONST(0x0)
#define APB_MISC_PP_PINMUX_GLOBAL_0_0_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define APB_MISC_PP_PINMUX_GLOBAL_0_0_READ_MASK                         _MK_MASK_CONST(0x1)
#define APB_MISC_PP_PINMUX_GLOBAL_0_0_WRITE_MASK                        _MK_MASK_CONST(0x1)
#define APB_MISC_PP_PINMUX_GLOBAL_0_0_CLAMP_INPUTS_WHEN_TRISTATED_SHIFT                 _MK_SHIFT_CONST(0)
#define APB_MISC_PP_PINMUX_GLOBAL_0_0_CLAMP_INPUTS_WHEN_TRISTATED_FIELD                 _MK_FIELD_CONST(0x1, APB_MISC_PP_PINMUX_GLOBAL_0_0_CLAMP_INPUTS_WHEN_TRISTATED_SHIFT)
#define APB_MISC_PP_PINMUX_GLOBAL_0_0_CLAMP_INPUTS_WHEN_TRISTATED_RANGE                 0:0
#define APB_MISC_PP_PINMUX_GLOBAL_0_0_CLAMP_INPUTS_WHEN_TRISTATED_WOFFSET                       0x0
#define APB_MISC_PP_PINMUX_GLOBAL_0_0_CLAMP_INPUTS_WHEN_TRISTATED_DEFAULT                       _MK_MASK_CONST(0x0)
#define APB_MISC_PP_PINMUX_GLOBAL_0_0_CLAMP_INPUTS_WHEN_TRISTATED_DEFAULT_MASK                  _MK_MASK_CONST(0x1)
#define APB_MISC_PP_PINMUX_GLOBAL_0_0_CLAMP_INPUTS_WHEN_TRISTATED_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define APB_MISC_PP_PINMUX_GLOBAL_0_0_CLAMP_INPUTS_WHEN_TRISTATED_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define APB_MISC_PP_PINMUX_GLOBAL_0_0_CLAMP_INPUTS_WHEN_TRISTATED_INIT_ENUM                     DISABLE
#define APB_MISC_PP_PINMUX_GLOBAL_0_0_CLAMP_INPUTS_WHEN_TRISTATED_DISABLE                       _MK_ENUM_CONST(0)
#define APB_MISC_PP_PINMUX_GLOBAL_0_0_CLAMP_INPUTS_WHEN_TRISTATED_ENABLE                        _MK_ENUM_CONST(1)


// Reserved address 68 [0x44]

// Reserved address 96 [0x60]

// Reserved address 100 [0x64]

// Reserved address 104 [0x68]

// Reserved address 108 [0x6c]

// Reserved address 112 [0x70]

// Reserved address 116 [0x74]

// Reserved address 120 [0x78]

// Register APB_MISC_PP_MISC_SAVE_THE_DAY_0
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0                 _MK_ADDR_CONST(0x7c)
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SECURE                  0x0
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_WORD_COUNT                      0x1
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_RESET_VAL                       _MK_MASK_CONST(0x0)
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_RESET_MASK                      _MK_MASK_CONST(0xffffffff)
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SW_DEFAULT_VAL                  _MK_MASK_CONST(0x0)
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SW_DEFAULT_MASK                         _MK_MASK_CONST(0x0)
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_READ_MASK                       _MK_MASK_CONST(0xffffffff)
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_WRITE_MASK                      _MK_MASK_CONST(0xffffffff)
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_A_SHIFT                    _MK_SHIFT_CONST(24)
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_A_FIELD                    _MK_FIELD_CONST(0xff, APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_A_SHIFT)
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_A_RANGE                    31:24
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_A_WOFFSET                  0x0
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_A_DEFAULT                  _MK_MASK_CONST(0x0)
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_A_DEFAULT_MASK                     _MK_MASK_CONST(0xff)
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_A_SW_DEFAULT                       _MK_MASK_CONST(0x0)
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_A_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)

#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_B_SHIFT                    _MK_SHIFT_CONST(16)
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_B_FIELD                    _MK_FIELD_CONST(0xff, APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_B_SHIFT)
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_B_RANGE                    23:16
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_B_WOFFSET                  0x0
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_B_DEFAULT                  _MK_MASK_CONST(0x0)
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_B_DEFAULT_MASK                     _MK_MASK_CONST(0xff)
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_B_SW_DEFAULT                       _MK_MASK_CONST(0x0)
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_B_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)

#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_C_SHIFT                    _MK_SHIFT_CONST(8)
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_C_FIELD                    _MK_FIELD_CONST(0xff, APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_C_SHIFT)
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_C_RANGE                    15:8
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_C_WOFFSET                  0x0
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_C_DEFAULT                  _MK_MASK_CONST(0x0)
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_C_DEFAULT_MASK                     _MK_MASK_CONST(0xff)
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_C_SW_DEFAULT                       _MK_MASK_CONST(0x0)
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_C_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)

#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_D_SHIFT                    _MK_SHIFT_CONST(0)
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_D_FIELD                    _MK_FIELD_CONST(0xff, APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_D_SHIFT)
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_D_RANGE                    7:0
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_D_WOFFSET                  0x0
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_D_DEFAULT                  _MK_MASK_CONST(0x0)
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_D_DEFAULT_MASK                     _MK_MASK_CONST(0xff)
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_D_SW_DEFAULT                       _MK_MASK_CONST(0x0)
#define APB_MISC_PP_MISC_SAVE_THE_DAY_0_SAVE_THE_DAY_D_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)


// Reserved address 128 [0x80]

// Reserved address 132 [0x84]

// Reserved address 136 [0x88]

// Reserved address 140 [0x8c]

// Reserved address 144 [0x90]

// Reserved address 148 [0x94]

// Reserved address 152 [0x98]

// Reserved address 156 [0x9c]

// Reserved address 160 [0xa0]

// Reserved address 164 [0xa4]

// Register APB_MISC_PP_PULLUPDOWN_REG_C_0
#define APB_MISC_PP_PULLUPDOWN_REG_C_0                  _MK_ADDR_CONST(0xa8)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_SECURE                   0x0
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_WORD_COUNT                       0x1
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_RESET_VAL                        _MK_MASK_CONST(0x0)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_RESET_MASK                       _MK_MASK_CONST(0xfc000000)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_SW_DEFAULT_VAL                   _MK_MASK_CONST(0x0)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_READ_MASK                        _MK_MASK_CONST(0xfc000000)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_WRITE_MASK                       _MK_MASK_CONST(0xfc000000)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_XM2C_PU_PD_SHIFT                 _MK_SHIFT_CONST(30)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_XM2C_PU_PD_FIELD                 _MK_FIELD_CONST(0x3, APB_MISC_PP_PULLUPDOWN_REG_C_0_XM2C_PU_PD_SHIFT)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_XM2C_PU_PD_RANGE                 31:30
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_XM2C_PU_PD_WOFFSET                       0x0
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_XM2C_PU_PD_DEFAULT                       _MK_MASK_CONST(0x0)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_XM2C_PU_PD_DEFAULT_MASK                  _MK_MASK_CONST(0x3)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_XM2C_PU_PD_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_XM2C_PU_PD_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_XM2C_PU_PD_INIT_ENUM                     NORMAL
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_XM2C_PU_PD_NORMAL                        _MK_ENUM_CONST(0)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_XM2C_PU_PD_PULL_DOWN                     _MK_ENUM_CONST(1)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_XM2C_PU_PD_PULL_UP                       _MK_ENUM_CONST(2)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_XM2C_PU_PD_RSVD                  _MK_ENUM_CONST(3)

#define APB_MISC_PP_PULLUPDOWN_REG_C_0_XM2D_PU_PD_SHIFT                 _MK_SHIFT_CONST(28)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_XM2D_PU_PD_FIELD                 _MK_FIELD_CONST(0x3, APB_MISC_PP_PULLUPDOWN_REG_C_0_XM2D_PU_PD_SHIFT)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_XM2D_PU_PD_RANGE                 29:28
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_XM2D_PU_PD_WOFFSET                       0x0
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_XM2D_PU_PD_DEFAULT                       _MK_MASK_CONST(0x0)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_XM2D_PU_PD_DEFAULT_MASK                  _MK_MASK_CONST(0x3)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_XM2D_PU_PD_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_XM2D_PU_PD_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_XM2D_PU_PD_INIT_ENUM                     NORMAL
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_XM2D_PU_PD_NORMAL                        _MK_ENUM_CONST(0)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_XM2D_PU_PD_PULL_DOWN                     _MK_ENUM_CONST(1)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_XM2D_PU_PD_PULL_UP                       _MK_ENUM_CONST(2)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_XM2D_PU_PD_RSVD                  _MK_ENUM_CONST(3)

#define APB_MISC_PP_PULLUPDOWN_REG_C_0_DDRC_PU_PD_SHIFT                 _MK_SHIFT_CONST(26)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_DDRC_PU_PD_FIELD                 _MK_FIELD_CONST(0x3, APB_MISC_PP_PULLUPDOWN_REG_C_0_DDRC_PU_PD_SHIFT)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_DDRC_PU_PD_RANGE                 27:26
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_DDRC_PU_PD_WOFFSET                       0x0
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_DDRC_PU_PD_DEFAULT                       _MK_MASK_CONST(0x0)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_DDRC_PU_PD_DEFAULT_MASK                  _MK_MASK_CONST(0x3)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_DDRC_PU_PD_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_DDRC_PU_PD_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_DDRC_PU_PD_INIT_ENUM                     NORMAL
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_DDRC_PU_PD_NORMAL                        _MK_ENUM_CONST(0)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_DDRC_PU_PD_PULL_DOWN                     _MK_ENUM_CONST(1)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_DDRC_PU_PD_PULL_UP                       _MK_ENUM_CONST(2)
#define APB_MISC_PP_PULLUPDOWN_REG_C_0_DDRC_PU_PD_RSVD                  _MK_ENUM_CONST(3)


//
// REGISTER LIST
//
#define LIST_ARAPB_MISC_PP_REGS(_op_) \
_op_(APB_MISC_PP_CONFIG_CTL_0) \
_op_(APB_MISC_PP_PINMUX_GLOBAL_0_0) \
_op_(APB_MISC_PP_MISC_SAVE_THE_DAY_0) \
_op_(APB_MISC_PP_PULLUPDOWN_REG_C_0)


//
// ADDRESS SPACES
//

#define BASE_ADDRESS_APB_MISC_PP        0x00000000

//
// ARAPB_MISC_PP REGISTER BANKS
//

#define APB_MISC_PP0_FIRST_REG 0x0024 // APB_MISC_PP_CONFIG_CTL_0
#define APB_MISC_PP0_LAST_REG 0x0024 // APB_MISC_PP_CONFIG_CTL_0
#define APB_MISC_PP1_FIRST_REG 0x0040 // APB_MISC_PP_PINMUX_GLOBAL_0_0
#define APB_MISC_PP1_LAST_REG 0x0040 // APB_MISC_PP_PINMUX_GLOBAL_0_0
#define APB_MISC_PP2_FIRST_REG 0x007c // APB_MISC_PP_MISC_SAVE_THE_DAY_0
#define APB_MISC_PP2_LAST_REG 0x007c // APB_MISC_PP_MISC_SAVE_THE_DAY_0
#define APB_MISC_PP3_FIRST_REG 0x00a8 // APB_MISC_PP_PULLUPDOWN_REG_C_0
#define APB_MISC_PP3_LAST_REG 0x00a8 // APB_MISC_PP_PULLUPDOWN_REG_C_0

// To satisfy various compilers and platforms,
// we let users control the types and syntax of certain constants, using macros.
#ifndef _MK_SHIFT_CONST
  #define _MK_SHIFT_CONST(_constant_) _constant_
#endif
#ifndef _MK_MASK_CONST
  #define _MK_MASK_CONST(_constant_) _constant_
#endif
#ifndef _MK_ENUM_CONST
  #define _MK_ENUM_CONST(_constant_) (_constant_ ## UL)
#endif
#ifndef _MK_ADDR_CONST
  #define _MK_ADDR_CONST(_constant_) _constant_
#endif
#ifndef _MK_FIELD_CONST
  #define _MK_FIELD_CONST(_mask_, _shift_) (_MK_MASK_CONST(_mask_) << _MK_SHIFT_CONST(_shift_))
#endif

#endif // ifndef ___ARAPB_MISC_PP_H_INC_
