
#ifndef HOST1X_MODULE_IDS_H_INC
#define HOST1X_MODULE_IDS_H_INC

#define NV_HOST1X_MODULEID_HOST1X        0x0
#define NV_HOST1X_MODULEID_MPE           0x1
#define NV_HOST1X_MODULEID_MPE2X         0x1
#define NV_HOST1X_MODULEID_VI            0x2
#define NV_HOST1X_MODULEID_EPP           0x3
#define NV_HOST1X_MODULEID_GR2D          0x5
#define NV_HOST1X_MODULEID_GR3D          0x6
#define NV_HOST1X_MODULEID_VG            0x7
#define NV_HOST1X_MODULEID_DISPLAY       0x8
#define NV_HOST1X_MODULEID_DISPLAYB      0x9
#define NV_HOST1X_MODULEID_DISP          0x8
#define NV_HOST1X_MODULEID_DISPB         0x9
#define NV_HOST1X_MODULEID_HDMI          0xA
#define NV_HOST1X_MODULEID_TVO           0xB
#define NV_HOST1X_MODULEID_DSI           0xC
#define NV_HOST1X_MODULEID_VS            0xD
#define NV_HOST1X_MODULEID_VCI           0xE
#define NV_HOST1X_MODULEID_CSI           0xF
#define NV_HOST1X_MODULEID_DSIB          0x10
#define NV_HOST1X_MODULEID_GPU           0x11
#define NV_HOST1X_MODULEID_VIC           0xD
#define NV_HOST1X_MODULEID_MSENC         0x13
#define NV_HOST1X_MODULEID_TSEC          0x14
#define NV_HOST1X_MODULEID_SOR           0x15
#define NV_HOST1X_MODULEID_SOR1          0x16
#define NV_HOST1X_MODULEID_DPAUX         0x17
#define NV_HOST1X_MODULEID_ISP           0x18
#define NV_HOST1X_MODULEID_DISPLAYC      0x19
#define NV_HOST1X_MODULEID_ISPB          0x1A
#define NV_HOST1X_MODULEID_SYNCPT_CPU0   0x1E
#define NV_HOST1X_MODULEID_SYNCPT_CPU1   0x1F
#endif

