/*
 * Copyright (c) 2012, NVIDIA CORPORATION.  All rights reserved.
 *
 * NVIDIA CORPORATION and its licensors retain all intellectual property
 * and proprietary rights in and to this software, related documentation
 * and any modifications thereto.  Any use, reproduction, disclosure or
 * distribution of this software and related documentation without an express
 * license agreement from NVIDIA CORPORATION is strictly prohibited
 */

#ifndef ARDEV_T_XUSB_IDP_H_
#define ARDEV_T_XUSB_IDP_H_

#define XUSB_IDP_ULPI_PHY_VENDOR_ID_1_0                    _MK_ADDR_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_1_0_SECURE             0
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_1_0_WORD_COUNT         1
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_1_0_RESET_VAL          _MK_MASK_CONST(0xde)
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_1_0_RESET_MASK         _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_1_0_SW_DEFAULT_VAL     _MK_MASK_CONST(0xde)
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_1_0_SW_DEFAULT_MASK    _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_1_0_READ_MASK          _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_1_0_WRITE_MASK         _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_1_0_LOW_SHIFT           _MK_SHIFT_CONST(0)
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_1_0_LOW_FIELD          (_MK_SHIFT_CONST(0xff) << XUSB_IDP_ULPI_PHY_VENDOR_ID_1_0_LOW_SHIFT)
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_1_0_LOW_RANGE          7:0
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_1_0_LOW_WOFFSET        0
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_1_0_LOW_DEFAULT        (_MK_MASK_CONST(0xDE)
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_1_0_LOW_DEFAULT_MASK   (_MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_1_0_LOW_SW_DEFAULT     (_MK_MASK_CONST(0xDE)
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_1_0_LOW_SW_DEFAULT_MASK (_MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_1_0_LOW_NVIDIA         _MK_ENUM_CONST(0xDE)
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_2_0                    _MK_ADDR_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_2_0_SECURE             0
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_2_0_WORD_COUNT         1
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_2_0_RESET_VAL          _MK_MASK_CONST(0x10)
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_2_0_RESET_MASK         _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_2_0_SW_DEFAULT_VAL     _MK_MASK_CONST(0x10)
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_2_0_SW_DEFAULT_MASK    _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_2_0_READ_MASK          _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_2_0_WRITE_MASK         _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_2_0_HIGH_SHIFT          _MK_SHIFT_CONST(0)
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_2_0_HIGH_FIELD         (_MK_SHIFT_CONST(0xff) << XUSB_IDP_ULPI_PHY_VENDOR_ID_2_0_HIGH_SHIFT)
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_2_0_HIGH_RANGE         7:0
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_2_0_HIGH_WOFFSET       0
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_2_0_HIGH_DEFAULT       (_MK_MASK_CONST(0x10)
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_2_0_HIGH_DEFAULT_MASK  (_MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_2_0_HIGH_SW_DEFAULT    (_MK_MASK_CONST(0x10)
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_2_0_HIGH_SW_DEFAULT_MASK (_MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_VENDOR_ID_2_0_HIGH_NVIDIA        _MK_ENUM_CONST(0x10)
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_1_0                   _MK_ADDR_CONST(0x02)
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_1_0_SECURE            0
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_1_0_WORD_COUNT        1
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_1_0_RESET_VAL         _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_1_0_RESET_MASK        _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_1_0_SW_DEFAULT_VAL    _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_1_0_SW_DEFAULT_MASK   _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_1_0_READ_MASK         _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_1_0_WRITE_MASK        _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_1_0_LOW_SHIFT          _MK_SHIFT_CONST(0)
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_1_0_LOW_FIELD         (_MK_SHIFT_CONST(0xff) << XUSB_IDP_ULPI_PHY_PRODUCT_ID_1_0_LOW_SHIFT)
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_1_0_LOW_RANGE         7:0
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_1_0_LOW_WOFFSET       0
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_1_0_LOW_DEFAULT       (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_1_0_LOW_DEFAULT_MASK  (_MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_1_0_LOW_SW_DEFAULT    (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_1_0_LOW_SW_DEFAULT_MASK (_MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_2_0                   _MK_ADDR_CONST(0x03)
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_2_0_SECURE            0
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_2_0_WORD_COUNT        1
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_2_0_RESET_VAL         _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_2_0_RESET_MASK        _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_2_0_SW_DEFAULT_VAL    _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_2_0_SW_DEFAULT_MASK   _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_2_0_READ_MASK         _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_2_0_WRITE_MASK        _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_2_0_HIGH_SHIFT         _MK_SHIFT_CONST(0)
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_2_0_HIGH_FIELD        (_MK_SHIFT_CONST(0xff) << XUSB_IDP_ULPI_PHY_PRODUCT_ID_2_0_HIGH_SHIFT)
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_2_0_HIGH_RANGE        7:0
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_2_0_HIGH_WOFFSET      0
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_2_0_HIGH_DEFAULT      (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_2_0_HIGH_DEFAULT_MASK (_MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_2_0_HIGH_SW_DEFAULT   (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_PRODUCT_ID_2_0_HIGH_SW_DEFAULT_MASK (_MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0                         _MK_ADDR_CONST(0x04)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_SECURE                  0
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_WORD_COUNT              1
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_RESET_VAL               _MK_MASK_CONST(0x41)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_RESET_MASK              _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_SW_DEFAULT_VAL          _MK_MASK_CONST(0x41)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_SW_DEFAULT_MASK         _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_READ_MASK               _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_WRITE_MASK              _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_XCVRSEL_SHIFT            _MK_SHIFT_CONST(0)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_XCVRSEL_FIELD           (_MK_SHIFT_CONST(0x3) << XUSB_IDP_ULPI_PHY_FN_CTL_0_XCVRSEL_SHIFT)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_XCVRSEL_RANGE           1:0
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_XCVRSEL_WOFFSET         0
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_XCVRSEL_DEFAULT         (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_XCVRSEL_DEFAULT_MASK    (_MK_MASK_CONST(0x3)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_XCVRSEL_SW_DEFAULT      (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_XCVRSEL_SW_DEFAULT_MASK (_MK_MASK_CONST(0x3)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_XCVRSEL_HS              _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_XCVRSEL_FS              _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_XCVRSEL_LS              _MK_ENUM_CONST(0x02)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_XCVRSEL_FSLS            _MK_ENUM_CONST(0x03)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_TERMSEL_SHIFT            _MK_SHIFT_CONST(2)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_TERMSEL_FIELD           (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_FN_CTL_0_TERMSEL_SHIFT)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_TERMSEL_RANGE           2:2
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_TERMSEL_WOFFSET         0
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_TERMSEL_DEFAULT         (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_TERMSEL_DEFAULT_MASK    (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_TERMSEL_SW_DEFAULT      (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_TERMSEL_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_TERMSEL_DISABLED        _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_TERMSEL_ENABLED         _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_OPMODE_SHIFT             _MK_SHIFT_CONST(3)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_OPMODE_FIELD            (_MK_SHIFT_CONST(0x3) << XUSB_IDP_ULPI_PHY_FN_CTL_0_OPMODE_SHIFT)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_OPMODE_RANGE            4:3
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_OPMODE_WOFFSET          0
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_OPMODE_DEFAULT          (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_OPMODE_DEFAULT_MASK     (_MK_MASK_CONST(0x3)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_OPMODE_SW_DEFAULT       (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_OPMODE_SW_DEFAULT_MASK  (_MK_MASK_CONST(0x3)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_OPMODE_NORMAL_AUTO      _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_OPMODE_NON_DRV          _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_OPMODE_DIS_ENC          _MK_ENUM_CONST(0x02)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_OPMODE_NORMAL           _MK_ENUM_CONST(0x03)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_RESET_SHIFT              _MK_SHIFT_CONST(5)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_RESET_FIELD             (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_FN_CTL_0_RESET_SHIFT)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_RESET_RANGE             5:5
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_RESET_WOFFSET           0
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_RESET_DEFAULT           (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_RESET_DEFAULT_MASK      (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_RESET_SW_DEFAULT        (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_RESET_SW_DEFAULT_MASK   (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_RESET_DISABLED          _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_RESET_ENABLED           _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_SUSPEND_SHIFT            _MK_SHIFT_CONST(6)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_SUSPEND_FIELD           (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_FN_CTL_0_SUSPEND_SHIFT)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_SUSPEND_RANGE           6:6
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_SUSPEND_WOFFSET         0
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_SUSPEND_DEFAULT         (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_SUSPEND_DEFAULT_MASK    (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_SUSPEND_SW_DEFAULT      (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_SUSPEND_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_SUSPEND_ENABLED         _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_SUSPEND_DISABLED        _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_RSVD_SHIFT               _MK_SHIFT_CONST(7)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_RSVD_FIELD              (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_FN_CTL_0_RSVD_SHIFT)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_RSVD_RANGE              7:7
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_RSVD_WOFFSET            0
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_RSVD_DEFAULT            (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_RSVD_DEFAULT_MASK       (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_RSVD_SW_DEFAULT         (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_FN_CTL_0_RSVD_SW_DEFAULT_MASK    (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0                       _MK_ADDR_CONST(0x07)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_SECURE                0
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_WORD_COUNT            1
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_RESET_VAL             _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_RESET_MASK            _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_SW_DEFAULT_VAL        _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_SW_DEFAULT_MASK       _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_READ_MASK             _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_WRITE_MASK            _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_6PIN_FSLS_SERMODE_SHIFT  _MK_SHIFT_CONST(0)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_6PIN_FSLS_SERMODE_FIELD (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_INTF_CTL_0_6PIN_FSLS_SERMODE_SHIFT)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_6PIN_FSLS_SERMODE_RANGE 0:0
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_6PIN_FSLS_SERMODE_WOFFSET 0
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_6PIN_FSLS_SERMODE_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_6PIN_FSLS_SERMODE_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_6PIN_FSLS_SERMODE_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_6PIN_FSLS_SERMODE_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_6PIN_FSLS_SERMODE_DISABLED _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_6PIN_FSLS_SERMODE_ENABLED _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_3PIN_FSLS_SERMODE_SHIFT  _MK_SHIFT_CONST(1)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_3PIN_FSLS_SERMODE_FIELD (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_INTF_CTL_0_3PIN_FSLS_SERMODE_SHIFT)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_3PIN_FSLS_SERMODE_RANGE 1:1
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_3PIN_FSLS_SERMODE_WOFFSET 0
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_3PIN_FSLS_SERMODE_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_3PIN_FSLS_SERMODE_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_3PIN_FSLS_SERMODE_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_3PIN_FSLS_SERMODE_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_3PIN_FSLS_SERMODE_DISABLED _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_3PIN_FSLS_SERMODE_ENABLED _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_CARKIT_MODE_SHIFT      _MK_SHIFT_CONST(2)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_CARKIT_MODE_FIELD     (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_INTF_CTL_0_CARKIT_MODE_SHIFT)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_CARKIT_MODE_RANGE     2:2
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_CARKIT_MODE_WOFFSET   0
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_CARKIT_MODE_DEFAULT   (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_CARKIT_MODE_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_CARKIT_MODE_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_CARKIT_MODE_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_CARKIT_MODE_DISABLED  _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_CARKIT_MODE_ENABLED   _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_CLKSUSPENDM_SHIFT      _MK_SHIFT_CONST(3)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_CLKSUSPENDM_FIELD     (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_INTF_CTL_0_CLKSUSPENDM_SHIFT)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_CLKSUSPENDM_RANGE     3:3
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_CLKSUSPENDM_WOFFSET   0
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_CLKSUSPENDM_DEFAULT   (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_CLKSUSPENDM_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_CLKSUSPENDM_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_CLKSUSPENDM_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_CLKSUSPENDM_DISABLED  _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_CLKSUSPENDM_ENABLED   _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_AUTORESUME_SHIFT       _MK_SHIFT_CONST(4)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_AUTORESUME_FIELD      (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_INTF_CTL_0_AUTORESUME_SHIFT)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_AUTORESUME_RANGE      4:4
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_AUTORESUME_WOFFSET    0
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_AUTORESUME_DEFAULT    (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_AUTORESUME_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_AUTORESUME_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_AUTORESUME_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_AUTORESUME_DISABLED   _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_AUTORESUME_ENABLED    _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INDICATOR_COMP_SHIFT   _MK_SHIFT_CONST(5)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INDICATOR_COMP_FIELD  (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_INTF_CTL_0_INDICATOR_COMP_SHIFT)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INDICATOR_COMP_RANGE  5:5
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INDICATOR_COMP_WOFFSET 0
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INDICATOR_COMP_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INDICATOR_COMP_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INDICATOR_COMP_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INDICATOR_COMP_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INDICATOR_COMP_DISABLED _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INDICATOR_COMP_ENABLED _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INDICATOR_PASS_SHIFT   _MK_SHIFT_CONST(6)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INDICATOR_PASS_FIELD  (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_INTF_CTL_0_INDICATOR_PASS_SHIFT)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INDICATOR_PASS_RANGE  6:6
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INDICATOR_PASS_WOFFSET 0
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INDICATOR_PASS_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INDICATOR_PASS_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INDICATOR_PASS_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INDICATOR_PASS_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INDICATOR_PASS_DISABLED _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INDICATOR_PASS_ENABLED _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INTF_PROTECT_DISABLE_SHIFT  _MK_SHIFT_CONST(7)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INTF_PROTECT_DISABLE_FIELD (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_INTF_CTL_0_INTF_PROTECT_DISABLE_SHIFT)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INTF_PROTECT_DISABLE_RANGE 7:7
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INTF_PROTECT_DISABLE_WOFFSET 0
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INTF_PROTECT_DISABLE_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INTF_PROTECT_DISABLE_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INTF_PROTECT_DISABLE_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INTF_PROTECT_DISABLE_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INTF_PROTECT_DISABLE_OFF _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_CTL_0_INTF_PROTECT_DISABLE_ON _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0                        _MK_ADDR_CONST(0x0A)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_SECURE                 0
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_WORD_COUNT             1
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_RESET_VAL              _MK_MASK_CONST(0x6)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_RESET_MASK             _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_SW_DEFAULT_VAL         _MK_MASK_CONST(0x6)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_SW_DEFAULT_MASK        _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_READ_MASK              _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_WRITE_MASK             _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_IDPULLUP_SHIFT          _MK_SHIFT_CONST(0)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_IDPULLUP_FIELD         (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_OTG_CTL_0_IDPULLUP_SHIFT)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_IDPULLUP_RANGE         0:0
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_IDPULLUP_WOFFSET       0
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_IDPULLUP_DEFAULT       (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_IDPULLUP_DEFAULT_MASK  (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_IDPULLUP_SW_DEFAULT    (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_IDPULLUP_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_IDPULLUP_DISABLED      _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_IDPULLUP_ENABLED       _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DPPULLDOWN_SHIFT        _MK_SHIFT_CONST(1)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DPPULLDOWN_FIELD       (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_OTG_CTL_0_DPPULLDOWN_SHIFT)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DPPULLDOWN_RANGE       1:1
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DPPULLDOWN_WOFFSET     0
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DPPULLDOWN_DEFAULT     (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DPPULLDOWN_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DPPULLDOWN_SW_DEFAULT  (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DPPULLDOWN_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DPPULLDOWN_DISABLED    _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DPPULLDOWN_ENABLED     _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DMPULLDOWN_SHIFT        _MK_SHIFT_CONST(2)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DMPULLDOWN_FIELD       (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_OTG_CTL_0_DMPULLDOWN_SHIFT)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DMPULLDOWN_RANGE       2:2
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DMPULLDOWN_WOFFSET     0
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DMPULLDOWN_DEFAULT     (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DMPULLDOWN_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DMPULLDOWN_SW_DEFAULT  (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DMPULLDOWN_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DMPULLDOWN_DISABLED    _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DMPULLDOWN_ENABLED     _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DISCHRGVBUS_SHIFT       _MK_SHIFT_CONST(3)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DISCHRGVBUS_FIELD      (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_OTG_CTL_0_DISCHRGVBUS_SHIFT)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DISCHRGVBUS_RANGE      3:3
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DISCHRGVBUS_WOFFSET    0
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DISCHRGVBUS_DEFAULT    (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DISCHRGVBUS_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DISCHRGVBUS_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DISCHRGVBUS_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DISCHRGVBUS_DISABLED   _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DISCHRGVBUS_ENABLED    _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_CHRGVBUS_SHIFT          _MK_SHIFT_CONST(4)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_CHRGVBUS_FIELD         (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_OTG_CTL_0_CHRGVBUS_SHIFT)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_CHRGVBUS_RANGE         4:4
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_CHRGVBUS_WOFFSET       0
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_CHRGVBUS_DEFAULT       (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_CHRGVBUS_DEFAULT_MASK  (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_CHRGVBUS_SW_DEFAULT    (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_CHRGVBUS_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_CHRGVBUS_DISABLED      _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_CHRGVBUS_ENABLED       _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DRVVBUS_SHIFT           _MK_SHIFT_CONST(5)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DRVVBUS_FIELD          (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_OTG_CTL_0_DRVVBUS_SHIFT)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DRVVBUS_RANGE          5:5
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DRVVBUS_WOFFSET        0
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DRVVBUS_DEFAULT        (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DRVVBUS_DEFAULT_MASK   (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DRVVBUS_SW_DEFAULT     (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DRVVBUS_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DRVVBUS_DISABLED       _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DRVVBUS_ENABLED        _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DRVVBUSEXT_SHIFT        _MK_SHIFT_CONST(6)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DRVVBUSEXT_FIELD       (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_OTG_CTL_0_DRVVBUSEXT_SHIFT)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DRVVBUSEXT_RANGE       6:6
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DRVVBUSEXT_WOFFSET     0
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DRVVBUSEXT_DEFAULT     (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DRVVBUSEXT_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DRVVBUSEXT_SW_DEFAULT  (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DRVVBUSEXT_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DRVVBUSEXT_DISABLED    _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_DRVVBUSEXT_ENABLED     _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_EXTVBUSIND_SHIFT        _MK_SHIFT_CONST(7)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_EXTVBUSIND_FIELD       (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_OTG_CTL_0_EXTVBUSIND_SHIFT)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_EXTVBUSIND_RANGE       7:7
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_EXTVBUSIND_WOFFSET     0
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_EXTVBUSIND_DEFAULT     (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_EXTVBUSIND_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_EXTVBUSIND_SW_DEFAULT  (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_EXTVBUSIND_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_EXTVBUSIND_DISABLED    _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_OTG_CTL_0_EXTVBUSIND_ENABLED     _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTR_0                           _MK_ADDR_CONST(0x0D)
#define XUSB_IDP_ULPI_PHY_INTR_0_SECURE                    0
#define XUSB_IDP_ULPI_PHY_INTR_0_WORD_COUNT                1
#define XUSB_IDP_ULPI_PHY_INTR_0_RESET_VAL                 _MK_MASK_CONST(0x1f)
#define XUSB_IDP_ULPI_PHY_INTR_0_RESET_MASK                _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_INTR_0_SW_DEFAULT_VAL            _MK_MASK_CONST(0x1f)
#define XUSB_IDP_ULPI_PHY_INTR_0_SW_DEFAULT_MASK           _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_INTR_0_READ_MASK                 _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_INTR_0_WRITE_MASK                _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_INTR_0_HOSTDISC_RISE_SHIFT        _MK_SHIFT_CONST(0)
#define XUSB_IDP_ULPI_PHY_INTR_0_HOSTDISC_RISE_FIELD       (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_INTR_0_HOSTDISC_RISE_SHIFT)
#define XUSB_IDP_ULPI_PHY_INTR_0_HOSTDISC_RISE_RANGE       0:0
#define XUSB_IDP_ULPI_PHY_INTR_0_HOSTDISC_RISE_WOFFSET     0
#define XUSB_IDP_ULPI_PHY_INTR_0_HOSTDISC_RISE_DEFAULT     (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTR_0_HOSTDISC_RISE_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTR_0_HOSTDISC_RISE_SW_DEFAULT  (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTR_0_HOSTDISC_RISE_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTR_0_HOSTDISC_RISE_DISABLED    _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTR_0_HOSTDISC_RISE_ENABLED     _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTR_0_VBUSVLD_RISE_SHIFT         _MK_SHIFT_CONST(1)
#define XUSB_IDP_ULPI_PHY_INTR_0_VBUSVLD_RISE_FIELD        (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_INTR_0_VBUSVLD_RISE_SHIFT)
#define XUSB_IDP_ULPI_PHY_INTR_0_VBUSVLD_RISE_RANGE        1:1
#define XUSB_IDP_ULPI_PHY_INTR_0_VBUSVLD_RISE_WOFFSET      0
#define XUSB_IDP_ULPI_PHY_INTR_0_VBUSVLD_RISE_DEFAULT      (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTR_0_VBUSVLD_RISE_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTR_0_VBUSVLD_RISE_SW_DEFAULT   (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTR_0_VBUSVLD_RISE_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTR_0_VBUSVLD_RISE_DISABLED     _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTR_0_VBUSVLD_RISE_ENABLED      _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTR_0_SESSVLD_RISE_SHIFT         _MK_SHIFT_CONST(2)
#define XUSB_IDP_ULPI_PHY_INTR_0_SESSVLD_RISE_FIELD        (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_INTR_0_SESSVLD_RISE_SHIFT)
#define XUSB_IDP_ULPI_PHY_INTR_0_SESSVLD_RISE_RANGE        2:2
#define XUSB_IDP_ULPI_PHY_INTR_0_SESSVLD_RISE_WOFFSET      0
#define XUSB_IDP_ULPI_PHY_INTR_0_SESSVLD_RISE_DEFAULT      (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTR_0_SESSVLD_RISE_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTR_0_SESSVLD_RISE_SW_DEFAULT   (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTR_0_SESSVLD_RISE_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTR_0_SESSVLD_RISE_DISABLED     _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTR_0_SESSVLD_RISE_ENABLED      _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTR_0_SESSEND_RISE_SHIFT         _MK_SHIFT_CONST(3)
#define XUSB_IDP_ULPI_PHY_INTR_0_SESSEND_RISE_FIELD        (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_INTR_0_SESSEND_RISE_SHIFT)
#define XUSB_IDP_ULPI_PHY_INTR_0_SESSEND_RISE_RANGE        3:3
#define XUSB_IDP_ULPI_PHY_INTR_0_SESSEND_RISE_WOFFSET      0
#define XUSB_IDP_ULPI_PHY_INTR_0_SESSEND_RISE_DEFAULT      (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTR_0_SESSEND_RISE_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTR_0_SESSEND_RISE_SW_DEFAULT   (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTR_0_SESSEND_RISE_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTR_0_SESSEND_RISE_DISABLED     _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTR_0_SESSEND_RISE_ENABLED      _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTR_0_IDGND_RISE_SHIFT           _MK_SHIFT_CONST(4)
#define XUSB_IDP_ULPI_PHY_INTR_0_IDGND_RISE_FIELD          (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_INTR_0_IDGND_RISE_SHIFT)
#define XUSB_IDP_ULPI_PHY_INTR_0_IDGND_RISE_RANGE          4:4
#define XUSB_IDP_ULPI_PHY_INTR_0_IDGND_RISE_WOFFSET        0
#define XUSB_IDP_ULPI_PHY_INTR_0_IDGND_RISE_DEFAULT        (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTR_0_IDGND_RISE_DEFAULT_MASK   (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTR_0_IDGND_RISE_SW_DEFAULT     (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTR_0_IDGND_RISE_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTR_0_IDGND_RISE_DISABLED       _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTR_0_IDGND_RISE_ENABLED        _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTR_0_RSVD_SHIFT                 _MK_SHIFT_CONST(5)
#define XUSB_IDP_ULPI_PHY_INTR_0_RSVD_FIELD                (_MK_SHIFT_CONST(0x7) << XUSB_IDP_ULPI_PHY_INTR_0_RSVD_SHIFT)
#define XUSB_IDP_ULPI_PHY_INTR_0_RSVD_RANGE                7:5
#define XUSB_IDP_ULPI_PHY_INTR_0_RSVD_WOFFSET              0
#define XUSB_IDP_ULPI_PHY_INTR_0_RSVD_DEFAULT              (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTR_0_RSVD_DEFAULT_MASK         (_MK_MASK_CONST(0x7)
#define XUSB_IDP_ULPI_PHY_INTR_0_RSVD_SW_DEFAULT           (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTR_0_RSVD_SW_DEFAULT_MASK      (_MK_MASK_CONST(0x7)
#define XUSB_IDP_ULPI_PHY_INTF_0                           _MK_ADDR_CONST(0x10)
#define XUSB_IDP_ULPI_PHY_INTF_0_SECURE                    0
#define XUSB_IDP_ULPI_PHY_INTF_0_WORD_COUNT                1
#define XUSB_IDP_ULPI_PHY_INTF_0_RESET_VAL                 _MK_MASK_CONST(0x1f)
#define XUSB_IDP_ULPI_PHY_INTF_0_RESET_MASK                _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_INTF_0_SW_DEFAULT_VAL            _MK_MASK_CONST(0x1f)
#define XUSB_IDP_ULPI_PHY_INTF_0_SW_DEFAULT_MASK           _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_INTF_0_READ_MASK                 _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_INTF_0_WRITE_MASK                _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_INTF_0_HOSTDISC_FALL_SHIFT        _MK_SHIFT_CONST(0)
#define XUSB_IDP_ULPI_PHY_INTF_0_HOSTDISC_FALL_FIELD       (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_INTF_0_HOSTDISC_FALL_SHIFT)
#define XUSB_IDP_ULPI_PHY_INTF_0_HOSTDISC_FALL_RANGE       0:0
#define XUSB_IDP_ULPI_PHY_INTF_0_HOSTDISC_FALL_WOFFSET     0
#define XUSB_IDP_ULPI_PHY_INTF_0_HOSTDISC_FALL_DEFAULT     (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTF_0_HOSTDISC_FALL_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTF_0_HOSTDISC_FALL_SW_DEFAULT  (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTF_0_HOSTDISC_FALL_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTF_0_HOSTDISC_FALL_DISABLED    _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_0_HOSTDISC_FALL_ENABLED     _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTF_0_VBUSVLD_FALL_SHIFT         _MK_SHIFT_CONST(1)
#define XUSB_IDP_ULPI_PHY_INTF_0_VBUSVLD_FALL_FIELD        (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_INTF_0_VBUSVLD_FALL_SHIFT)
#define XUSB_IDP_ULPI_PHY_INTF_0_VBUSVLD_FALL_RANGE        1:1
#define XUSB_IDP_ULPI_PHY_INTF_0_VBUSVLD_FALL_WOFFSET      0
#define XUSB_IDP_ULPI_PHY_INTF_0_VBUSVLD_FALL_DEFAULT      (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTF_0_VBUSVLD_FALL_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTF_0_VBUSVLD_FALL_SW_DEFAULT   (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTF_0_VBUSVLD_FALL_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTF_0_VBUSVLD_FALL_DISABLED     _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_0_VBUSVLD_FALL_ENABLED      _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTF_0_SESSVLD_FALL_SHIFT         _MK_SHIFT_CONST(2)
#define XUSB_IDP_ULPI_PHY_INTF_0_SESSVLD_FALL_FIELD        (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_INTF_0_SESSVLD_FALL_SHIFT)
#define XUSB_IDP_ULPI_PHY_INTF_0_SESSVLD_FALL_RANGE        2:2
#define XUSB_IDP_ULPI_PHY_INTF_0_SESSVLD_FALL_WOFFSET      0
#define XUSB_IDP_ULPI_PHY_INTF_0_SESSVLD_FALL_DEFAULT      (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTF_0_SESSVLD_FALL_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTF_0_SESSVLD_FALL_SW_DEFAULT   (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTF_0_SESSVLD_FALL_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTF_0_SESSVLD_FALL_DISABLED     _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_0_SESSVLD_FALL_ENABLED      _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTF_0_SESSEND_FALL_SHIFT         _MK_SHIFT_CONST(3)
#define XUSB_IDP_ULPI_PHY_INTF_0_SESSEND_FALL_FIELD        (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_INTF_0_SESSEND_FALL_SHIFT)
#define XUSB_IDP_ULPI_PHY_INTF_0_SESSEND_FALL_RANGE        3:3
#define XUSB_IDP_ULPI_PHY_INTF_0_SESSEND_FALL_WOFFSET      0
#define XUSB_IDP_ULPI_PHY_INTF_0_SESSEND_FALL_DEFAULT      (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTF_0_SESSEND_FALL_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTF_0_SESSEND_FALL_SW_DEFAULT   (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTF_0_SESSEND_FALL_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTF_0_SESSEND_FALL_DISABLED     _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_0_SESSEND_FALL_ENABLED      _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTF_0_IDGND_FALL_SHIFT           _MK_SHIFT_CONST(4)
#define XUSB_IDP_ULPI_PHY_INTF_0_IDGND_FALL_FIELD          (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_INTF_0_IDGND_FALL_SHIFT)
#define XUSB_IDP_ULPI_PHY_INTF_0_IDGND_FALL_RANGE          4:4
#define XUSB_IDP_ULPI_PHY_INTF_0_IDGND_FALL_WOFFSET        0
#define XUSB_IDP_ULPI_PHY_INTF_0_IDGND_FALL_DEFAULT        (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTF_0_IDGND_FALL_DEFAULT_MASK   (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTF_0_IDGND_FALL_SW_DEFAULT     (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTF_0_IDGND_FALL_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INTF_0_IDGND_FALL_DISABLED       _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_0_IDGND_FALL_ENABLED        _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INTF_0_RSVD_SHIFT                 _MK_SHIFT_CONST(5)
#define XUSB_IDP_ULPI_PHY_INTF_0_RSVD_FIELD                (_MK_SHIFT_CONST(0x7) << XUSB_IDP_ULPI_PHY_INTF_0_RSVD_SHIFT)
#define XUSB_IDP_ULPI_PHY_INTF_0_RSVD_RANGE                7:5
#define XUSB_IDP_ULPI_PHY_INTF_0_RSVD_WOFFSET              0
#define XUSB_IDP_ULPI_PHY_INTF_0_RSVD_DEFAULT              (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_0_RSVD_DEFAULT_MASK         (_MK_MASK_CONST(0x7)
#define XUSB_IDP_ULPI_PHY_INTF_0_RSVD_SW_DEFAULT           (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INTF_0_RSVD_SW_DEFAULT_MASK      (_MK_MASK_CONST(0x7)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0                     _MK_ADDR_CONST(0x13)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_SECURE              0
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_WORD_COUNT          1
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_RESET_VAL           _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_RESET_MASK          _MK_MASK_CONST(0x1f)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_SW_DEFAULT_VAL      _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_SW_DEFAULT_MASK     _MK_MASK_CONST(0x1f)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_READ_MASK           _MK_MASK_CONST(0x1f)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_WRITE_MASK          _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_HOSTDISC_SHIFT       _MK_SHIFT_CONST(0)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_HOSTDISC_FIELD      (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_INT_STATUS_0_HOSTDISC_SHIFT)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_HOSTDISC_RANGE      0:0
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_HOSTDISC_WOFFSET    0
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_HOSTDISC_DEFAULT    (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_HOSTDISC_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_HOSTDISC_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_HOSTDISC_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_HOSTDISC_LOW        _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_HOSTDISC_HIGH       _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_VBUSVLD_SHIFT        _MK_SHIFT_CONST(1)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_VBUSVLD_FIELD       (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_INT_STATUS_0_VBUSVLD_SHIFT)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_VBUSVLD_RANGE       1:1
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_VBUSVLD_WOFFSET     0
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_VBUSVLD_DEFAULT     (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_VBUSVLD_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_VBUSVLD_SW_DEFAULT  (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_VBUSVLD_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_VBUSVLD_LOW         _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_VBUSVLD_HIGH        _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_SESSVLD_SHIFT        _MK_SHIFT_CONST(2)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_SESSVLD_FIELD       (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_INT_STATUS_0_SESSVLD_SHIFT)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_SESSVLD_RANGE       2:2
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_SESSVLD_WOFFSET     0
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_SESSVLD_DEFAULT     (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_SESSVLD_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_SESSVLD_SW_DEFAULT  (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_SESSVLD_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_SESSVLD_LOW         _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_SESSVLD_HIGH        _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_SESSEND_SHIFT        _MK_SHIFT_CONST(3)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_SESSEND_FIELD       (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_INT_STATUS_0_SESSEND_SHIFT)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_SESSEND_RANGE       3:3
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_SESSEND_WOFFSET     0
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_SESSEND_DEFAULT     (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_SESSEND_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_SESSEND_SW_DEFAULT  (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_SESSEND_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_SESSEND_LOW         _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_SESSEND_HIGH        _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_IDGND_SHIFT          _MK_SHIFT_CONST(4)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_IDGND_FIELD         (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_INT_STATUS_0_IDGND_SHIFT)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_IDGND_RANGE         4:4
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_IDGND_WOFFSET       0
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_IDGND_DEFAULT       (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_IDGND_DEFAULT_MASK  (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_IDGND_SW_DEFAULT    (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_IDGND_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_IDGND_LOW           _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_STATUS_0_IDGND_HIGH          _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0                      _MK_ADDR_CONST(0x14)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_SECURE               0
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_WORD_COUNT           1
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_RESET_VAL            _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_RESET_MASK           _MK_MASK_CONST(0x1f)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_SW_DEFAULT_VAL       _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_SW_DEFAULT_MASK      _MK_MASK_CONST(0x1f)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_READ_MASK            _MK_MASK_CONST(0x1f)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_WRITE_MASK           _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_HOSTDISC_SHIFT        _MK_SHIFT_CONST(0)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_HOSTDISC_FIELD       (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_INT_LATCH_0_HOSTDISC_SHIFT)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_HOSTDISC_RANGE       0:0
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_HOSTDISC_WOFFSET     0
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_HOSTDISC_DEFAULT     (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_HOSTDISC_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_HOSTDISC_SW_DEFAULT  (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_HOSTDISC_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_HOSTDISC_LOW         _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_HOSTDISC_HIGH        _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_VBUSVLD_SHIFT         _MK_SHIFT_CONST(1)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_VBUSVLD_FIELD        (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_INT_LATCH_0_VBUSVLD_SHIFT)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_VBUSVLD_RANGE        1:1
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_VBUSVLD_WOFFSET      0
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_VBUSVLD_DEFAULT      (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_VBUSVLD_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_VBUSVLD_SW_DEFAULT   (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_VBUSVLD_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_VBUSVLD_LOW          _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_VBUSVLD_HIGH         _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_SESSVLD_SHIFT         _MK_SHIFT_CONST(2)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_SESSVLD_FIELD        (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_INT_LATCH_0_SESSVLD_SHIFT)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_SESSVLD_RANGE        2:2
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_SESSVLD_WOFFSET      0
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_SESSVLD_DEFAULT      (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_SESSVLD_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_SESSVLD_SW_DEFAULT   (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_SESSVLD_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_SESSVLD_LOW          _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_SESSVLD_HIGH         _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_SESSEND_SHIFT         _MK_SHIFT_CONST(3)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_SESSEND_FIELD        (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_INT_LATCH_0_SESSEND_SHIFT)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_SESSEND_RANGE        3:3
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_SESSEND_WOFFSET      0
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_SESSEND_DEFAULT      (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_SESSEND_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_SESSEND_SW_DEFAULT   (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_SESSEND_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_SESSEND_LOW          _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_SESSEND_HIGH         _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_IDGND_SHIFT           _MK_SHIFT_CONST(4)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_IDGND_FIELD          (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_INT_LATCH_0_IDGND_SHIFT)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_IDGND_RANGE          4:4
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_IDGND_WOFFSET        0
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_IDGND_DEFAULT        (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_IDGND_DEFAULT_MASK   (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_IDGND_SW_DEFAULT     (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_IDGND_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_IDGND_LOW            _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_INT_LATCH_0_IDGND_HIGH           _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_DEBUG_0                          _MK_ADDR_CONST(0x15)
#define XUSB_IDP_ULPI_PHY_DEBUG_0_SECURE                   0
#define XUSB_IDP_ULPI_PHY_DEBUG_0_WORD_COUNT               1
#define XUSB_IDP_ULPI_PHY_DEBUG_0_RESET_VAL                _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_DEBUG_0_RESET_MASK               _MK_MASK_CONST(0x3)
#define XUSB_IDP_ULPI_PHY_DEBUG_0_SW_DEFAULT_VAL           _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_DEBUG_0_SW_DEFAULT_MASK          _MK_MASK_CONST(0x3)
#define XUSB_IDP_ULPI_PHY_DEBUG_0_READ_MASK                _MK_MASK_CONST(0x3)
#define XUSB_IDP_ULPI_PHY_DEBUG_0_WRITE_MASK               _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_DEBUG_0_LINESTATE0_SHIFT          _MK_SHIFT_CONST(0)
#define XUSB_IDP_ULPI_PHY_DEBUG_0_LINESTATE0_FIELD         (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_DEBUG_0_LINESTATE0_SHIFT)
#define XUSB_IDP_ULPI_PHY_DEBUG_0_LINESTATE0_RANGE         0:0
#define XUSB_IDP_ULPI_PHY_DEBUG_0_LINESTATE0_WOFFSET       0
#define XUSB_IDP_ULPI_PHY_DEBUG_0_LINESTATE0_DEFAULT       (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_DEBUG_0_LINESTATE0_DEFAULT_MASK  (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_DEBUG_0_LINESTATE0_SW_DEFAULT    (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_DEBUG_0_LINESTATE0_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_DEBUG_0_LINESTATE0_LOW           _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_DEBUG_0_LINESTATE0_HIGH          _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_DEBUG_0_LINESTATE1_SHIFT          _MK_SHIFT_CONST(1)
#define XUSB_IDP_ULPI_PHY_DEBUG_0_LINESTATE1_FIELD         (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_DEBUG_0_LINESTATE1_SHIFT)
#define XUSB_IDP_ULPI_PHY_DEBUG_0_LINESTATE1_RANGE         1:1
#define XUSB_IDP_ULPI_PHY_DEBUG_0_LINESTATE1_WOFFSET       0
#define XUSB_IDP_ULPI_PHY_DEBUG_0_LINESTATE1_DEFAULT       (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_DEBUG_0_LINESTATE1_DEFAULT_MASK  (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_DEBUG_0_LINESTATE1_SW_DEFAULT    (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_DEBUG_0_LINESTATE1_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_DEBUG_0_LINESTATE1_LOW           _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_DEBUG_0_LINESTATE1_HIGH          _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_SCRATCH_0                        _MK_ADDR_CONST(0x16)
#define XUSB_IDP_ULPI_PHY_SCRATCH_0_SECURE                 0
#define XUSB_IDP_ULPI_PHY_SCRATCH_0_WORD_COUNT             1
#define XUSB_IDP_ULPI_PHY_SCRATCH_0_RESET_VAL              _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_SCRATCH_0_RESET_MASK             _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_SCRATCH_0_SW_DEFAULT_VAL         _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_SCRATCH_0_SW_DEFAULT_MASK        _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_SCRATCH_0_READ_MASK              _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_SCRATCH_0_WRITE_MASK             _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_SCRATCH_0_SCRATCH_SHIFT           _MK_SHIFT_CONST(0)
#define XUSB_IDP_ULPI_PHY_SCRATCH_0_SCRATCH_FIELD          (_MK_SHIFT_CONST(0xff) << XUSB_IDP_ULPI_PHY_SCRATCH_0_SCRATCH_SHIFT)
#define XUSB_IDP_ULPI_PHY_SCRATCH_0_SCRATCH_RANGE          7:0
#define XUSB_IDP_ULPI_PHY_SCRATCH_0_SCRATCH_WOFFSET        0
#define XUSB_IDP_ULPI_PHY_SCRATCH_0_SCRATCH_DEFAULT        (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_SCRATCH_0_SCRATCH_DEFAULT_MASK   (_MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_SCRATCH_0_SCRATCH_SW_DEFAULT     (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_SCRATCH_0_SCRATCH_SW_DEFAULT_MASK (_MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0                     _MK_ADDR_CONST(0x19)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_SECURE              0
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_WORD_COUNT          1
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_RESET_VAL           _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_RESET_MASK          _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_SW_DEFAULT_VAL      _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_SW_DEFAULT_MASK     _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_READ_MASK           _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_WRITE_MASK          _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_PWR_SHIFT            _MK_SHIFT_CONST(0)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_PWR_FIELD           (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_PWR_SHIFT)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_PWR_RANGE           0:0
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_PWR_WOFFSET         0
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_PWR_DEFAULT         (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_PWR_DEFAULT_MASK    (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_PWR_SW_DEFAULT      (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_PWR_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_PWR_OFF             _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_PWR_ON              _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_IDGNDDRV_SHIFT       _MK_SHIFT_CONST(1)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_IDGNDDRV_FIELD      (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_IDGNDDRV_SHIFT)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_IDGNDDRV_RANGE      1:1
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_IDGNDDRV_WOFFSET    0
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_IDGNDDRV_DEFAULT    (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_IDGNDDRV_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_IDGNDDRV_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_IDGNDDRV_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_IDGNDDRV_OFF        _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_IDGNDDRV_ON         _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_TXDEN_SHIFT          _MK_SHIFT_CONST(2)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_TXDEN_FIELD         (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_TXDEN_SHIFT)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_TXDEN_RANGE         2:2
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_TXDEN_WOFFSET       0
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_TXDEN_DEFAULT       (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_TXDEN_DEFAULT_MASK  (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_TXDEN_SW_DEFAULT    (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_TXDEN_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_TXDEN_OFF           _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_TXDEN_ON            _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_RXDEN_SHIFT          _MK_SHIFT_CONST(3)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_RXDEN_FIELD         (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_RXDEN_SHIFT)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_RXDEN_RANGE         3:3
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_RXDEN_WOFFSET       0
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_RXDEN_DEFAULT       (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_RXDEN_DEFAULT_MASK  (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_RXDEN_SW_DEFAULT    (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_RXDEN_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_RXDEN_OFF           _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_RXDEN_ON            _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_SPKLEFTON_SHIFT      _MK_SHIFT_CONST(4)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_SPKLEFTON_FIELD     (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_SPKLEFTON_SHIFT)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_SPKLEFTON_RANGE     4:4
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_SPKLEFTON_WOFFSET   0
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_SPKLEFTON_DEFAULT   (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_SPKLEFTON_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_SPKLEFTON_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_SPKLEFTON_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_SPKLEFTON_OFF       _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_SPKLEFTON_ON        _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_SPKRIGHTON_SHIFT     _MK_SHIFT_CONST(5)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_SPKRIGHTON_FIELD    (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_SPKRIGHTON_SHIFT)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_SPKRIGHTON_RANGE    5:5
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_SPKRIGHTON_WOFFSET  0
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_SPKRIGHTON_DEFAULT  (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_SPKRIGHTON_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_SPKRIGHTON_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_SPKRIGHTON_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_SPKRIGHTON_OFF      _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_SPKRIGHTON_ON       _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_MICEN_SHIFT          _MK_SHIFT_CONST(6)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_MICEN_FIELD         (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_MICEN_SHIFT)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_MICEN_RANGE         6:6
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_MICEN_WOFFSET       0
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_MICEN_DEFAULT       (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_MICEN_DEFAULT_MASK  (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_MICEN_SW_DEFAULT    (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_MICEN_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_MICEN_OFF           _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_MICEN_ON            _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_RSVD_SHIFT           _MK_SHIFT_CONST(7)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_RSVD_FIELD          (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_RSVD_SHIFT)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_RSVD_RANGE          7:7
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_RSVD_WOFFSET        0
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_RSVD_DEFAULT        (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_RSVD_DEFAULT_MASK   (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_RSVD_SW_DEFAULT     (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_CTL_0_RSVD_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_INTDLY_0                  _MK_ADDR_CONST(0x1C)
#define XUSB_IDP_ULPI_PHY_CARKIT_INTDLY_0_SECURE           0
#define XUSB_IDP_ULPI_PHY_CARKIT_INTDLY_0_WORD_COUNT       1
#define XUSB_IDP_ULPI_PHY_CARKIT_INTDLY_0_RESET_VAL        _MK_MASK_CONST(0x18)
#define XUSB_IDP_ULPI_PHY_CARKIT_INTDLY_0_RESET_MASK       _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_CARKIT_INTDLY_0_SW_DEFAULT_VAL   _MK_MASK_CONST(0x18)
#define XUSB_IDP_ULPI_PHY_CARKIT_INTDLY_0_SW_DEFAULT_MASK  _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_CARKIT_INTDLY_0_READ_MASK        _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_CARKIT_INTDLY_0_WRITE_MASK       _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_CARKIT_INTDLY_0_DLY_SHIFT         _MK_SHIFT_CONST(0)
#define XUSB_IDP_ULPI_PHY_CARKIT_INTDLY_0_DLY_FIELD        (_MK_SHIFT_CONST(0xff) << XUSB_IDP_ULPI_PHY_CARKIT_INTDLY_0_DLY_SHIFT)
#define XUSB_IDP_ULPI_PHY_CARKIT_INTDLY_0_DLY_RANGE        7:0
#define XUSB_IDP_ULPI_PHY_CARKIT_INTDLY_0_DLY_WOFFSET      0
#define XUSB_IDP_ULPI_PHY_CARKIT_INTDLY_0_DLY_DEFAULT      (_MK_MASK_CONST(0x18)
#define XUSB_IDP_ULPI_PHY_CARKIT_INTDLY_0_DLY_DEFAULT_MASK (_MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_CARKIT_INTDLY_0_DLY_SW_DEFAULT   (_MK_MASK_CONST(0x18)
#define XUSB_IDP_ULPI_PHY_CARKIT_INTDLY_0_DLY_SW_DEFAULT_MASK (_MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0                     _MK_ADDR_CONST(0x1D)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_SECURE              0
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_WORD_COUNT          1
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_RESET_VAL           _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_RESET_MASK          _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_SW_DEFAULT_VAL      _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_SW_DEFAULT_MASK     _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_READ_MASK           _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_WRITE_MASK          _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_IDFLOATRISE_SHIFT    _MK_SHIFT_CONST(0)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_IDFLOATRISE_FIELD   (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_CARKIT_INT_0_IDFLOATRISE_SHIFT)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_IDFLOATRISE_RANGE   0:0
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_IDFLOATRISE_WOFFSET 0
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_IDFLOATRISE_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_IDFLOATRISE_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_IDFLOATRISE_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_IDFLOATRISE_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_IDFLOATRISE_DISABLED _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_IDFLOATRISE_ENABLED _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_IDFLOATFALL_SHIFT    _MK_SHIFT_CONST(1)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_IDFLOATFALL_FIELD   (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_CARKIT_INT_0_IDFLOATFALL_SHIFT)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_IDFLOATFALL_RANGE   1:1
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_IDFLOATFALL_WOFFSET 0
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_IDFLOATFALL_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_IDFLOATFALL_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_IDFLOATFALL_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_IDFLOATFALL_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_IDFLOATFALL_DISABLED _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_IDFLOATFALL_ENABLED _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARINTDET_SHIFT      _MK_SHIFT_CONST(2)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARINTDET_FIELD     (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARINTDET_SHIFT)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARINTDET_RANGE     2:2
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARINTDET_WOFFSET   0
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARINTDET_DEFAULT   (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARINTDET_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARINTDET_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARINTDET_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARINTDET_DISABLED  _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARINTDET_ENABLED   _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARDPRISE_SHIFT      _MK_SHIFT_CONST(3)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARDPRISE_FIELD     (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARDPRISE_SHIFT)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARDPRISE_RANGE     3:3
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARDPRISE_WOFFSET   0
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARDPRISE_DEFAULT   (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARDPRISE_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARDPRISE_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARDPRISE_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARDPRISE_DISABLED  _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARDPRISE_ENABLED   _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARDPFALL_SHIFT      _MK_SHIFT_CONST(4)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARDPFALL_FIELD     (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARDPFALL_SHIFT)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARDPFALL_RANGE     4:4
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARDPFALL_WOFFSET   0
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARDPFALL_DEFAULT   (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARDPFALL_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARDPFALL_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARDPFALL_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARDPFALL_DISABLED  _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_CARDPFALL_ENABLED   _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_RSVD_SHIFT           _MK_SHIFT_CONST(5)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_RSVD_FIELD          (_MK_SHIFT_CONST(0x7) << XUSB_IDP_ULPI_PHY_CARKIT_INT_0_RSVD_SHIFT)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_RSVD_RANGE          7:5
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_RSVD_WOFFSET        0
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_RSVD_DEFAULT        (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_RSVD_DEFAULT_MASK   (_MK_MASK_CONST(0x7)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_RSVD_SW_DEFAULT     (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_0_RSVD_SW_DEFAULT_MASK (_MK_MASK_CONST(0x7)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0              _MK_ADDR_CONST(0x20)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_SECURE       0
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_WORD_COUNT   1
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_RESET_VAL    _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_RESET_MASK   _MK_MASK_CONST(0x7)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_SW_DEFAULT_VAL _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_SW_DEFAULT_MASK _MK_MASK_CONST(0x7)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_READ_MASK    _MK_MASK_CONST(0x7)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_WRITE_MASK   _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_IDFLOAT_SHIFT  _MK_SHIFT_CONST(0)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_IDFLOAT_FIELD (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_IDFLOAT_SHIFT)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_IDFLOAT_RANGE 0:0
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_IDFLOAT_WOFFSET 0
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_IDFLOAT_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_IDFLOAT_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_IDFLOAT_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_IDFLOAT_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_IDFLOAT_LOW  _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_IDFLOAT_HIGH _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_CARINTDET_SHIFT  _MK_SHIFT_CONST(1)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_CARINTDET_FIELD (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_CARINTDET_SHIFT)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_CARINTDET_RANGE 1:1
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_CARINTDET_WOFFSET 0
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_CARINTDET_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_CARINTDET_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_CARINTDET_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_CARINTDET_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_CARINTDET_LOW _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_CARINTDET_HIGH _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_CARDP_SHIFT   _MK_SHIFT_CONST(2)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_CARDP_FIELD  (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_CARDP_SHIFT)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_CARDP_RANGE  2:2
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_CARDP_WOFFSET 0
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_CARDP_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_CARDP_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_CARDP_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_CARDP_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_CARDP_LOW    _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0_CARDP_HIGH   _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0               _MK_ADDR_CONST(0x21)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_SECURE        0
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_WORD_COUNT    1
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_RESET_VAL     _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_RESET_MASK    _MK_MASK_CONST(0x7)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_SW_DEFAULT_VAL _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_SW_DEFAULT_MASK _MK_MASK_CONST(0x7)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_READ_MASK     _MK_MASK_CONST(0x7)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_WRITE_MASK    _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_IDFLOAT_SHIFT  _MK_SHIFT_CONST(0)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_IDFLOAT_FIELD (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_IDFLOAT_SHIFT)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_IDFLOAT_RANGE 0:0
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_IDFLOAT_WOFFSET 0
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_IDFLOAT_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_IDFLOAT_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_IDFLOAT_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_IDFLOAT_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_IDFLOAT_LOW   _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_IDFLOAT_HIGH  _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_CARINTDET_SHIFT  _MK_SHIFT_CONST(1)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_CARINTDET_FIELD (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_CARINTDET_SHIFT)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_CARINTDET_RANGE 1:1
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_CARINTDET_WOFFSET 0
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_CARINTDET_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_CARINTDET_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_CARINTDET_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_CARINTDET_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_CARINTDET_LOW _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_CARINTDET_HIGH _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_CARDP_SHIFT    _MK_SHIFT_CONST(2)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_CARDP_FIELD   (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_CARDP_SHIFT)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_CARDP_RANGE   2:2
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_CARDP_WOFFSET 0
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_CARDP_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_CARDP_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_CARDP_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_CARDP_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_CARDP_LOW     _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0_CARDP_HIGH    _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0                _MK_ADDR_CONST(0x22)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_SECURE         0
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_WORD_COUNT     1
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_RESET_VAL      _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_RESET_MASK     _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_SW_DEFAULT_VAL _MK_MASK_CONST(0x0)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_SW_DEFAULT_MASK _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_READ_MASK      _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_WRITE_MASK     _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_TXPLSEN_SHIFT   _MK_SHIFT_CONST(0)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_TXPLSEN_FIELD  (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_TXPLSEN_SHIFT)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_TXPLSEN_RANGE  0:0
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_TXPLSEN_WOFFSET 0
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_TXPLSEN_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_TXPLSEN_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_TXPLSEN_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_TXPLSEN_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_TXPLSEN_OFF    _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_TXPLSEN_ON     _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_RXPLSEN_SHIFT   _MK_SHIFT_CONST(1)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_RXPLSEN_FIELD  (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_RXPLSEN_SHIFT)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_RXPLSEN_RANGE  1:1
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_RXPLSEN_WOFFSET 0
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_RXPLSEN_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_RXPLSEN_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_RXPLSEN_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_RXPLSEN_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_RXPLSEN_OFF    _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_RXPLSEN_ON     _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_SPKLEFTBIASEN_SHIFT  _MK_SHIFT_CONST(2)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_SPKLEFTBIASEN_FIELD (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_SPKLEFTBIASEN_SHIFT)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_SPKLEFTBIASEN_RANGE 2:2
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_SPKLEFTBIASEN_WOFFSET 0
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_SPKLEFTBIASEN_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_SPKLEFTBIASEN_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_SPKLEFTBIASEN_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_SPKLEFTBIASEN_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_SPKLEFTBIASEN_OFF _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_SPKLEFTBIASEN_ON _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_SPKRIGHTBIASEN_SHIFT  _MK_SHIFT_CONST(3)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_SPKRIGHTBIASEN_FIELD (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_SPKRIGHTBIASEN_SHIFT)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_SPKRIGHTBIASEN_RANGE 3:3
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_SPKRIGHTBIASEN_WOFFSET 0
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_SPKRIGHTBIASEN_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_SPKRIGHTBIASEN_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_SPKRIGHTBIASEN_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_SPKRIGHTBIASEN_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_SPKRIGHTBIASEN_OFF _MK_ENUM_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_SPKRIGHTBIASEN_ON _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_RSVD_SHIFT      _MK_SHIFT_CONST(4)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_RSVD_FIELD     (_MK_SHIFT_CONST(0xf) << XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_RSVD_SHIFT)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_RSVD_RANGE     7:4
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_RSVD_WOFFSET   0
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_RSVD_DEFAULT   (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_RSVD_DEFAULT_MASK (_MK_MASK_CONST(0xf)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_RSVD_SW_DEFAULT (_MK_MASK_CONST(0x00)
#define XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0_RSVD_SW_DEFAULT_MASK (_MK_MASK_CONST(0xf)
#define XUSB_IDP_ULPI_PHY_TXPOSWIDTH_0                     _MK_ADDR_CONST(0x25)
#define XUSB_IDP_ULPI_PHY_TXPOSWIDTH_0_SECURE              0
#define XUSB_IDP_ULPI_PHY_TXPOSWIDTH_0_WORD_COUNT          1
#define XUSB_IDP_ULPI_PHY_TXPOSWIDTH_0_RESET_VAL           _MK_MASK_CONST(0x10)
#define XUSB_IDP_ULPI_PHY_TXPOSWIDTH_0_RESET_MASK          _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_TXPOSWIDTH_0_SW_DEFAULT_VAL      _MK_MASK_CONST(0x10)
#define XUSB_IDP_ULPI_PHY_TXPOSWIDTH_0_SW_DEFAULT_MASK     _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_TXPOSWIDTH_0_READ_MASK           _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_TXPOSWIDTH_0_WRITE_MASK          _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_TXPOSWIDTH_0_WIDTH_SHIFT          _MK_SHIFT_CONST(0)
#define XUSB_IDP_ULPI_PHY_TXPOSWIDTH_0_WIDTH_FIELD         (_MK_SHIFT_CONST(0xff) << XUSB_IDP_ULPI_PHY_TXPOSWIDTH_0_WIDTH_SHIFT)
#define XUSB_IDP_ULPI_PHY_TXPOSWIDTH_0_WIDTH_RANGE         7:0
#define XUSB_IDP_ULPI_PHY_TXPOSWIDTH_0_WIDTH_WOFFSET       0
#define XUSB_IDP_ULPI_PHY_TXPOSWIDTH_0_WIDTH_DEFAULT       (_MK_MASK_CONST(0x10)
#define XUSB_IDP_ULPI_PHY_TXPOSWIDTH_0_WIDTH_DEFAULT_MASK  (_MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_TXPOSWIDTH_0_WIDTH_SW_DEFAULT    (_MK_MASK_CONST(0x10)
#define XUSB_IDP_ULPI_PHY_TXPOSWIDTH_0_WIDTH_SW_DEFAULT_MASK (_MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_TXNEGWIDTH_0                     _MK_ADDR_CONST(0x26)
#define XUSB_IDP_ULPI_PHY_TXNEGWIDTH_0_SECURE              0
#define XUSB_IDP_ULPI_PHY_TXNEGWIDTH_0_WORD_COUNT          1
#define XUSB_IDP_ULPI_PHY_TXNEGWIDTH_0_RESET_VAL           _MK_MASK_CONST(0x20)
#define XUSB_IDP_ULPI_PHY_TXNEGWIDTH_0_RESET_MASK          _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_TXNEGWIDTH_0_SW_DEFAULT_VAL      _MK_MASK_CONST(0x20)
#define XUSB_IDP_ULPI_PHY_TXNEGWIDTH_0_SW_DEFAULT_MASK     _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_TXNEGWIDTH_0_READ_MASK           _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_TXNEGWIDTH_0_WRITE_MASK          _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_TXNEGWIDTH_0_WIDTH_SHIFT          _MK_SHIFT_CONST(0)
#define XUSB_IDP_ULPI_PHY_TXNEGWIDTH_0_WIDTH_FIELD         (_MK_SHIFT_CONST(0xff) << XUSB_IDP_ULPI_PHY_TXNEGWIDTH_0_WIDTH_SHIFT)
#define XUSB_IDP_ULPI_PHY_TXNEGWIDTH_0_WIDTH_RANGE         7:0
#define XUSB_IDP_ULPI_PHY_TXNEGWIDTH_0_WIDTH_WOFFSET       0
#define XUSB_IDP_ULPI_PHY_TXNEGWIDTH_0_WIDTH_DEFAULT       (_MK_MASK_CONST(0x20)
#define XUSB_IDP_ULPI_PHY_TXNEGWIDTH_0_WIDTH_DEFAULT_MASK  (_MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_TXNEGWIDTH_0_WIDTH_SW_DEFAULT    (_MK_MASK_CONST(0x20)
#define XUSB_IDP_ULPI_PHY_TXNEGWIDTH_0_WIDTH_SW_DEFAULT_MASK (_MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_RXPOLLRCVRY_0                    _MK_ADDR_CONST(0x27)
#define XUSB_IDP_ULPI_PHY_RXPOLLRCVRY_0_SECURE             0
#define XUSB_IDP_ULPI_PHY_RXPOLLRCVRY_0_WORD_COUNT         1
#define XUSB_IDP_ULPI_PHY_RXPOLLRCVRY_0_RESET_VAL          _MK_MASK_CONST(0x2)
#define XUSB_IDP_ULPI_PHY_RXPOLLRCVRY_0_RESET_MASK         _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_RXPOLLRCVRY_0_SW_DEFAULT_VAL     _MK_MASK_CONST(0x2)
#define XUSB_IDP_ULPI_PHY_RXPOLLRCVRY_0_SW_DEFAULT_MASK    _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_RXPOLLRCVRY_0_READ_MASK          _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_RXPOLLRCVRY_0_WRITE_MASK         _MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_RXPOLLRCVRY_0_RCVRY_SHIFT         _MK_SHIFT_CONST(0)
#define XUSB_IDP_ULPI_PHY_RXPOLLRCVRY_0_RCVRY_FIELD        (_MK_SHIFT_CONST(0xff) << XUSB_IDP_ULPI_PHY_RXPOLLRCVRY_0_RCVRY_SHIFT)
#define XUSB_IDP_ULPI_PHY_RXPOLLRCVRY_0_RCVRY_RANGE        7:0
#define XUSB_IDP_ULPI_PHY_RXPOLLRCVRY_0_RCVRY_WOFFSET      0
#define XUSB_IDP_ULPI_PHY_RXPOLLRCVRY_0_RCVRY_DEFAULT      (_MK_MASK_CONST(0x02)
#define XUSB_IDP_ULPI_PHY_RXPOLLRCVRY_0_RCVRY_DEFAULT_MASK (_MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_PHY_RXPOLLRCVRY_0_RCVRY_SW_DEFAULT   (_MK_MASK_CONST(0x02)
#define XUSB_IDP_ULPI_PHY_RXPOLLRCVRY_0_RCVRY_SW_DEFAULT_MASK (_MK_MASK_CONST(0xff)
#define XUSB_IDP_ULPI_HOST_PHY_OVRD_0                      _MK_ADDR_CONST(0x30)
#define XUSB_IDP_ULPI_HOST_PHY_OVRD_0_SECURE               0
#define XUSB_IDP_ULPI_HOST_PHY_OVRD_0_WORD_COUNT           1
#define XUSB_IDP_ULPI_HOST_PHY_OVRD_0_RESET_VAL            _MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_HOST_PHY_OVRD_0_RESET_MASK           _MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_HOST_PHY_OVRD_0_SW_DEFAULT_VAL       _MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_HOST_PHY_OVRD_0_SW_DEFAULT_MASK      _MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_HOST_PHY_OVRD_0_READ_MASK            _MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_HOST_PHY_OVRD_0_WRITE_MASK           _MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_HOST_PHY_OVRD_0_NULL_MODE_DIR_SHIFT   _MK_SHIFT_CONST(0)
#define XUSB_IDP_ULPI_HOST_PHY_OVRD_0_NULL_MODE_DIR_FIELD  (_MK_SHIFT_CONST(0x1) << XUSB_IDP_ULPI_HOST_PHY_OVRD_0_NULL_MODE_DIR_SHIFT)
#define XUSB_IDP_ULPI_HOST_PHY_OVRD_0_NULL_MODE_DIR_RANGE  0:0
#define XUSB_IDP_ULPI_HOST_PHY_OVRD_0_NULL_MODE_DIR_WOFFSET 0
#define XUSB_IDP_ULPI_HOST_PHY_OVRD_0_NULL_MODE_DIR_DEFAULT (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_HOST_PHY_OVRD_0_NULL_MODE_DIR_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_HOST_PHY_OVRD_0_NULL_MODE_DIR_SW_DEFAULT (_MK_MASK_CONST(0x01)
#define XUSB_IDP_ULPI_HOST_PHY_OVRD_0_NULL_MODE_DIR_SW_DEFAULT_MASK (_MK_MASK_CONST(0x1)
#define XUSB_IDP_ULPI_HOST_PHY_OVRD_0_NULL_MODE_DIR_ON     _MK_ENUM_CONST(0x01)
#define XUSB_IDP_ULPI_HOST_PHY_OVRD_0_NULL_MODE_DIR_OFF    _MK_ENUM_CONST(0x00)
#define LIST_XUSB_IDP_REGS(_op_) \
  _op_(XUSB_IDP_ULPI_PHY_VENDOR_ID_1_0) \
  _op_(XUSB_IDP_ULPI_PHY_VENDOR_ID_2_0) \
  _op_(XUSB_IDP_ULPI_PHY_PRODUCT_ID_1_0) \
  _op_(XUSB_IDP_ULPI_PHY_PRODUCT_ID_2_0) \
  _op_(XUSB_IDP_ULPI_PHY_FN_CTL_0) \
  _op_(XUSB_IDP_ULPI_PHY_INTF_CTL_0) \
  _op_(XUSB_IDP_ULPI_PHY_OTG_CTL_0) \
  _op_(XUSB_IDP_ULPI_PHY_INTR_0) \
  _op_(XUSB_IDP_ULPI_PHY_INTF_0) \
  _op_(XUSB_IDP_ULPI_PHY_INT_STATUS_0) \
  _op_(XUSB_IDP_ULPI_PHY_INT_LATCH_0) \
  _op_(XUSB_IDP_ULPI_PHY_DEBUG_0) \
  _op_(XUSB_IDP_ULPI_PHY_SCRATCH_0) \
  _op_(XUSB_IDP_ULPI_PHY_CARKIT_CTL_0) \
  _op_(XUSB_IDP_ULPI_PHY_CARKIT_INTDLY_0) \
  _op_(XUSB_IDP_ULPI_PHY_CARKIT_INT_0) \
  _op_(XUSB_IDP_ULPI_PHY_CARKIT_INT_STATUS_0) \
  _op_(XUSB_IDP_ULPI_PHY_CARKIT_INT_LATCH_0) \
  _op_(XUSB_IDP_ULPI_PHY_CARKIT_PULSECTL_0) \
  _op_(XUSB_IDP_ULPI_PHY_TXPOSWIDTH_0) \
  _op_(XUSB_IDP_ULPI_PHY_TXNEGWIDTH_0) \
  _op_(XUSB_IDP_ULPI_PHY_RXPOLLRCVRY_0) \
  _op_(XUSB_IDP_ULPI_HOST_PHY_OVRD_0)
#ifndef _MK_SHIFT_CONST
  #define _MK_SHIFT_CONST(_constant_) _constant_
#endif
#ifndef _MK_MASK_CONST
  #define _MK_MASK_CONST(_constant_) _constant_
#endif
#ifndef _MK_ENUM_CONST
  #define _MK_ENUM_CONST(_constant_) (_constant_ ## UL)
#endif
#ifndef _MK_ADDR_CONST
  #define _MK_ADDR_CONST(_constant_) _constant_
#endif
#endif
