################################### tell Emacs this is a -*- makefile-gmake -*-
#
# Copyright (c) 2012-2013, NVIDIA CORPORATION.  All Rights Reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.
#
# tmake for SW Mobile component makefile
#
# libnvopenmax_common static library component makefile fragment
#
###############################################################################

ifdef NV_COMPONENT_FLAG_STATIC_LIBRARY_SECTION
include $(NV_BUILD_START_COMPONENT)

NV_COMPONENT_NAME              := libnvopenmax_common
NV_COMPONENT_OWN_INTERFACE_DIR := .
NV_COMPONENT_SOURCES           := \
	samplebase.c \
	omxtestlib.c \
	samplewindow_none.c

NV_COMPONENT_INCLUDES          := \
	$(NV_SOURCE)/camera/core/include \
	$(NV_SOURCE)/camera-partner/imager/include \
	$(NV_SOURCE)/multimedia-partner/nvmm/include \
	$(NV_SOURCE)/multimedia-partner/openmax/include/openmax/il

NV_COMPONENT_CFLAGS            += \
	-DOMXVERSION=2

ifeq ($(NV_BUILD_CONFIGURATION_LINUX_USERSPACE_IS_ANDROID),1)
NV_COMPONENT_HAS_BROKEN_CODE   := \
	sign-compare \
	missing-field-initializers
endif

include $(NV_BUILD_STATIC_LIBRARY)
endif

# Local Variables:
# indent-tabs-mode: t
# tab-width: 8
# End:
