################################### tell Emacs this is a -*- makefile-gmake -*-
#
# Copyright (c) 2012-2013 NVIDIA CORPORATION.  All Rights Reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.
#
# tmake for SW Mobile component makefile
#
# omxplayer dynamic binary component makefile
#
###############################################################################

ifdef NV_COMPONENT_FLAG_NVTEST_LIBRARY_SECTION
include $(NV_BUILD_START_COMPONENT)

NV_COMPONENT_NAME                       := omxplayer
NV_COMPONENT_SOURCES                    := \
        omxplayer.c \
        main_omxplayer.c \
        samplecomponent.c \
        sampleprotocol.c \
        nvhttppost.c

NV_COMPONENT_NEEDED_INTERFACE_DIRS      := \
        $(NV_SOURCE)/camera/core/nvmm_camera \
        $(NV_SOURCE)/camera-partner/imager/nvodm_imager \
        $(NV_SOURCE)/core/drivers/nvrm \
        $(NV_SOURCE)/multimedia-partner/nvmm/nvmm/utils \
        $(NV_SOURCE)/multimedia-partner/openmax/il

NV_COMPONENT_NEEDED_STATIC_INTERFACE_DIRS := \
	../common \
        $(NV_SOURCE)/core/utils/nvfxmath

NV_COMPONENT_CFLAGS                     += \
        -D__OMX_EXPORTS -DOMXVERSION=2

ifeq ($(NV_BUILD_CONFIGURATION_LINUX_USERSPACE_IS_ANDROID),1)
NV_COMPONENT_CFLAGS                     := \
        -DUSE_ANDROID_WINSYS=1
NV_COMPONENT_NEEDED_INTERFACE_DIRS      += \
	$(NV_INTERFACE_GPU_GRAPHICS_NVWINSYS_PRIVATE)
NV_COMPONENT_HAS_BROKEN_CODE            := ignore-all
else
NV_COMPONENT_CFLAGS                     := \
        -DUSE_ANDROID_WINSYS=0
endif

include $(NV_BUILD_NVTEST_LIBRARY)
endif

# Local Variables:
# indent-tabs-mode: t
# tab-width: 8
# End:
# vi: set tabstop=8 noexpandtab:
