# NVIDIA development system
#
# Copyright (c) 2012-2013, NVIDIA CORPORATION.  All rights reserved.
#
# !!! PLEASE DO NOT EDIT THIS FILE WITHOUT CONSULTING NVIDIA !!!

# default is tablet, we override this for shield and phones
NVSI_PRODUCT_CLASS ?= tablet

# not really used but we need to support legacy chips
ifneq ($(filter ap20 t30, $(TARGET_TEGRA_VERSION)),)
NVSI_XML_FILE := xml/com.nvidia.nvsi.default.xml
NVSI_XML_INCLUDE := com.nvidia.nvsi.default.xml.h
else
NVSI_XML_FILE := xml/com.nvidia.nvsi.$(TARGET_TEGRA_VERSION).$(NVSI_PRODUCT_CLASS).xml
NVSI_XML_INCLUDE := com.nvidia.nvsi.$(TARGET_TEGRA_VERSION).$(NVSI_PRODUCT_CLASS).xml.h
endif

# validate on non-engineering and non-simulation builds
ifneq ($(TARGET_BUILD_VARIANT),eng)
ifneq ($(TARGET_BOARD),simulation)

ifeq ($(wildcard $(TOP)/vendor/nvidia/tegra/secureos/nvsi/$(NVSI_XML_FILE)),)
$(error Unknown SOC detected: $(TARGET_TEGRA_VERSION))
endif

endif
endif
