# NVIDIA development system
#
# Copyright (c) 2012-2013, NVIDIA CORPORATION.  All rights reserved.
#
# !!! PLEASE DO NOT EDIT THIS FILE WITHOUT CONSULTING NVIDIA !!!

PRODUCT_PACKAGES += com.nvidia.nvsi
