################################### tell Emacs this is a -*- makefile-gmake -*-
#
# Copyright (c) 2012 NVIDIA CORPORATION.  All Rights Reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.
#
# tmake for SW Mobile
#
###############################################################################

ifdef NV_COMPONENT_FLAG_DYNAMIC_EXECUTABLE_SECTION
include $(NV_BUILD_START_COMPONENT)

NV_COMPONENT_NAME                  := cjpeg
NV_COMPONENT_SOURCES               := \
	cdjpeg.c \
	cjpeg.c \
	rdbmp.c \
	rdgif.c \
	rdppm.c \
	rdrle.c \
        rdswitch.c \
	rdtarga.c \
	rdy4m.c
NV_COMPONENT_NEEDED_INTERFACE_DIRS := \
	$(NV_SOURCE)/external/jpeg/libjpeg-6b

include $(NV_BUILD_DYNAMIC_EXECUTABLE)
endif

# Local Variables:
# indent-tabs-mode: t
# tab-width: 8
# End:
# vi: set tabstop=8 noexpandtab:
